-- MTRW v0.5 ADMIN SYSTEM
-- Run after supabase/schema.sql
-- Master account is identified by email. No password is stored here.

create table if not exists public.admin_roles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  role text not null check (role in ('moderator','administrator','senior_admin','master')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_sanctions (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  kicked_until timestamptz,
  banned_until timestamptz,
  ban_reason text,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_user_id uuid references public.profiles(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_logs_created_idx on public.admin_logs(created_at desc);
create index if not exists admin_logs_target_idx on public.admin_logs(target_user_id);

alter table public.admin_roles enable row level security;
alter table public.player_sanctions enable row level security;
alter table public.admin_logs enable row level security;

-- No direct client writes. Admin operations go through SECURITY DEFINER RPCs.
create or replace function public.is_admin(p_uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_roles where user_id=p_uid);
$$;

grant execute on function public.is_admin(uuid) to authenticated;

-- Automatically make the designated master email the master on account creation.
create or replace function public.bootstrap_master_admin()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  target_email text := 'mafiatherealworld@gmail.com';
begin
  if lower(new.email) = target_email then
    insert into public.admin_roles(user_id, role)
    values(new.id, 'master')
    on conflict(user_id) do update set role='master', updated_at=now();
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_master on auth.users;
create trigger on_auth_user_created_master
after insert on auth.users
for each row execute procedure public.bootstrap_master_admin();

-- Also allow the SQL to be run after the master account already exists.
insert into public.admin_roles(user_id, role)
select id, 'master' from public.profiles
where lower(id::text) in (select id::text from auth.users where lower(email)='mafiatherealworld@gmail.com')
on conflict(user_id) do update set role='master', updated_at=now();

create or replace function public.admin_role()
returns text language sql stable security definer set search_path=public as $$
  select coalesce((select role from public.admin_roles where user_id=auth.uid()), 'player');
$$;
grant execute on function public.admin_role() to authenticated;

create or replace function public.admin_list_players()
returns table(
  id uuid, username text, mafia_name text, money bigint, reputation integer,
  created_at timestamptz, updated_at timestamptz, role text,
  banned_until timestamptz, ban_reason text, territory_count bigint
)
language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'admin_required'; end if;
  return query
  select p.id,p.username,p.mafia_name,p.money,p.reputation,p.created_at,p.updated_at,
         coalesce(ar.role,'player'),ps.banned_until,ps.ban_reason,
         (select count(*) from public.territories t where t.owner_id=p.id)
  from public.profiles p
  left join public.admin_roles ar on ar.user_id=p.id
  left join public.player_sanctions ps on ps.user_id=p.id
  order by p.created_at desc;
end;
$$;
grant execute on function public.admin_list_players() to authenticated;

create or replace function public.admin_logs_list(p_limit integer default 100)
returns setof public.admin_logs
language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'admin_required'; end if;
  return query select * from public.admin_logs order by created_at desc limit least(greatest(p_limit,1),500);
end;
$$;
grant execute on function public.admin_logs_list(integer) to authenticated;

create or replace function public.admin_set_role(p_target uuid, p_role text)
returns json language plpgsql security definer set search_path=public as $$
declare actor_role text := public.admin_role();
begin
  if actor_role <> 'master' then raise exception 'master_required'; end if;
  if p_target = auth.uid() and p_role <> 'master' then raise exception 'master_cannot_demote_self'; end if;
  if p_role not in ('player','moderator','administrator','senior_admin','master') then raise exception 'invalid_role'; end if;
  if p_role='player' then delete from public.admin_roles where user_id=p_target;
  else insert into public.admin_roles(user_id,role) values(p_target,p_role) on conflict(user_id) do update set role=excluded.role,updated_at=now(); end if;
  insert into public.admin_logs(admin_id,action,target_user_id,details) values(auth.uid(),'set_role',p_target,json_build_object('role',p_role));
  return json_build_object('success',true,'role',p_role);
end;
$$;
grant execute on function public.admin_set_role(uuid,text) to authenticated;

create or replace function public.admin_ban(p_target uuid,p_duration_minutes integer,p_reason text default 'Kein Grund angegeben')
returns json language plpgsql security definer set search_path=public as $$
declare actor_role text:=public.admin_role(); until_at timestamptz;
begin
  if actor_role not in ('moderator','administrator','senior_admin','master') then raise exception 'admin_required'; end if;
  if p_target=auth.uid() then raise exception 'cannot_sanction_self'; end if;
  if p_duration_minutes < 0 then raise exception 'invalid_duration'; end if;
  until_at:=case when p_duration_minutes=0 then null else now()+make_interval(mins=>p_duration_minutes) end;
  insert into public.player_sanctions(user_id,banned_until,ban_reason,updated_at) values(p_target,until_at,p_reason,now())
  on conflict(user_id) do update set banned_until=excluded.banned_until,ban_reason=excluded.ban_reason,updated_at=now();
  insert into public.admin_logs(admin_id,action,target_user_id,details) values(auth.uid(),'ban',p_target,json_build_object('minutes',p_duration_minutes,'reason',p_reason));
  return json_build_object('success',true,'banned_until',until_at);
end;
$$;
grant execute on function public.admin_ban(uuid,integer,text) to authenticated;

create or replace function public.admin_unban(p_target uuid)
returns json language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'admin_required'; end if;
  update public.player_sanctions set banned_until=null,ban_reason=null,updated_at=now() where user_id=p_target;
  insert into public.admin_logs(admin_id,action,target_user_id) values(auth.uid(),'unban',p_target);
  return json_build_object('success',true);
end;
$$;
grant execute on function public.admin_unban(uuid) to authenticated;

create or replace function public.admin_kick(p_target uuid,p_minutes integer default 5,p_reason text default 'Von einem Admin gekickt')
returns json language plpgsql security definer set search_path=public as $$
declare until_at timestamptz;
begin
  if not public.is_admin() then raise exception 'admin_required'; end if;
  if p_target=auth.uid() then raise exception 'cannot_sanction_self'; end if;
  until_at:=now()+make_interval(mins=>greatest(p_minutes,1));
  insert into public.player_sanctions(user_id,kicked_until,updated_at) values(p_target,until_at,now())
  on conflict(user_id) do update set kicked_until=excluded.kicked_until,updated_at=now();
  insert into public.admin_logs(admin_id,action,target_user_id,details) values(auth.uid(),'kick',p_target,json_build_object('minutes',p_minutes,'reason',p_reason));
  return json_build_object('success',true,'kicked_until',until_at);
end;
$$;
grant execute on function public.admin_kick(uuid,integer,text) to authenticated;

create or replace function public.admin_set_player(p_target uuid,p_money bigint default null,p_reputation integer default null)
returns json language plpgsql security definer set search_path=public as $$
declare r text:=public.admin_role(); m bigint; rep integer;
begin
  if r not in ('administrator','senior_admin','master') then raise exception 'permission_denied'; end if;
  update public.profiles set money=case when p_money is null then money else greatest(p_money,0) end,
    reputation=case when p_reputation is null then reputation else greatest(p_reputation,0) end,updated_at=now()
    where id=p_target returning money,reputation into m,rep;
  if not found then raise exception 'player_not_found'; end if;
  insert into public.admin_logs(admin_id,action,target_user_id,details) values(auth.uid(),'set_player',p_target,json_build_object('money',p_money,'reputation',p_reputation));
  return json_build_object('success',true,'money',m,'reputation',rep);
end;
$$;
grant execute on function public.admin_set_player(uuid,bigint,integer) to authenticated;

create or replace function public.admin_delete_territory(p_zone_key text)
returns json language plpgsql security definer set search_path=public as $$
begin
  if public.admin_role() not in ('administrator','senior_admin','master') then raise exception 'permission_denied'; end if;
  delete from public.territories where zone_key=p_zone_key;
  insert into public.admin_logs(admin_id,action,details) values(auth.uid(),'delete_territory',json_build_object('zone_key',p_zone_key));
  return json_build_object('success',true);
end;
$$;
grant execute on function public.admin_delete_territory(text) to authenticated;

create or replace function public.player_access_status()
returns json language plpgsql security definer set search_path=public as $$
declare s public.player_sanctions; r text:=public.admin_role();
begin
  select * into s from public.player_sanctions where user_id=auth.uid();
  if s.banned_until is not null and (s.banned_until > now() or s.banned_until is null) then
    return json_build_object('allowed',false,'type','ban','until',s.banned_until,'reason',s.ban_reason);
  end if;
  if s.kicked_until is not null and s.kicked_until > now() then
    return json_build_object('allowed',false,'type','kick','until',s.kicked_until,'reason','Du wurdest gekickt.');
  end if;
  return json_build_object('allowed',true,'role',r);
end;
$$;
grant execute on function public.player_access_status() to authenticated;

-- Prevent direct table manipulation of admin data.
drop policy if exists admin_roles_no_direct_read on public.admin_roles;
create policy admin_roles_no_direct_read on public.admin_roles for select using (auth.uid()=user_id or public.is_admin());
drop policy if exists sanctions_admin_read on public.player_sanctions;
create policy sanctions_admin_read on public.player_sanctions for select using (auth.uid()=user_id or public.is_admin());
drop policy if exists logs_admin_read on public.admin_logs;
create policy logs_admin_read on public.admin_logs for select using (public.is_admin());
