-- MAFIVERA V1 — Spielerprofil + Familien / Diplomatie
-- Nach dem Deploy einmal im Supabase SQL Editor ausführen.

create table if not exists public.mtrw_families (
  id text primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  tag text not null,
  description text not null default 'Zusammenhalt, Ehre, Familie',
  image_url text,
  level integer not null default 1 check(level>=1),
  points bigint not null default 0 check(points>=0),
  treasury bigint not null default 0 check(treasury>=0),
  member_cap integer not null default 10 check(member_cap>=1),
  wins integer not null default 0,
  losses integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists mtrw_families_name_idx on public.mtrw_families(lower(name));
create index if not exists mtrw_families_tag_idx on public.mtrw_families(lower(tag));

create table if not exists public.mtrw_family_members (
  family_id text not null references public.mtrw_families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'Mitglied',
  family_points bigint not null default 0 check(family_points>=0),
  donated_total bigint not null default 0 check(donated_total>=0),
  joined_at timestamptz not null default now(),
  last_donation_at timestamptz,
  primary key(family_id,user_id),
  unique(user_id)
);
create index if not exists mtrw_family_members_user_idx on public.mtrw_family_members(user_id);

create table if not exists public.mtrw_family_upgrades (
  family_id text not null references public.mtrw_families(id) on delete cascade,
  upgrade_key text not null,
  level integer not null default 0 check(level>=0),
  updated_at timestamptz not null default now(),
  primary key(family_id,upgrade_key)
);

create table if not exists public.mtrw_family_diplomacy (
  id bigint generated by default as identity primary key,
  family_id text not null references public.mtrw_families(id) on delete cascade,
  target_family_id text not null references public.mtrw_families(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','allied','declined','ended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(family_id,target_family_id),
  check(family_id<>target_family_id)
);
create index if not exists mtrw_family_diplomacy_target_idx on public.mtrw_family_diplomacy(target_family_id,status);

alter table public.mtrw_families enable row level security;
alter table public.mtrw_family_members enable row level security;
alter table public.mtrw_family_upgrades enable row level security;
alter table public.mtrw_family_diplomacy enable row level security;

drop policy if exists mtrw_families_read on public.mtrw_families;
create policy mtrw_families_read on public.mtrw_families for select to authenticated using (true);
drop policy if exists mtrw_families_insert on public.mtrw_families;
create policy mtrw_families_insert on public.mtrw_families for insert to authenticated with check(owner_id=auth.uid());
drop policy if exists mtrw_families_update on public.mtrw_families;
create policy mtrw_families_update on public.mtrw_families for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());

drop policy if exists mtrw_family_members_read on public.mtrw_family_members;
create policy mtrw_family_members_read on public.mtrw_family_members for select to authenticated using (user_id=auth.uid() or exists(select 1 from public.mtrw_family_members me where me.family_id=mtrw_family_members.family_id and me.user_id=auth.uid()));
drop policy if exists mtrw_family_members_insert on public.mtrw_family_members;
create policy mtrw_family_members_insert on public.mtrw_family_members for insert to authenticated with check(user_id=auth.uid());
drop policy if exists mtrw_family_members_update on public.mtrw_family_members;
create policy mtrw_family_members_update on public.mtrw_family_members for update to authenticated using(user_id=auth.uid());
drop policy if exists mtrw_family_members_delete on public.mtrw_family_members;
create policy mtrw_family_members_delete on public.mtrw_family_members for delete to authenticated using(user_id=auth.uid() or exists(select 1 from public.mtrw_families f where f.id=family_id and f.owner_id=auth.uid()));

drop policy if exists mtrw_family_upgrades_read on public.mtrw_family_upgrades;
create policy mtrw_family_upgrades_read on public.mtrw_family_upgrades for select to authenticated using(true);
drop policy if exists mtrw_family_upgrades_write on public.mtrw_family_upgrades;
create policy mtrw_family_upgrades_write on public.mtrw_family_upgrades for all to authenticated using(exists(select 1 from public.mtrw_families f where f.id=family_id and f.owner_id=auth.uid())) with check(exists(select 1 from public.mtrw_families f where f.id=family_id and f.owner_id=auth.uid()));

drop policy if exists mtrw_family_diplomacy_read on public.mtrw_family_diplomacy;
create policy mtrw_family_diplomacy_read on public.mtrw_family_diplomacy for select to authenticated using(exists(select 1 from public.mtrw_family_members m where m.family_id=mtrw_family_diplomacy.family_id and m.user_id=auth.uid()) or exists(select 1 from public.mtrw_family_members m where m.family_id=mtrw_family_diplomacy.target_family_id and m.user_id=auth.uid()));
drop policy if exists mtrw_family_diplomacy_insert on public.mtrw_family_diplomacy;
create policy mtrw_family_diplomacy_insert on public.mtrw_family_diplomacy for insert to authenticated with check(exists(select 1 from public.mtrw_family_members m where m.family_id=family_id and m.user_id=auth.uid()));
drop policy if exists mtrw_family_diplomacy_update on public.mtrw_family_diplomacy;
create policy mtrw_family_diplomacy_update on public.mtrw_family_diplomacy for update to authenticated using(exists(select 1 from public.mtrw_family_members m where (m.family_id=family_id or m.family_id=target_family_id) and m.user_id=auth.uid())) with check(true);

create or replace function public.mtrw_family_xp_requirement(p_level integer) returns bigint language sql immutable as $$ select round(500*power(1.65,greatest(0,p_level-1)))::bigint; $$;

create or replace function public.mtrw_family_donate(p_family_id text,p_amount bigint) returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid();m public.mtrw_family_members;f public.mtrw_families;today date:=current_date;new_level integer;begin
 if uid is null then raise exception 'not_authenticated'; end if;
 if p_amount<=0 or p_amount>5000 then raise exception 'invalid_amount'; end if;
 select * into m from public.mtrw_family_members where family_id=p_family_id and user_id=uid for update;
 if not found then raise exception 'not_family_member'; end if;
 if m.last_donation_at is not null and (m.last_donation_at at time zone 'utc')::date=today then raise exception 'already_donated_today'; end if;
 update public.profiles set money=money-p_amount,updated_at=now() where id=uid and money>=p_amount;
 if not found then raise exception 'insufficient_money'; end if;
 update public.mtrw_family_members set donated_total=donated_total+p_amount,family_points=family_points+floor(p_amount/10),last_donation_at=now() where family_id=p_family_id and user_id=uid;
 update public.mtrw_families set treasury=treasury+p_amount,points=points+floor(p_amount/10),updated_at=now() where id=p_family_id returning * into f;
 while f.points>=public.mtrw_family_xp_requirement(f.level) loop
   f.points:=f.points-public.mtrw_family_xp_requirement(f.level);f.level:=f.level+1;f.member_cap:=10+(f.level-1)*5;
 end loop;
 update public.mtrw_families set points=f.points,level=f.level,member_cap=f.member_cap,updated_at=now() where id=p_family_id;
 return json_build_object('success',true,'family_id',p_family_id,'level',f.level,'points',f.points,'treasury',f.treasury,'member_cap',f.member_cap);
end;$$;
grant execute on function public.mtrw_family_donate(text,bigint) to authenticated;

create or replace function public.mtrw_family_join(p_family_id text) returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid();f public.mtrw_families;cnt integer;begin
 if uid is null then raise exception 'not_authenticated'; end if;
 select * into f from public.mtrw_families where id=p_family_id for update;
 if not found then raise exception 'family_not_found';end if;
 if exists(select 1 from public.mtrw_family_members where user_id=uid) then raise exception 'already_in_family';end if;
 select count(*) into cnt from public.mtrw_family_members where family_id=p_family_id;
 if cnt>=f.member_cap then raise exception 'family_full';end if;
 insert into public.mtrw_family_members(family_id,user_id,role) values(p_family_id,uid,'Mitglied');
 return json_build_object('success',true,'family_id',p_family_id);
end;$$;
grant execute on function public.mtrw_family_join(text) to authenticated;

create or replace function public.mtrw_family_create(p_id text,p_name text,p_tag text,p_description text,p_image_url text) returns json language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid();begin
 if uid is null then raise exception 'not_authenticated';end if;
 if exists(select 1 from public.mtrw_family_members where user_id=uid) then raise exception 'already_in_family';end if;
 insert into public.mtrw_families(id,owner_id,name,tag,description,image_url) values(p_id,uid,left(trim(p_name),32),left(upper(trim(p_tag)),6),coalesce(nullif(trim(p_description),''),'Zusammenhalt, Ehre, Familie'),nullif(trim(p_image_url),''));
 insert into public.mtrw_family_members(family_id,user_id,role) values(p_id,uid,'Anführer');
 return json_build_object('success',true,'family_id',p_id);
end;$$;
grant execute on function public.mtrw_family_create(text,text,text,text,text) to authenticated;
