-- MTRW Discord/game audit log storage
create table if not exists public.game_logs(
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  category text not null check(category in ('game','player','register','chat')),
  event text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists game_logs_created_idx on public.game_logs(created_at desc);
create index if not exists game_logs_category_idx on public.game_logs(category,created_at desc);
create index if not exists game_logs_user_idx on public.game_logs(user_id,created_at desc);
alter table public.game_logs enable row level security;
drop policy if exists game_logs_no_client_select on public.game_logs;
-- Logs are written/read by the secure Edge Function with the service role.
-- No direct client access is granted.
revoke all on public.game_logs from anon,authenticated;
