/* MTRW v0.5 - Admin UI. All sensitive actions are server-side RPCs. */
(async()=>{
  if(!window.db) return;
  const {data:{session}}=await window.db.auth.getSession(); if(!session) return;
  const roleRes=await window.db.rpc('admin_role'); if(roleRes.error || !roleRes.data || roleRes.data==='player') return;
  const role=roleRes.data;
  const canManagePlayers=['administrator','senior_admin','master'].includes(role);
  const canManageAdmins=role==='master';
  const btn=document.createElement('button'); btn.id='adminBtn'; btn.className='secondary'; btn.textContent='🛡️ Admin';
  btn.style.cssText='position:fixed;right:12px;top:70px;z-index:1600;width:auto;min-width:110px;margin:0'; document.body.appendChild(btn);
  const overlay=document.createElement('div'); overlay.id='adminOverlay'; overlay.hidden=true; overlay.innerHTML=`<div class="admin-card"><div class="admin-head"><div><b>🛡️ MTRW ADMIN</b><small>Rolle: ${escapeHtml(role)}</small></div><button id="adminClose" class="secondary">✕</button></div><div class="admin-tabs"><button id="playersTab" class="primary">👥 Spieler</button><button id="logsTab" class="secondary">📜 Logs</button></div><div id="adminContent"></div></div>`; document.body.appendChild(overlay);
  const content=overlay.querySelector('#adminContent');
  btn.onclick=()=>{overlay.hidden=false;loadPlayers()}; overlay.querySelector('#adminClose').onclick=()=>overlay.hidden=true;
  overlay.querySelector('#playersTab').onclick=loadPlayers; overlay.querySelector('#logsTab').onclick=loadLogs;
  async function loadPlayers(){content.innerHTML='<p class="muted">Spieler werden geladen…</p>';const {data,error}=await window.db.rpc('admin_list_players');if(error){content.innerHTML='<p class="error">'+escapeHtml(error.message)+'</p>';return}content.innerHTML=`<input id="playerSearch" class="admin-search" placeholder="Spieler suchen…"><div id="playerList"></div>`;const list=content.querySelector('#playerList');function render(){const q=content.querySelector('#playerSearch').value.toLowerCase();list.innerHTML='';(data||[]).filter(p=>[p.username,p.mafia_name,p.role].join(' ').toLowerCase().includes(q)).forEach(p=>list.appendChild(playerCard(p)))}content.querySelector('#playerSearch').oninput=render;render()}
  function playerCard(p){const el=document.createElement('div');el.className='player-card';const banned=p.banned_until&&new Date(p.banned_until)>new Date();el.innerHTML=`<div class="player-main"><b>${escapeHtml(p.username)}</b><span>${escapeHtml(p.role)} · ${p.territory_count} Gebiete</span><span>💵 $${Number(p.money).toLocaleString('de-DE')} · ⭐ ${p.reputation}</span>${banned?'<span class="ban">🔨 GEBANNT: '+escapeHtml(p.ban_reason||'ohne Grund')+'</span>':''}</div><div class="player-actions"><button class="secondary" data-a="kick">🚪 Kick</button><button class="danger" data-a="ban">🔨 Bann</button>${banned?'<button class="secondary" data-a="unban">🔓 Entbannen</button>':''}${canManagePlayers?'<button class="secondary" data-a="stats">💰 Werte</button>':''}${canManageAdmins?'<button class="secondary" data-a="role">🛡️ Rolle</button>':''}</div>`;el.querySelectorAll('button').forEach(b=>b.onclick=()=>action(b.dataset.a,p));return el}
  async function action(a,p){if(a==='kick'){const reason=prompt('Kick-Grund:','Von einem Admin gekickt');if(reason===null)return;await call('admin_kick',{p_target:p.id,p_minutes:5,p_reason:reason});return loadPlayers()}if(a==='ban'){const d=prompt('Bann-Dauer in Minuten (0 = 100 Jahre/permanent):','60');if(d===null)return;const reason=prompt('Bann-Grund:','Verstoß gegen die Spielregeln');if(reason===null)return;await call('admin_ban',{p_target:p.id,p_duration_minutes:Math.max(0,Number(d)||0),p_reason:reason});return loadPlayers()}if(a==='unban'){await call('admin_unban',{p_target:p.id});return loadPlayers()}if(a==='stats'){const money=prompt('Neues Geld:',p.money);if(money===null)return;const rep=prompt('Neue Reputation:',p.reputation);if(rep===null)return;await call('admin_set_player',{p_target:p.id,p_money:Math.max(0,Number(money)||0),p_reputation:Math.max(0,Number(rep)||0)});return loadPlayers()}if(a==='role'){const r=prompt('Rolle: player / moderator / administrator / senior_admin / master',p.role);if(r===null)return;await call('admin_set_role',{p_target:p.id,p_role:r});return loadPlayers()}}
  async function call(fn,args){const {error}=await window.db.rpc(fn,args);if(error)alert('Admin-Aktion fehlgeschlagen: '+error.message);else alert('Aktion erfolgreich ausgeführt.')}
  async function loadLogs(){content.innerHTML='<p class="muted">Logs werden geladen…</p>';const {data,error}=await window.db.rpc('admin_logs_list',{p_limit:200});if(error){content.innerHTML='<p class="error">'+escapeHtml(error.message)+'</p>';return}content.innerHTML='<div class="log-list">'+(data||[]).map(x=>`<div class="log"><b>${escapeHtml(x.action)}</b><span>${new Date(x.created_at).toLocaleString('de-DE')}</span><small>${escapeHtml(JSON.stringify(x.details||{}))}</small></div>`).join('')+'</div>'}
  function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
})();