/* MTRW v0.7 - Admin UI. Permissions are enforced server-side by Supabase RPCs. */
(async()=>{
  if(!window.db)return;
  const {data:{session}}=await window.db.auth.getSession();if(!session)return;
  const roleRes=await window.db.rpc('admin_role');if(roleRes.error)return;
  const rawRole=roleRes.data||'player';if(rawRole==='player'||rawRole==='supporter')return;
  const role=rawRole==='master'?'administrator':rawRole,isMaster=rawRole==='master';
  const canModerate=['moderator','administrator'].includes(role)||isMaster,canAdmin=role==='administrator'||isMaster;
  const roleLabel=role==='administrator'?(isMaster?'Administrator · MASTER':'Administrator'):'Moderator';
  const btn=document.createElement('button');btn.id='adminBtn';btn.className='secondary';btn.textContent='🛡️ Admin';btn.style.cssText='position:fixed;right:12px;top:70px;z-index:1600;width:auto;min-width:110px;margin:0';document.body.appendChild(btn);
  const overlay=document.createElement('div');overlay.id='adminOverlay';overlay.hidden=true;overlay.innerHTML=`<div class="admin-card"><div class="admin-head"><div><b>🛡️ MTRW ADMIN</b><small>Rang: ${escapeHtml(roleLabel)}</small></div><button id="adminClose" class="secondary">✕</button></div><div class="admin-tabs"><button id="playersTab" class="primary">👥 Spieler</button><button id="logsTab" class="secondary">📜 Logs</button></div><div id="adminContent"></div></div>`;document.body.appendChild(overlay);
  const content=overlay.querySelector('#adminContent');btn.onclick=()=>{overlay.hidden=false;loadPlayers()};overlay.querySelector('#adminClose').onclick=()=>overlay.hidden=true;overlay.querySelector('#playersTab').onclick=loadPlayers;overlay.querySelector('#logsTab').onclick=loadLogs;
  function roleName(r){return r==='master'?'Administrator · MASTER':r==='administrator'?'Administrator':r==='moderator'?'Moderator':r==='supporter'?'Supporter':'Spieler'}
  function timeLeft(ts){if(!ts)return'';const ms=new Date(ts)-Date.now();if(ms<=0)return'';const min=Math.ceil(ms/60000);if(min<60)return`${min} Min.`;return`${Math.ceil(min/60)} Std.`}
  async function loadPlayers(){content.innerHTML='<p class="muted">Spieler werden geladen…</p>';const{data,error}=await window.db.rpc('admin_list_players');if(error){content.innerHTML='<p class="error">'+escapeHtml(error.message)+'</p>';return}content.innerHTML=`<div class="admin-perms"><b>${escapeHtml(roleLabel)}</b> · ${role==='moderator'?'Moderation bis 24h Bann':'Volle Administration'}</div><input id="playerSearch" class="admin-search" placeholder="Spieler suchen…"><div id="playerList"></div>`;const list=content.querySelector('#playerList');function render(){const q=content.querySelector('#playerSearch').value.toLowerCase();list.innerHTML='';(data||[]).filter(p=>[p.username,p.mafia_name,p.role].join(' ').toLowerCase().includes(q)).forEach(p=>list.appendChild(playerCard(p)))}content.querySelector('#playerSearch').oninput=render;render()}
  function playerCard(p){const el=document.createElement('div');el.className='player-card';const banned=p.banned_until&&new Date(p.banned_until)>new Date(),muted=p.muted_until&&new Date(p.muted_until)>new Date(),kicked=p.kicked_until&&new Date(p.kicked_until)>new Date(),targetIsMaster=p.role==='master';let actions='';if(canModerate&&!targetIsMaster){actions+=`<button class="secondary" data-a="kick">🚪 Kick</button>`;actions+=`<button class="secondary" data-a="mute">${muted?'🔊 Entmuten':'🔇 Mute'}</button>`;actions+=`<button class="danger" data-a="ban">🔨 ${banned?'Bann ändern':'Bann'}</button>`;if(banned&&canAdmin)actions+=`<button class="secondary" data-a="unban">🔓 Entbannen</button>`}if(canAdmin&&!targetIsMaster){actions+=`<button class="secondary" data-a="stats">💰 Werte</button>`;actions+=`<button class="secondary" data-a="role">🛡️ Rolle</button>`}el.innerHTML=`<div class="player-main"><b>${escapeHtml(p.username)}</b><span>🏷️ ${escapeHtml(roleName(p.role))} · 🏴 ${p.territory_count} Gebiete</span><span>💵 $${Number(p.money).toLocaleString('de-DE')} · ⭐ ${p.reputation}</span>${kicked?'<span class="ban">🚪 Gekickt: '+escapeHtml(timeLeft(p.kicked_until))+'</span>':''}${muted?'<span class="ban">🔇 Gemutet: '+escapeHtml(timeLeft(p.muted_until))+(p.mute_reason?' · '+escapeHtml(p.mute_reason):'')+'</span>':''}${banned?'<span class="ban">🔨 GEBANNT: '+escapeHtml(timeLeft(p.banned_until)||'dauerhaft')+(p.ban_reason?' · '+escapeHtml(p.ban_reason):'')+'</span>':''}</div><div class="player-actions">${actions}</div>`;el.querySelectorAll('button').forEach(b=>b.onclick=()=>action(b.dataset.a,p));return el}
  async function action(a,p){if(a==='kick'){const reason=prompt('Kick-Grund:','Verstoß gegen die Spielregeln');if(reason===null)return;await call('admin_kick',{p_target:p.id,p_minutes:5,p_reason:reason},p);return loadPlayers()}if(a==='mute'){if(p.muted_until&&new Date(p.muted_until)>new Date()){await call('admin_unmute',{p_target:p.id},p);return loadPlayers()}const d=prompt('Mute-Dauer in Minuten:','30');if(d===null)return;const minutes=Math.max(1,Math.floor(Number(d)||0)),reason=prompt('Mute-Grund:','Verstoß gegen die Chatregeln');if(reason===null)return;await call('admin_mute',{p_target:p.id,p_duration_minutes:minutes,p_reason:reason},p);return loadPlayers()}if(a==='ban'){let d;if(role==='moderator'&&!isMaster){d=prompt('Bann-Dauer in Minuten (max. 1440 = 24 Stunden):','60');if(d===null)return;const n=Math.floor(Number(d)||0);if(n<1||n>1440){alert('Als Moderator sind nur Banns von 1 Minute bis maximal 24 Stunden erlaubt.');return}d=n}else{d=prompt('Bann-Dauer in Minuten (0 = dauerhaft):','60');if(d===null)return;d=Math.max(0,Math.floor(Number(d)||0))}const reason=prompt('Bann-Grund:','Verstoß gegen die Spielregeln');if(reason===null)return;await call('admin_ban',{p_target:p.id,p_duration_minutes:d,p_reason:reason},p);return loadPlayers()}if(a==='unban'){await call('admin_unban',{p_target:p.id},p);return loadPlayers()}if(a==='stats'){const money=prompt('Neues Geld:',p.money);if(money===null)return;const rep=prompt('Neue Reputation:',p.reputation);if(rep===null)return;await call('admin_set_player',{p_target:p.id,p_money:Math.max(0,Math.floor(Number(money)||0)),p_reputation:Math.max(0,Math.floor(Number(rep)||0))},p);return loadPlayers()}if(a==='role'){const r=prompt('Rolle: player / supporter / moderator / administrator',p.role==='master'?'administrator':p.role);if(r===null)return;if(!['player','supporter','moderator','administrator'].includes(r)){alert('Ungültige Rolle.');return}await call('admin_set_role',{p_target:p.id,p_role:r},p);return loadPlayers()}}
  async function call(fn,args,p){const{error}=await window.db.rpc(fn,args);if(error){alert('Admin-Aktion fehlgeschlagen: '+error.message);return}const category=['admin_mute','admin_unmute'].includes(fn)?'chat':'player';window.mtrwLog?.(category,`Moderationsaktion: ${fn}`,{target_user_id:p?.id||null,...args});alert('Aktion erfolgreich ausgeführt.')}
  async function loadLogs(){content.innerHTML='<p class="muted">Logs werden geladen…</p>';const{data,error}=await window.db.rpc('admin_logs_list',{p_limit:200});if(error){content.innerHTML='<p class="error">'+escapeHtml(error.message)+'</p>';return}content.innerHTML='<div class="log-list">'+(data||[]).map(x=>`<div class="log"><b>${escapeHtml(x.action)}</b><span>${new Date(x.created_at).toLocaleString('de-DE')}</span><small>${escapeHtml(JSON.stringify(x.details||{}))}</small></div>`).join('')+'</div>'}
  function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
})();