/* MAFIVERA V1 — buildings, storage and visible building markers */
(()=>{'use strict';
const markerCss=document.createElement('style');markerCss.textContent=`.mtrw-building-pin{display:flex;flex-direction:column;align-items:center;justify-content:center;min-width:82px;transform:translateY(-2px);pointer-events:none}.mtrw-building-pin span{font-size:28px;line-height:29px;text-shadow:0 2px 5px #000,0 0 3px #000}.mtrw-building-pin b{margin-top:2px;padding:2px 6px;border-radius:7px;background:rgba(5,8,12,.92);border:1px solid rgba(255,255,255,.16);color:#fff;font-size:9px;line-height:11px;white-space:nowrap;text-shadow:0 1px 2px #000;box-shadow:0 2px 7px rgba(0,0,0,.4)}.leaflet-marker-icon.building-marker{filter:none!important}`;document.head.appendChild(markerCss);
const BUILDINGS={
 warehouse:{name:'Lager',icon:'📦',cost:800,desc:'+1.000 Lagerkapazität für Material und Produkte.',capacityBonus:1000},
 money:{name:'Geldwäsche',icon:'💵',cost:1000,desc:'+50% Geldproduktion auf diesem Feld.',yield:{money:1.5}},
 club:{name:'Clubhaus',icon:'🥃',cost:1000,desc:'+50% Ruhmproduktion auf diesem Feld.',yield:{reputation:1.5}},
 lab:{name:'Chemielabor',icon:'⚗️',cost:1000,desc:'Verarbeitet automatisch 5 Material zu 1 Produkt pro Minute.',product:true},
 market:{name:'Schwarzmarkt',icon:'🕶️',cost:1000,desc:'+25% Verkaufspreis für Produkte.',sale:1.25},
 watch:{name:'Wachposten',icon:'🛡️',cost:1000,desc:'Schützt dieses und angrenzende Felder (Radius 1) mit +25%.',defense:.25,radius:1},
 hideout:{name:'Gangversteck',icon:'🏰',cost:1000,desc:'Lagert bis zu 10 Truppen und schützt Radius 2 – auch diagonal – mit +75%.',defense:.75,radius:2,capacity:10}
};
const RECRUITMENT={name:'Rekrutierungszentrum',icon:'🏢',cost:1000,desc:'Produziert automatisch Schläger. Start: 1 Schläger alle 120 Sekunden.'};
const ALL_BUILDINGS={...BUILDINGS,recruitment:RECRUITMENT};
const BASE_STORAGE=5000;
const wait=fn=>{let n=0;const t=()=>{if(window.db)return fn();if(++n<100)setTimeout(t,100)};t()};
wait(async()=>{
 const {data}=await window.db.auth.getSession();const user=data?.session?.user;if(!user)return;
 const key='mafivera:v1:save:'+user.id;
 const read=()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch(e){return {}}};
 const write=s=>{try{localStorage.setItem(key,JSON.stringify(s))}catch(e){}};
 const fmt=n=>Number(n||0).toLocaleString('de-DE');
 const toast=t=>{const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2600)};
 const cell=id=>{const m=/^g_(-?\d+)_(-?\d+)$/.exec(id);if(!m)return null;return{id,row:+m[1],col:+m[2]}};
 const storageCapacity=s=>BASE_STORAGE+Object.values(s.built||{}).filter(b=>b?.type==='warehouse').length*1000;
 const storageUsed=s=>Number(s.material||0)+Number(s.product||0);
 const clampStorage=s=>{const cap=storageCapacity(s);if(Number(s.material||0)>cap)s.material=cap;if(Number(s.product||0)>cap)s.product=Math.min(Number(s.product||0),Math.max(0,cap-Number(s.material||0)));return cap};
 const updateStorageUi=s=>{const cap=storageCapacity(s),used=storageUsed(s),pct=Math.min(100,cap?used/cap*100:0);document.querySelectorAll('[data-storage-used]').forEach(e=>e.textContent=fmt(used));document.querySelectorAll('[data-storage-cap]').forEach(e=>e.textContent=fmt(cap));document.querySelectorAll('[data-storage-bar]').forEach(e=>e.style.width=pct+'%');const hud=document.getElementById('storageBadge');if(hud){hud.innerHTML=`📦 Lager <b>${fmt(used)}</b> / ${fmt(cap)}`;hud.title=`Material + Produkte · ${fmt(cap)} maximale Lagerkapazität`}};
 const ensureStorageUi=()=>{const hud=document.querySelector('.hud');if(!hud)return;if(!document.getElementById('storageBadge')){const e=document.createElement('div');e.id='storageBadge';e.className='storage-badge';hud.appendChild(e)}updateStorageUi(read())};
 const protection=id=>{const t=cell(id);if(!t)return[];const s=read(),out=[];Object.entries(s.built||{}).forEach(([bid,b])=>{const d=BUILDINGS[b?.type],c=cell(bid);if(!d?.defense||!c||!(s.fields||{})[bid])return;const delta=Math.max(Math.abs(c.row-t.row),Math.abs(c.col-t.col));if(delta<=d.radius)out.push({id:bid,building:d,type:b.type,bonus:d.defense,distance:delta,troops:b.troops||0})});return out};
 const defense=id=>protection(id).reduce((n,x)=>n+x.bonus,0);
 window.MAFIVERA_BUILDINGS=BUILDINGS;window.MAFIVERA_ALL_BUILDINGS=ALL_BUILDINGS;
 window.MAFIVERA_STORAGE_CAPACITY=()=>storageCapacity(read());window.MAFIVERA_STORAGE_USED=()=>storageUsed(read());window.mtrwDefense=id=>defense(id);
 const buildingLayer=()=>{const map=window.__mtrwLeafletMap||window.mtrwMap;if(!map||!window.L)return null;let layer=window.__mtrwBuildingLayer;if(!layer){layer=L.layerGroup().addTo(map);window.__mtrwBuildingLayer=layer}return layer};
 const renderBuildingGraphics=()=>{const layer=buildingLayer();if(!layer)return;layer.clearLayers();const s=read(),o=s.worldOrigin||s.gps;if(!o)return;Object.entries(s.built||{}).forEach(([id,b])=>{if(!s.fields?.[id])return;const c=cell(id),d=ALL_BUILDINGS[b?.type];if(!c||!d)return;const lat=o.lat+(c.row+.5)*.0018,lng=o.lng+(c.col+.5)*.0025;const marker=L.marker([lat,lng],{interactive:false,zIndexOffset:500,icon:L.divIcon({className:'building-marker',html:`<div class="mtrw-building-pin"><span>${d.icon}</span><b>${d.name}</b></div>`,iconSize:[96,52],iconAnchor:[48,26]})});layer.addLayer(marker)})};
 const setCurrent=id=>{window.__mtrwBuildingCell=id;setTimeout(()=>decorate(id),50)};
 const wrap=()=>{if(typeof window.mtrwClaim!=='function'||window.mtrwClaim.__buildingWrapped)return;const fn=window.mtrwClaim;const w=id=>{setCurrent(id);return fn(id)};w.__buildingWrapped=true;window.mtrwClaim=w};
 const buildingPanel=id=>{
  const s=read(),b=(s.built||{})[id],body=document.getElementById('drawerBody');if(!body)return;window.__mtrwBuildingCell=id;
  if(b){const d=ALL_BUILDINGS[b.type];if(!d)return;body.innerHTML=`<div class="panel-hero">${d.icon} <div><b>${d.name}</b><p>${d.desc}<br>Stufe ${b.level||1}${b.type==='warehouse'?` · +${fmt(d.capacityBonus)} Kapazität`:''}${b.type==='hideout'?` · ${b.troops||0}/${b.capacity||10} Truppen`:''}</p></div></div>${b.type==='warehouse'?`<div class="panel-hint">📦 Gesamtlager: <b>${fmt(storageUsed(s))} / ${fmt(storageCapacity(s))}</b></div>`:''}${b.type==='hideout'?'<button class="panel-action" data-baction="station">🪖 Truppen stationieren</button>':''}<button class="panel-action danger" data-baction="remove">🏚️ Gebäude abreißen · 50% Erstattung</button><button class="panel-action" data-baction="back">← Zurück zum Grundstück</button>`}
  else{body.innerHTML=`<h3>Gebäude errichten</h3><p class="muted">Pro Kachel kann genau <b>ein Gebäude</b> stehen. Bau nur, wenn die benötigten Ressourcen bzw. das Geld vorhanden sind.</p>${Object.entries(ALL_BUILDINGS).map(([k,d])=>`<button class="panel-action" data-build="${k}">${d.icon} <b>${d.name}</b> · ${fmt(d.cost)} $<br><small>${d.desc}</small></button>`).join('')}`}
  body.querySelectorAll('[data-build]').forEach(btn=>btn.onclick=()=>{const type=btn.dataset.build,d=ALL_BUILDINGS[type],st=read();st.built=st.built||{};if(st.built[id])return toast('Auf dieser Kachel steht bereits ein Gebäude.');if(Number(st.money||0)<d.cost)return toast(`Du brauchst ${fmt(d.cost)} $.`);st.money-=d.cost;st.built[id]={type,level:1,troops:0,capacity:d.capacity||0};clampStorage(st);write(st);document.getElementById('money').textContent=fmt(st.money);renderBuildingGraphics();updateStorageUi(st);window.dispatchEvent(new Event('mafivera:buildingChanged'));toast(`${d.icon} ${d.name} gebaut.`);buildingPanel(id)});
  body.querySelectorAll('[data-baction]').forEach(btn=>btn.onclick=()=>{const a=btn.dataset.baction,st=read(),b=st.built?.[id],d=b&&ALL_BUILDINGS[b.type];if(a==='back')return decorate(id);if(!b)return;if(a==='remove'){if(b.type==='hideout'){st.hitmen=(st.hitmen||0)+(b.troops||0);st.stationed=Math.max(0,(st.stationed||0)-(b.troops||0))}st.money=(st.money||0)+Math.floor((d.cost||0)*.5);delete st.built[id];clampStorage(st);write(st);document.getElementById('money').textContent=fmt(st.money);renderBuildingGraphics();updateStorageUi(st);window.dispatchEvent(new Event('mafivera:buildingChanged'));decorate(id);toast(`Gebäude abgerissen · +${fmt(Math.floor(d.cost*.5))} $.`)}if(a==='station'){const free=Math.min(Number(st.hitmen||0),Number(b.capacity||10)-Number(b.troops||0));if(free<=0)return toast('Kein Platz oder keine freien Truppen.');const n=Math.max(1,Math.min(free,Number(prompt(`Wie viele Truppen? (max. ${free})`,'1')||0)));b.troops=(b.troops||0)+n;st.hitmen-=n;st.stationed=(st.stationed||0)+n;write(st);buildingPanel(id);window.dispatchEvent(new Event('mafivera:buildingChanged'));toast(`${n} Truppen im Gangversteck stationiert.`)}});
 };
 const decorate=id=>{const body=document.getElementById('drawerBody');if(!body||!id)return;const s=read(),f=s.fields?.[id];if(!f)return;const b=s.built?.[id],p=Math.round(defense(id)*100);let old=body.querySelector('[data-building-open]');if(!old){old=document.createElement('button');old.className='panel-action';old.dataset.buildingOpen='1';body.appendChild(old)}old.textContent=b?`${ALL_BUILDINGS[b.type]?.icon||'🏗️'} ${ALL_BUILDINGS[b.type]?.name||'Gebäude'} verwalten`:'🏗️ Gebäude auf diesem Feld errichten';old.onclick=()=>buildingPanel(id);let info=body.querySelector('[data-building-info]');if(!info){info=document.createElement('div');info.className='panel-hint';info.dataset.buildingInfo='1';body.appendChild(info)}info.innerHTML=p?`🛡️ <b>Geschützt</b>: +${p}% Verteidigung. Schutzradius wird in alle Richtungen berechnet, <b>diagonal eingeschlossen</b>.`:''};
 const init=()=>{ensureStorageUi();wrap();setTimeout(()=>{wrap();renderBuildingGraphics();updateStorageUi(read())},250);const map=window.__mtrwLeafletMap||window.mtrwMap;if(map){map.on('moveend zoomend',renderBuildingGraphics)}};
 init();
 const economy=()=>{const s=read(),now=Date.now(),mins=Math.max(0,Math.min(60,(now-(s.__buildingTick||now))/60000));if(mins<.016){updateStorageUi(s);return}let money=0,material=0,rep=0,products=0;Object.entries(s.fields||{}).forEach(([id,f])=>{const b=s.built?.[id],d=BUILDINGS[b?.type];(f.props||[]).forEach(p=>{const mult=d?.yield?.[p]||1;if(p==='money')money+=mult*mins;if(p==='material')material+=mult*mins;if(p==='reputation')rep+=mult*mins});if(d?.product)products+=Math.floor((s.material||0)/5*mins)});const cap=storageCapacity(s);s.money=(s.money||0)+Math.floor(money);s.material=Math.min(cap,(s.material||0)+Math.floor(material));if(products>0){const batches=Math.min(products,Math.floor((s.material||0)/5),Math.max(0,cap-(s.product||0)));s.material-=batches*5;s.product=(s.product||0)+batches}s.influence=(s.influence||0)+Math.floor(rep);s.__buildingTick=now;clampStorage(s);write(s);['money','material','product','level'].forEach(i=>{const e=document.getElementById(i);if(e)e.textContent=fmt(s[i])});updateStorageUi(s);renderBuildingGraphics();if(money||material||rep||products)toast(`Gebäudeproduktion: +${Math.floor(money)} $ · +${Math.floor(material)} Material${rep?` · +${Math.floor(rep)} Ruhm`:''}${products?` · +${products} Produkt`:''}`)};
 economy();setInterval(economy,15000);
 window.addEventListener('mafivera:territoryChanged',()=>{setTimeout(()=>{renderBuildingGraphics();updateStorageUi(read())},50)});
});
})();
