/* MTRW Email Authentication v1 */
(()=>{
  if(window.mtrwEmailAuthInstalled)return;
  window.mtrwEmailAuthInstalled=true;
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  async function boot(){
    for(let i=0;i<80&&!window.db;i++)await wait(100);
    const db=window.db,start=document.getElementById('start'),card=start?.querySelector('.card');
    if(!db||!start||!card)return;
    card.innerHTML=`<div class="logo">🕴️ MAFIA</div><div class="sub">THE REAL WORLD</div><h1>Willkommen</h1><p id="emailModeText">Melde dich mit deiner E-Mail-Adresse und deinem Passwort an.</p><input id="emailAuthEmail" type="email" autocomplete="email" placeholder="E-Mail-Adresse"><input id="emailAuthPassword" type="password" autocomplete="current-password" placeholder="Passwort"><input id="emailAuthUsername" autocomplete="username" maxlength="24" placeholder="Username (nur bei Registrierung)" hidden><button class="primary" id="emailAuthButton" type="button">🔐 Anmelden</button><button class="secondary" id="emailRegisterButton" type="button">📝 Neues Konto erstellen</button><button class="secondary" id="emailForgotButton" type="button">🔑 Passwort vergessen</button><div id="emailAuthMessage" class="message" aria-live="polite"></div><div class="foot">Dein Spielstand wird dauerhaft mit deinem Konto verknüpft.</div>`;
    const email=document.getElementById('emailAuthEmail'),pass=document.getElementById('emailAuthPassword'),uname=document.getElementById('emailAuthUsername'),action=document.getElementById('emailAuthButton'),register=document.getElementById('emailRegisterButton'),forgot=document.getElementById('emailForgotButton'),text=document.getElementById('emailModeText'),out=document.getElementById('emailAuthMessage');
    let mode='login';
    const set=(t,err=false)=>{out.textContent=t;out.style.color=err?'#f88':'#d1a72c'};
    const validUser=u=>/^[A-Za-z0-9_.-]{3,24}$/.test(u);
    register.onclick=()=>{if(mode==='login'){mode='register';text.textContent='Erstelle dein Konto. Der Username ist dein Name im Spiel.';uname.hidden=false;action.textContent='🚀 Konto erstellen';register.textContent='↩️ Zur Anmeldung';set('');}else{mode='login';text.textContent='Melde dich mit deiner E-Mail-Adresse und deinem Passwort an.';uname.hidden=true;action.textContent='🔐 Anmelden';register.textContent='📝 Neues Konto erstellen';set('')}};
    action.onclick=async()=>{const em=email.value.trim().toLowerCase(),pw=pass.value,un=uname.value.trim();if(!em||!pw){set('Bitte E-Mail-Adresse und Passwort eingeben.',true);return}if(pw.length<8){set('Das Passwort muss mindestens 8 Zeichen lang sein.',true);return}action.disabled=true;try{if(mode==='register'){if(!validUser(un)){set('Username: 3–24 Zeichen, nur Buchstaben, Zahlen, Punkt, Bindestrich oder Unterstrich.',true);return}const exists=await db.from('profiles').select('id').eq('username',un).maybeSingle();if(exists.error)throw exists.error;if(exists.data){set('Dieser Username ist bereits vergeben.',true);return}set('Konto wird erstellt…');const r=await db.auth.signUp({email:em,password:pw,options:{data:{username:un}}});if(r.error)throw r.error;if(r.data.session){set('Anmeldung erfolgreich. Spiel wird geladen…');setTimeout(()=>location.reload(),250)}else set('Konto erstellt. Bitte bestätige die E-Mail-Adresse. Danach kannst du dich anmelden.')}else{set('Anmeldung wird geprüft…');const r=await db.auth.signInWithPassword({email:em,password:pw});if(r.error)throw r.error;set('Anmeldung erfolgreich. Spiel wird geladen…');setTimeout(()=>location.reload(),250)}}catch(e){const m=String(e?.message||e);if(/invalid login credentials/i.test(m))set('E-Mail oder Passwort ist falsch.',true);else if(/email not confirmed/i.test(m))set('Bitte bestätige zuerst deine E-Mail-Adresse.',true);else if(/already registered/i.test(m))set('Für diese E-Mail existiert bereits ein Konto. Melde dich an.',true);else set(m,true)}finally{action.disabled=false}};
    forgot.onclick=async()=>{const em=email.value.trim().toLowerCase();if(!em){set('Bitte zuerst deine E-Mail-Adresse eingeben.',true);return}forgot.disabled=true;try{const r=await db.auth.resetPasswordForEmail(em,{redirectTo:location.origin+location.pathname});if(r.error)throw r.error;set('E-Mail zum Zurücksetzen des Passworts wurde angefordert.')}catch(e){set(String(e?.message||e),true)}finally{forgot.disabled=false}};
  }
  boot();
})();