/* MAFIVERA V1 — Map-first playable core */
(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const load=src=>new Promise((ok,no)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s)});
const start=async()=>{
 if(!window.db)return setTimeout(start,100); const {data}=await window.db.auth.getSession(); if(!data?.session){location.reload();return;}
 const user=data.session.user,meta=user.user_metadata||{},name=meta.username||user.email?.split('@')[0]||'Spieler',root=document.getElementById('gameRoot');if(!root)return;
 if(!document.getElementById('mafiveraGameCss')){const l=document.createElement('link');l.id='mafiveraGameCss';l.rel='stylesheet';l.href='./game.css?v=4';document.head.appendChild(l)}
 if(!window.L){try{await load('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js')}catch(e){try{await load('https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js')}catch(e2){}}}
 const key='mtrw-v1-'+user.id;let state={money:0,level:1,material:0,product:0,family:null,territories:0,productionUntil:0,log:[]};try{state={...state,...JSON.parse(localStorage.getItem(key)||'{}')}}catch(e){}
 const save=()=>localStorage.setItem(key,JSON.stringify(state));
 let map=null,gpsWatch=null,gpsActive=false,playerMarker=null,accuracyCircle=null;
 root.innerHTML=`<div class="mafivera-game"><header class="hud"><button id="menuBtn" class="icon-btn">☰</button><div class="hud-brand"><b>MAFIVERA</b><span>Die Welt gehört dir</span></div><div class="hud-stats"><span>💰 <b id="money">0</b></span><span>⭐ <b id="level">1</b></span><span>⚡ <b>100</b></span></div></header><main id="worldMap" class="world-map"></main><div class="map-overlay top-left"><div class="location-pill"><span id="gpsIndicator">●</span><span id="gpsText">Standort nicht aktiviert</span></div></div><div class="map-overlay top-right"><button id="locateBtn" class="map-btn">⌖</button></div><div class="map-overlay resource-legend"><span>🟢 Material</span><span>🟣 Produktion</span><span>🟠 Dealer</span></div><section id="drawer" class="drawer hidden"><div class="drawer-head"><div><small>MAFIVERA</small><h2 id="drawerTitle">Menü</h2></div><button id="drawerClose" class="close-btn">×</button></div><div id="drawerBody"></div></section><nav class="bottom-nav"><button class="bottom-btn active" data-panel="map"><span>🗺️</span><small>KARTE</small></button><button class="bottom-btn" data-panel="family"><span>♜</span><small>FAMILIE</small></button><button class="bottom-btn" data-panel="business"><span>⚗</span><small>GESCHÄFT</small></button><button class="bottom-btn" data-panel="social"><span>♧</span><small>SOZIAL</small></button><button class="bottom-btn" data-panel="more"><span>▦</span><small>MEHR</small></button><button class="bottom-btn" data-panel="profile"><span>◉</span><small>PROFIL</small></button></nav><div id="toast" class="toast"></div></div>`;
 const toast=t=>{const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)};
 const refresh=()=>{document.getElementById('money').textContent=state.money.toLocaleString('de-DE');document.getElementById('level').textContent=state.level;save()};
 const log=(event,cat='game',details={})=>{const fn=cat==='player'?window.mtrwPlayerEvent:window.mtrwGameEvent;if(typeof fn==='function')fn(event,details)};
 const drawer=document.getElementById('drawer'),title=document.getElementById('drawerTitle'),body=document.getElementById('drawerBody');
 const action=a=>{
  if(a==='logout'){stopGps();window.db.auth.signOut().finally(()=>location.reload());return}
  if(a==='create-family'){state.family=state.family?state.family:'Neue Familie';state.level++;refresh();render('family');toast('Familie gegründet.');log('Familie gegründet','player');return}
  if(a==='collect'){state.material+=5;refresh();toast('+5 Material gesammelt.');log('Material gesammelt','game',{menge:5});return}
  if(a==='produce'){if(state.productionUntil>Date.now()){toast('Produktion läuft bereits.');return}if(state.material<2){toast('Mindestens 2 Material nötig.');return}state.material-=2;state.productionUntil=Date.now()+15000;refresh();render('business');toast('Produktion gestartet · 15 Sek.');log('Produktion gestartet');setTimeout(()=>{if(state.productionUntil&&Date.now()>=state.productionUntil){state.productionUntil=0;state.product++;state.level=Math.max(1,1+Math.floor(state.product/5));refresh();if(!drawer.classList.contains('hidden'))render('business');toast('Produktion abgeschlossen.');log('Produktion abgeschlossen')}},15100);return}
  if(a==='sell'){if(state.product<1){toast('Keine Ware zum Verkauf.');return}state.product--;state.money+=100;state.level=Math.max(1,1+Math.floor(state.money/500));refresh();render('business');toast('+100 $ verdient.');log('Ware beim Dealer verkauft','game',{wert:100});return}
  if(a==='claim'){state.territories++;state.level++;refresh();render('family');toast('Gebiet übernommen.');log('Gebiet übernommen','player');return}
  if(a==='players'){toast('Spielersuche wird mit dem Online-System verbunden.');return}
  if(a==='friends'){toast('Freundesliste wird als nächstes mit Supabase verbunden.');return}
  if(a==='chat'){toast('Chat-System ist vorbereitet.');return}
  if(a==='missions'){toast('Neue Aufträge werden hier erscheinen.');return}
  if(a==='achievements'){toast('Erfolge werden hier gespeichert.');return}
  if(a==='leaderboard'){toast('Rangliste wird mit dem Online-System verbunden.');return}
  if(a==='settings'){toast('Einstellungen werden vorbereitet.');return}
  if(a==='help'){toast('Klicke auf Kartenmarker, um Orte zu erkunden.');return}
  toast('Bereich geöffnet.');
 };
 const render=panel=>{if(panel==='map'){drawer.classList.add('hidden');return}const family=state.family||'Keine Familie';const running=state.productionUntil>Date.now();const remain=running?Math.ceil((state.productionUntil-Date.now())/1000):0;const content={
 family:`<div class="panel-hero">♜<div><b>${esc(family)}</b><p>Deine Allianz und dein Einfluss.</p></div></div><div class="panel-grid"><div><b>${state.territories}</b><small>Gebiete</small></div><div><b>0</b><small>Mitglieder</small></div><div><b>${state.level}</b><small>Rang</small></div></div><button class="panel-action" data-action="create-family">${state.family?'⚙ Familie verwalten':'＋ Familie gründen'}</button><button class="panel-action" data-action="claim">🏴 Nächstes Gebiet übernehmen</button>`,
 business:`<div class="panel-hero">⚗<div><b>Dein Geschäft</b><p>Abstrakte Spielressource: Material → Produkt → Dealer.</p></div></div><div class="production-card"><div class="business-stats"><span>Material <b>${state.material}</b></span><span>Ware <b>${state.product}</b></span></div><div class="production-progress"><i style="width:${running?55:100}%"></i></div><small>${running?'Produktion läuft · noch '+remain+' Sek.':'Produktion bereit'}</small></div><button class="panel-action" data-action="collect">📦 +5 Material sammeln</button><button class="panel-action" data-action="produce">⚗ 1 Einheit produzieren</button><button class="panel-action" data-action="sell">💵 Beim Dealer verkaufen</button>`,
 social:`<div class="panel-hero">♧<div><b>Sozial</b><p>Spieler, Kontakte und Nachrichten.</p></div></div><button class="panel-action" data-action="players">👥 Spieler in der Nähe</button><button class="panel-action" data-action="friends">🤝 Freunde</button><button class="panel-action" data-action="chat">💬 Nachrichten</button>`,
 more:`<div class="panel-hero">▦<div><b>Mehr</b><p>Weitere Spielsysteme.</p></div></div><button class="panel-action" data-action="missions">🎯 Aufträge</button><button class="panel-action" data-action="achievements">🏆 Erfolge</button><button class="panel-action" data-action="leaderboard">📊 Rangliste</button><button class="panel-action" data-action="settings">⚙ Einstellungen</button><button class="panel-action" data-action="help">❓ Hilfe</button><button class="panel-action danger" data-action="logout">🚪 Abmelden</button>`,
 profile:`<div class="profile-big">◉</div><h3>${esc(name)}</h3><p class="muted">${esc(user.email||'')}</p><div class="profile-list"><div><span>Level</span><b>${state.level}</b></div><div><span>Vermögen</span><b>${state.money.toLocaleString('de-DE')} $</b></div><div><span>Material</span><b>${state.material}</b></div><div><span>Ware</span><b>${state.product}</b></div><div><span>Gebiete</span><b>${state.territories}</b></div><div><span>GPS</span><b>${gpsActive?'Aktiv':'Aus'}</b></div></div><button class="panel-action danger" data-action="logout">Abmelden</button>`};title.textContent={family:'Familie',business:'Geschäft',social:'Sozial',more:'Mehr',profile:'Profil'}[panel]||'Menü';body.innerHTML=content[panel]||'';drawer.classList.remove('hidden');body.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));};
 document.querySelectorAll('.bottom-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.panel);log('Menü geöffnet',{bereich:b.dataset.panel})});
 document.getElementById('menuBtn').onclick=()=>render('more');document.getElementById('drawerClose').onclick=()=>drawer.classList.add('hidden');drawer.onclick=e=>{if(e.target===drawer)drawer.classList.add('hidden')};
 const setGps=(t,a=false)=>{document.getElementById('gpsText').textContent=t;document.getElementById('gpsIndicator').classList.toggle('active',a)};
 const stopGps=()=>{if(gpsWatch!==null){navigator.geolocation.clearWatch(gpsWatch);gpsWatch=null}gpsActive=false;setGps('Standort pausiert');log('GPS-Tracking gestoppt')};
 const startGps=()=>{if(!navigator.geolocation){toast('Standort wird nicht unterstützt.');return}if(!window.isSecureContext){toast('GPS benötigt HTTPS.');return}if(gpsActive)return;setGps('Standort wird ermittelt…');gpsWatch=navigator.geolocation.watchPosition(p=>{gpsActive=true;setGps('GPS aktiv · ± '+Math.round(p.coords.accuracy)+' m',true);const ll=[p.coords.latitude,p.coords.longitude];if(map){if(!playerMarker){playerMarker=L.marker(ll).addTo(map).bindPopup('📍 Deine Position');accuracyCircle=L.circle(ll,{radius:p.coords.accuracy,color:'#d6ad2d',fillOpacity:.06,weight:1}).addTo(map)}else{playerMarker.setLatLng(ll);accuracyCircle.setLatLng(ll).setRadius(p.coords.accuracy)}}},e=>{gpsActive=false;setGps(e.code===1?'Standortzugriff verweigert':'Standort nicht verfügbar');toast('Standort konnte nicht ermittelt werden.');log('GPS-Fehler')},{enableHighAccuracy:true,maximumAge:5000,timeout:15000});log('Standortzugriff gestartet','player')};
 document.getElementById('locateBtn').onclick=()=>{if(!gpsActive){startGps();return}if(playerMarker)map.setView(playerMarker.getLatLng(),16)};
 const addMarker=(lat,lng,type,label,click)=>{const colors={material:'#4ade80',production:'#a78bfa',dealer:'#fb923c'},c=colors[type];const icon=L.divIcon({className:'mtrw-marker',html:`<span style="border-color:${c};color:${c}">●</span>`,iconSize:[30,30],iconAnchor:[15,15]});L.marker([lat,lng],{icon}).addTo(map).bindTooltip(label,{direction:'top'}).on('click',click)};
 if(window.L){map=L.map('worldMap',{zoomControl:false,attributionControl:true}).setView([51.1657,10.4515],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);[[51.21,10.37,'material','Materialstelle'],[51.06,10.55,'material','Materialstelle'],[50.98,10.74,'production','Produktionsstandort'],[51.14,11,'dealer','Dealer'],[51.25,10.75,'production','Produktionsstandort'],[50.92,10.6,'dealer','Dealer']].forEach(m=>addMarker(...m,()=>{if(m[2]==='material'){render('business');toast('Materialstelle geöffnet. Nutze +5 Material.')}else if(m[2]==='production'){render('business');toast('Produktionsstandort geöffnet.')}else{render('business');toast('Dealer geöffnet. Verkauf ist verfügbar.')}}));setTimeout(()=>map.invalidateSize(),200)}else document.getElementById('worldMap').innerHTML='<div class="map-fallback">🗺️<b>Karte konnte nicht geladen werden</b><span>Bitte Seite neu laden.</span></div>';
 window.addEventListener('beforeunload',stopGps);refresh();log('Game geladen','game',{username:name});
};start();
})();