/* MAFIVERA V1 — Map, GPS, Gebiete & Wirtschaft */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const load=src=>new Promise((r,j)=>{const s=document.createElement('script');s.src=src;s.onload=r;s.onerror=j;document.head.appendChild(s)});
async function start(){
 if(!window.db)return setTimeout(start,100);const {data}=await window.db.auth.getSession();if(!data?.session){location.reload();return}
 const user=data.session.user,meta=user.user_metadata||{},name=meta.username||user.email?.split('@')[0]||'Spieler',root=document.getElementById('gameRoot');if(!root)return;
 const css=document.createElement('link');css.rel='stylesheet';css.href='./game.css?v=11';document.head.appendChild(css);
 if(!window.L){try{await load('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js')}catch(e){try{await load('https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js')}catch(e2){}}}
 const saveKey='mafivera:v1:save:'+user.id,defaults={money:0,level:1,energy:100,material:0,product:0,territories:0,influence:0,family:null,labLevel:0,production:null,lastSaved:null,fields:{},built:{},dealer:null,gps:null};let state={...defaults};try{const raw=localStorage.getItem(saveKey);if(raw){const p=JSON.parse(raw);state={...defaults,...p,fields:{...defaults.fields,...(p.fields||{})},built:{...defaults.built,...(p.built||{})}}}}catch(e){}
 const save=()=>{state.lastSaved=new Date().toISOString();try{localStorage.setItem(saveKey,JSON.stringify(state))}catch(e){}};const fmt=n=>Number(n||0).toLocaleString('de-DE');const levelUp=()=>{const before=state.level,target=250+before*150;state.level=Math.max(1,1+Math.floor((state.money+state.product*20+state.material+state.influence*10)/target));return state.level>before};const productionDuration=30000;const settleProduction=()=>{const p=state.production;if(!p?.running||Date.now()-p.startedAt<p.durationMs)return false;state.material=Math.max(0,state.material-p.input);state.product+=p.output;state.production=null;levelUp();save();return true};const hud=()=>{settleProduction();[['money',state.money],['material',state.material],['product',state.product],['level',state.level]].forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=fmt(v)})};
 let map=null,playerMarker=null,accuracyCircle=null,gpsWatch=null,gps=null,gpsCentered=false,territories=[],resources=[],eventFields=[];
 const baseTerritories=[['t1','Nordwest',-0.0042,-0.0048,'material','money'],['t2','Nord',-0.0042,0,'reputation','material'],['t3','Nordost',-0.0042,0.0048,'money','reputation'],['t4','West',0,-0.0048,'material','reputation'],['t5','Mitte',0,0,'money','material'],['t6','Ost',0,0.0048,'reputation','money'],['t7','Südwest',0.0042,-0.0048,'money','material'],['t8','Süd',0.0042,0,'material','money'],['t9','Südost',0.0042,0.0048,'reputation','material']];
 function markerIcon(type){const icon=type==='player'?'●':type==='resource'?'▣':type==='territory'?'◆':type==='event'?'✦':'$';return L.divIcon({className:'',html:`<div class="map-marker ${type}">${icon}</div>`,iconSize:[34,34],iconAnchor:[17,17]})}
 function propLabel(p){return p==='reputation'?'Ruf':p==='material'?'Material':'Geld'}
 function makeWorld(lat,lng){territories=baseTerritories.map(x=>({id:x[0],name:x[1],lat:lat+x[2],lng:lng+x[3],props:[x[4],x[5]]}));resources=[{id:'r1',name:'Materialfeld Nord',lat:lat-0.003,lng:lng-0.0028,base:8,territoryId:'t1'},{id:'r2',name:'Materialfeld Ost',lat:lat,lng:lng+0.003,base:7,territoryId:'t6'},{id:'r3',name:'Materialfeld Süd',lat:lat+0.003,lng:lng+0.0015,base:9,territoryId:'t8'}]}
 root.innerHTML=`<div class="mafivera-game"><header class="hud"><button id="menuBtn" class="icon-btn">☰</button><div class="hud-brand"><b>MAFIVERA</b><span>Die Welt gehört dir</span></div><div class="hud-stats"><span>💰 <b id="money">0</b></span><span>📦 <b id="material">0</b></span><span>⚗ <b id="product">0</b></span><span>⭐ <b id="level">1</b></span></div></header><main id="worldMap" class="world-map"></main><div class="map-overlay top-left"><div class="location-pill"><span id="gpsIndicator">●</span><span id="gpsText">Standort wird gesucht…</span></div></div><div class="map-overlay top-right"><button id="locateBtn" class="map-btn">⌖</button></div><section id="drawer" class="drawer hidden"><div class="drawer-head"><div><small>MAFIVERA</small><h2 id="drawerTitle">Menü</h2></div><button id="drawerClose" class="close-btn">×</button></div><div id="drawerBody"></div></section><nav class="bottom-nav"><button class="bottom-btn active" data-panel="map"><span>🗺️</span><small>KARTE</small></button><button class="bottom-btn" data-panel="family"><span>♜</span><small>FAMILIE</small></button><button class="bottom-btn" data-panel="business"><span>⚗</span><small>GESCHÄFT</small></button><button class="bottom-btn" data-panel="social"><span>♧</span><small>SOZIAL</small></button><button class="bottom-btn" data-panel="more"><span>▦</span><small>MEHR</small></button><button class="bottom-btn" data-panel="profile"><span>◉</span><small>PROFIL</small></button></nav><div id="toast" class="toast"></div></div>`;
 const toast=t=>{const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2600)};const drawer=document.getElementById('drawer'),title=document.getElementById('drawerTitle'),body=document.getElementById('drawerBody');const setGps=(text,on=false)=>{const t=document.getElementById('gpsText'),i=document.getElementById('gpsIndicator');if(t)t.textContent=text;if(i)i.classList.toggle('active',on)};
 function tileIcon(t){const f=state.fields[t.id],b=state.built[t.id];if(b)return '🏭';if(f)return '⌂';if(t.props.includes('material'))return '📦';return '◆'}
 function tilePopup(t){const owned=!!state.fields[t.id],cost=250+state.territories*150;return `<b>◆ ${esc(t.name)}</b><br>${owned?'Dein beanspruchtes Grundstück':'Freies Grundstück'}<br>Eigenschaften: ${t.props.map(propLabel).join(' + ')}${t.props.includes('material')?'<br>📦 Material wird hier automatisch erzeugt.':''}<br><button onclick="window.mtrwClaim&&window.mtrwClaim('${t.id}')">${owned?'Gebiet öffnen':'Gebiet beanspruchen · '+fmt(cost)+' $'}</button>`}
 function renderMarkers(){if(!map)return;map.eachLayer(layer=>{if(layer._mafivera)map.removeLayer(layer)});const add=m=>{m._mafivera=true;m.addTo(map)};const dh=.00415,dw=.00475;
  territories.forEach(t=>{const owned=!!state.fields[t.id],b=L.rectangle([[t.lat-dh/2,t.lng-dw/2],[t.lat+dh/2,t.lng+dw/2]],{color:owned?'#58a6ff':'#637080',weight:owned?3:1,fillColor:owned?'#58a6ff':'#101820',fillOpacity:owned?.22:.10,interactive:true});b._mafivera=true;b.bindPopup(tilePopup(t));b.on('click',()=>open('territory',t));b.addTo(map);const label=L.marker([t.lat,t.lng],{icon:L.divIcon({className:'',html:`<div class="territory-tile-label"><span class="territory-building">${tileIcon(t)}</span>${owned?'<em>DEIN GEBIET</em>':''}${t.props.includes('material')?'<small>📦</small>':''}</div>`,iconSize:[70,70],iconAnchor:[35,35]}),interactive:false});add(label)});
  resources.forEach(r=>{const m=L.marker([r.lat,r.lng],{icon:markerIcon('resource')});m.bindPopup(`<b>▣ ${esc(r.name)}</b><br>${r.base} Material pro Zyklus<br>${state.fields[r.territoryId]?'Dieses Materialfeld produziert automatisch für dich.':'Beanspruche das zugehörige Gebiet, um die Produktion zu aktivieren.'}`);add(m)});
  eventFields.forEach(e=>{if(e.expires>Date.now()){const m=L.marker([e.lat,e.lng],{icon:markerIcon('event')});m.bindPopup(`<b>✦ Materiallieferung</b><br>${e.amount} Material verfügbar<br>Verschwindet in ${Math.ceil((e.expires-Date.now())/60000)} Min.<br><button onclick="window.mtrwCollectEvent&&window.mtrwCollectEvent('${e.id}')">Material einsammeln</button>`);add(m)}});
  if(state.dealer?.expires>Date.now()){const d=state.dealer,m=L.marker([d.lat,d.lng],{icon:markerIcon('dealer')});m.bindPopup(`<b>💵 Dealer</b><br>${d.offer} Drogen · ${d.price} $<br><button onclick="window.mtrwOpenDealer&&window.mtrwOpenDealer()">Dealer öffnen</button>`);add(m)}
  if(playerMarker){playerMarker._mafivera=true;playerMarker.addTo(map);if(accuracyCircle){accuracyCircle._mafivera=true;accuracyCircle.addTo(map)}}}
 function claim(id){const t=territories.find(x=>x.id===id);if(!t)return;if(state.fields[id]){open('territory',t);return}const cost=250+state.territories*150;if(state.money<cost){toast(`Beanspruchen kostet ${fmt(cost)} $.`);return}state.money-=cost;state.territories++;state.fields[id]={claimedAt:Date.now(),props:t.props,materialBank:0,lastTick:Date.now(),rate:t.props.includes('material')?5:0};state.influence+=t.props.includes('reputation')?10:4;save();hud();renderMarkers();toast(`◆ ${t.name} beansprucht`);window.mtrwPlayerEvent?.('Gebiet beansprucht',{gebiet:t.name});open('territory',t)}window.mtrwClaim=claim;
 function collectTerritory(t){const f=state.fields[t.id];if(!f||!f.props?.includes('material'))return;const now=Date.now(),elapsed=Math.floor((now-(f.lastTick||now))/60000);if(elapsed>0){const gain=elapsed*(f.rate||5)*((1+state.labLevel*.25));f.materialBank=(f.materialBank||0)+Math.floor(gain);f.lastTick+=elapsed*60000;save()}const amount=f.materialBank||0;if(amount){state.material+=amount;f.materialBank=0;save();hud();toast(`+${fmt(amount)} Material aus ${t.name}`)}}
 function settleFields(){territories.forEach(t=>{if(state.fields[t.id])collectTerritory(t)})}
 function buildLab(t){if(!state.fields[t.id])return;if(state.built[t.id]){toast('Auf diesem Gebiet steht bereits ein Labor.');return}const cost=800;if(state.money<cost){toast(`Laborbau kostet ${fmt(cost)} $.`);return}state.money-=cost;state.built[t.id]={type:'lab',level:1};state.labLevel++;save();hud();toast(`🏭 Labor auf ${t.name} gebaut`);renderMarkers();open('territory',t)}
 function open(panel,data=null){settleFields();if(panel==='map'){drawer.classList.add('hidden');return}let t='',c='';if(panel==='territory'){const f=state.fields[data.id],owned=!!f;t='Gebiet';c=`<div class="panel-hero">◆<div><b>${esc(data.name)}</b><p>${owned?'In deinem Besitz':'Beanspruchbar'} · ${data.props.map(propLabel).join(' + ')}</p></div></div><div class="econ-grid"><div><span>Ruf</span><b>${data.props.includes('reputation')?'+10':'—'}</b></div><div><span>Material</span><b>${data.props.includes('material')?'Automatisch':'—'}</b></div><div><span>Geld</span><b>${data.props.includes('money')?'Einnahmen':'—'}</b></div><div><span>Status</span><b>${owned?'BEANSPRUCHT':'FREI'}</b></div></div>${owned?`<button class="panel-action" data-a="lab">🏭 ${state.built[data.id]?'Labor vorhanden':'Labor bauen · 800 $'}</button>`:`<button class="panel-action" data-a="claim">◆ Gebiet beanspruchen · ${fmt(250+state.territories*150)} $</button>`}<p class="panel-hint">📦 Materialgebiete produzieren automatisch. Es gibt keinen Sammelknopf für die normale Produktion.</p>`}
 else if(panel==='family'){t='Familie';c=`<div class="panel-hero">♜<div><b>${state.family?esc(state.family):'Noch keine Familie'}</b><p>Allianz, Gebiete und Einfluss.</p></div></div><button class="panel-action" data-a="family">+ Familie gründen</button><div class="panel-grid"><div><b>${state.territories}</b><small>Gebiete</small></div><div><b>${state.influence}</b><small>Ruf</small></div></div>`}
 else if(panel==='business'){const p=state.production?.running,rem=p?Math.max(0,p.durationMs-(Date.now()-p.startedAt)):0;t='Geschäft';c=`<div class="econ-grid"><div><span>Geld</span><b>${fmt(state.money)} $</b></div><div><span>Material</span><b>${fmt(state.material)}</b></div><div><span>Drogen</span><b>${fmt(state.product)}</b></div><div><span>Labore</span><b>${state.labLevel}</b></div></div><div class="production-card"><div><span>Produktion</span><b>${p?'Läuft':'Bereit'}</b></div><div class="production-progress"><i style="width:${p?Math.min(100,(Date.now()-p.startedAt)/p.durationMs*100):0}%"></i></div><small>${p?`Fertig in ${Math.ceil(rem/1000)}s`:'5 Material → 1 Droge · 30 Sekunden'}</small></div><button class="panel-action" data-a="produce">⚗ ${p?'Produktion prüfen':'Drogen produzieren'}</button><p class="panel-hint">Material entsteht automatisch auf deinen beanspruchten Materialgebieten.</p></div>`}
 else if(panel==='social'){t='Sozial';c='<div class="panel-hero">👥<div><b>Sozial</b><p>Spieler, Kontakte und Nachrichten.</p></div></div><button class="panel-action">👤 Freunde</button><button class="panel-action">💬 Nachrichten</button><button class="panel-action">🤝 Anfragen</button>'}
 else if(panel==='more'){t='Mehr';c='<div class="panel-hero">▦<div><b>Mehr</b><p>Weitere Spielbereiche.</p></div></div><button class="panel-action">🎯 Aufträge</button><button class="panel-action">🏆 Erfolge</button><button class="panel-action">⚙ Einstellungen</button>'}
 else if(panel==='profile'){t='Profil';c=`<div class="profile-big">👤</div><h3>${esc(name)}</h3><p class="muted">${esc(user.email||'')}</p><div class="profile-list"><div><span>Level</span><b>${state.level}</b></div><div><span>Vermögen</span><b>${fmt(state.money)} $</b></div><div><span>Material</span><b>${fmt(state.material)}</b></div><div><span>Drogen</span><b>${fmt(state.product)}</b></div><div><span>Gebiete</span><b>${state.territories}</b></div><div><span>Labore</span><b>${state.labLevel}</b></div></div><button class="panel-action danger" data-a="logout">Abmelden</button>`}
 else if(panel==='menu'){t='Menü';c='<button class="panel-action" data-a="gps">📍 Standort aktivieren</button><button class="panel-action">⚙ Einstellungen</button><button class="panel-action">❓ Hilfe</button><button class="panel-action danger" data-a="logout">🚪 Abmelden</button>'}
 else if(panel==='dealer'){t='Dealer';const d=state.dealer;c=d?`<div class="panel-hero">💵<div><b>Dealer</b><p>Nur für kurze Zeit auf der Karte.</p></div></div><div class="econ-grid"><div><span>Deine Drogen</span><b>${state.product}</b></div><div><span>Angebot</span><b>${d.offer}</b></div><div><span>Preis</span><b>${d.price} $</b></div><div><span>Verbleibend</span><b>${Math.ceil(Math.max(0,d.expires-Date.now())/60000)} Min.</b></div></div><button class="panel-action" data-a="sell">💵 Drogen verkaufen</button>`:'<p>Kein Dealer aktiv.</p>'}
 title.textContent=t;body.innerHTML=c;drawer.classList.remove('hidden');body.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(a==='logout'){save();if(gpsWatch!==null)navigator.geolocation?.clearWatch(gpsWatch);window.db.auth.signOut().finally(()=>location.reload());return}if(a==='gps'){startGps(true);drawer.classList.add('hidden');return}if(a==='family'){if(!state.family){state.family=name+'s Familie';state.influence=10;save();hud();open('family');toast('Familie gegründet.')}return}if(a==='claim'){claim(data.id);return}if(a==='lab'){buildLab(data);return}if(a==='produce'){settleProduction();if(state.production){open('business');toast('Produktion läuft bereits.');return}if(state.material<5){toast('Mindestens 5 Material benötigt.');return}state.production={running:true,startedAt:Date.now(),durationMs:productionDuration,input:5,output:1};save();open('business');toast('Produktion gestartet.');return}if(a==='sell'){sellDealer();return}})};
 window.mtrwOpenDealer=()=>open('dealer');function collectEvent(id){const e=eventFields.find(x=>x.id===id);if(!e||e.expires<=Date.now()){toast('Das Eventfeld ist bereits verschwunden.');return}state.material+=e.amount;eventFields=eventFields.filter(x=>x.id!==id);save();hud();renderMarkers();toast(`✦ +${fmt(e.amount)} Material eingesammelt`);window.mtrwGameEvent?.('Materiallieferung eingesammelt',{menge:e.amount})}window.mtrwCollectEvent=collectEvent;
 function spawnEvent(){if(!gps||!map)return;eventFields=eventFields.filter(x=>x.expires>Date.now());const a=Math.random()*Math.PI*2,d=.0015+Math.random()*.006,e={id:'ev'+Date.now(),lat:gps.lat+Math.cos(a)*d,lng:gps.lng+Math.sin(a)*d,amount:Math.floor(8+Math.random()*18),expires:Date.now()+5*60000};eventFields.push(e);renderMarkers();toast('✦ Materiallieferung in deiner Nähe erschienen');window.mtrwGameEvent?.('Materiallieferung erschienen',{dauerMinuten:5})}
 function spawnDealer(){if(!gps||!map)return;const a=Math.random()*Math.PI*2,d=.003+Math.random()*.012;state.dealer={lat:gps.lat+Math.cos(a)*d,lng:gps.lng+Math.sin(a)*d,offer:Math.floor(3+Math.random()*18),price:Math.floor(80+Math.random()*121),expires:Date.now()+10*60000};save();renderMarkers();toast('💵 Dealer in deiner Nähe erschienen');window.mtrwGameEvent?.('Dealer erschienen',{angebot:state.dealer.offer,preis:state.dealer.price})}
 function sellDealer(){const d=state.dealer;if(!d||d.expires<=Date.now()){state.dealer=null;renderMarkers();toast('Der Dealer ist verschwunden.');return}if(state.product<=0){toast('Keine Drogen zum Verkauf.');return}const qty=Math.min(state.product,d.offer),earned=qty*d.price;state.product-=qty;state.money+=earned;state.dealer=null;const up=levelUp();save();hud();renderMarkers();toast(`+${fmt(earned)} $ verdient`);if(up)window.mtrwPlayerEvent?.('Level aufgestiegen',{level:state.level});open('business')}
 function startGps(manual=false){if(!navigator.geolocation||!window.isSecureContext){setGps('GPS benötigt HTTPS');toast('Standortzugriff benötigt HTTPS.');return}if(gpsWatch!==null)return;setGps('Standort wird ermittelt…');gpsWatch=navigator.geolocation.watchPosition(p=>{gps={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};state.gps={...gps,updatedAt:Date.now()};setGps('GPS aktiv · ± '+Math.round(p.coords.accuracy)+' m',true);if(map){if(!playerMarker){playerMarker=L.marker([gps.lat,gps.lng],{icon:markerIcon('player')}).bindPopup('📍 Deine Position');playerMarker.addTo(map);accuracyCircle=L.circle([gps.lat,gps.lng],{radius:gps.accuracy,color:'#d6ad2d',fillOpacity:.06}).addTo(map)}else{playerMarker.setLatLng([gps.lat,gps.lng]);accuracyCircle.setLatLng([gps.lat,gps.lng]).setRadius(gps.accuracy)}if(!gpsCentered||manual){gpsCentered=true;map.setView([gps.lat,gps.lng],16);makeWorld(gps.lat,gps.lng);renderMarkers()}}save()},e=>{setGps(e.code===1?'Standortzugriff verweigert':'Standort nicht verfügbar');if(e.code===1)toast('Bitte Standortzugriff für diese Seite erlauben.');else toast('GPS konnte nicht ermittelt werden.')},{enableHighAccuracy:true,maximumAge:3000,timeout:15000})}
 document.getElementById('locateBtn').onclick=()=>{if(!gps){startGps(true);return}gpsCentered=true;map?.setView([gps.lat,gps.lng],16)};document.getElementById('menuBtn').onclick=()=>open('menu');document.getElementById('drawerClose').onclick=()=>drawer.classList.add('hidden');drawer.onclick=e=>{if(e.target===drawer)drawer.classList.add('hidden')};document.querySelectorAll('.bottom-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');open(b.dataset.panel);window.mtrwGameEvent?.('Menü geöffnet',{bereich:b.dataset.panel})});
 if(window.L){map=L.map('worldMap',{zoomControl:false,preferCanvas:true}).setView([51.1657,10.4515],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);const fallback=[51.1657,10.4515];if(state.gps){gps=state.gps;makeWorld(gps.lat,gps.lng)}else makeWorld(fallback[0],fallback[1]);renderMarkers();setTimeout(()=>map.invalidateSize(),400)}
 hud();settleFields();save();startGps();setInterval(()=>{settleFields();if(state.production)hud();eventFields=eventFields.filter(x=>x.expires>Date.now());if(state.dealer&&state.dealer.expires<=Date.now()){state.dealer=null;toast('💵 Der Dealer ist verschwunden.')}renderMarkers();save()},15000);setInterval(()=>{if(gps&&!state.dealer)spawnDealer()},180000);setInterval(()=>{if(gps&&Math.random()<.6)spawnEvent()},120000);window.addEventListener('beforeunload',save);window.mtrwGameEvent?.('Game geladen',{username:name,saveLoaded:true});}
start();})();