/* MAFIVERA — stable heist service (no map render loop) */
(()=>{'use strict';
if(window.MAFIVERA_HEIST_SYSTEM)return;window.MAFIVERA_HEIST_SYSTEM=true;
const KEY='mafivera:v1:save:',getKey=()=>Object.keys(localStorage).find(k=>k.startsWith(KEY)),read=()=>{try{const k=getKey();return k?JSON.parse(localStorage.getItem(k)||'{}'):{} }catch(e){return{}}},write=s=>{const k=getKey();if(k)try{localStorage.setItem(k,JSON.stringify(s))}catch(e){}};
const toast=t=>{const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._heistToast);e._heistToast=setTimeout(()=>e.classList.remove('show'),2800)};
const DURATION=30*60*1000,COOLDOWN=60*60*1000;
const threatType=(r,c)=>{const n=Math.abs(r*19+c*23)%9;return n===0?'Bank':n<3?'Geschäft':'Schwarzmarkt'};
const isThreat=(r,c)=>Math.abs(r*19+c*23)%9<3;
const name=(r,c)=>`Sektor ${r>=0?'N':'S'}${Math.abs(r)}-${c>=0?'O':'W'}${Math.abs(c)}`;
const ensure=()=>{const s=read();s.heists=Array.isArray(s.heists)?s.heists:[];s.threatFields=Array.isArray(s.threatFields)?s.threatFields:[];if(!s.worldOrigin)return s;const center=window.mtrwLiveGps||s.gps||s.worldOrigin,gl=.0018,gw=.0025,cr=Math.floor((center.lat-s.worldOrigin.lat)/gl),cc=Math.floor((center.lng-s.worldOrigin.lng)/gw),known=new Set(s.threatFields.map(x=>x.cellId));for(let r=cr-5;r<=cr+5;r++)for(let c=cc-5;c<=cc+5;c++)if(isThreat(r,c)){const id=`g_${r}_${c}`;if(!s.fields?.[id]&&!known.has(id)){s.threatFields.push({cellId:id,row:r,col:c,name:name(r,c),typeLabel:threatType(r,c)});known.add(id)}}write(s);return s};
const cooldown=id=>{const s=read(),h=s.heists.filter(x=>x.cellId===id&&x.status==='resolved').sort((a,b)=>(b.resolvedAt||0)-(a.resolvedAt||0))[0];return Number(h?.cooldownUntil||((h?.resolvedAt||0)+COOLDOWN))};
const start=cellId=>{const s=ensure(),t=s.threatFields.find(x=>x.cellId===cellId),now=Date.now();if(!t)return toast('Dieses Feld ist kein Heist-Ziel.');if(s.heists.some(h=>h.cellId===cellId&&h.status==='running'))return toast('Dieser Heist läuft bereits.');if(cooldown(cellId)>now)return toast('Dieses Ziel befindet sich noch im Cooldown.');if(Number(s.hitmen||0)<1)return toast('Keine Schläger verfügbar.');s.hitmen=Math.max(0,Number(s.hitmen||0)-1);s.heists.push({id:'h_'+now+'_'+Math.random().toString(36).slice(2,8),cellId,name:t.name,typeLabel:t.typeLabel,hitmen:1,status:'running',startedAt:now,endsAt:now+DURATION});write(s);toast('🔫 1 Schläger entsendet · 30 Minuten.');window.dispatchEvent(new Event('mafivera:worldRefresh'))};
const resolve=()=>{const s=ensure(),now=Date.now();let changed=false;for(const h of s.heists){if(h.status!=='running'||now<h.endsAt)continue;const success=Math.random()<.5;h.status='resolved';h.resolvedAt=now;h.cooldownUntil=now+COOLDOWN;h.success=success;h.reward=success?Math.floor(50000+Math.random()*50001):0;s.hitmen=Number(s.hitmen||0)+Number(h.hitmen||1);if(success)s.money=Number(s.money||0)+h.reward;changed=true}if(changed){write(s);toast('⏱️ Ein Heist wurde abgeschlossen.');window.dispatchEvent(new Event('mafivera:worldRefresh'))}};
window.mtrwStartHeist=start;window.MAFIVERA_HEIST={ensure,resolve,cooldown,start,read};
setTimeout(resolve,1500);setInterval(resolve,30000);
})();