/* MAFIVERA V1 — Ziel-UI / Tactical Map HUD */
(()=>{'use strict';
if(window.mtrwHudV1Installed)return;
window.mtrwHudV1Installed=true;
const css=document.createElement('style');
css.textContent=`
.hud{height:82px!important;align-items:center!important;padding:12px 28px!important;gap:18px!important;background:linear-gradient(180deg,rgba(3,7,11,.98),rgba(3,7,11,.78),transparent)!important}
.hud .icon-btn{width:58px!important;height:58px!important;border-radius:50%!important;border:1px solid #31404f!important;background:rgba(7,13,20,.9)!important;box-shadow:0 0 22px rgba(0,0,0,.35)!important;font-size:25px!important}
.hud-brand{flex:0 0 270px!important}.hud-brand b{font-size:22px!important;letter-spacing:3px!important}.hud-brand span{font-size:11px!important;letter-spacing:1.5px!important;color:#8b96a5!important}
.hud-stats{flex:1!important;justify-content:flex-end!important;gap:0!important;height:58px!important}
.hud-stats .hud-stat{position:relative!important;min-width:130px!important;height:58px!important;padding:7px 15px!important;border:0!important;border-left:1px solid rgba(120,145,170,.18)!important;border-radius:0!important;background:transparent!important;text-align:left!important;display:flex!important;flex-direction:column!important;align-items:flex-start!important;justify-content:center!important;gap:2px!important;backdrop-filter:none!important}
.hud-stats .hud-stat small{font-size:11px!important;letter-spacing:1px!important;font-weight:800!important;color:#778394!important;line-height:1!important}
.hud-stats .hud-stat b{font-size:20px!important;line-height:1.05!important;margin:0!important;color:#e8eef5!important;font-weight:800!important}
.hud-stats .hud-money b{color:#ffc72e!important}.hud-stats .hud-material b{color:#39e9b1!important}.hud-stats .hud-drugs b{color:#d7b0ff!important}.hud-stats .hud-recruit b{color:#e8eef5!important}.hud-stats .hud-tiles b{color:#ff6335!important}.hud-stats .hud-level b{color:#ffd54a!important}
.mtrw-level-wrap{width:108px;height:6px;margin-top:3px;border-radius:99px;background:#252c35;overflow:hidden}.mtrw-level-wrap i{display:block;height:100%;width:0;background:#ffd05a;border-radius:99px;box-shadow:0 0 8px #ffd05a}
.mtrw-map-legend{position:absolute;z-index:18;left:18px;top:126px;width:205px;padding:14px 14px 12px;border:1px solid rgba(130,160,190,.35);border-radius:12px;background:rgba(5,10,16,.83);box-shadow:0 10px 35px #0009;backdrop-filter:blur(14px);font-size:12px;color:#9ca8b7}
.mtrw-map-legend h4{margin:0 0 11px;color:#e9eef5;font-size:12px;letter-spacing:.8px;text-transform:uppercase}.mtrw-map-legend div{display:flex;align-items:center;gap:9px;margin:8px 0}.mtrw-map-legend i{display:block;width:24px;height:14px;border-radius:2px;background:transparent;border:2px solid}.mtrw-map-legend .own{border-color:#1687ff;background:#1687ff55}.mtrw-map-legend .ally{border-color:#27d7a0;background:#27d7a055}.mtrw-map-legend .enemy{border-color:#a44cff;background:#a44cff33}.mtrw-map-legend .heist{border-color:#ff334f;background:#ff334f44}.mtrw-map-legend .industry{border-color:#aeb8c5;background:#aeb8c522}.mtrw-map-legend .city{border-color:#3e4855;background:#202a3555}
.mtrw-map-tools{position:absolute;z-index:19;right:22px;top:108px;display:flex;flex-direction:column;gap:10px}.mtrw-map-tool{position:relative;width:52px;height:52px;border-radius:50%;border:1px solid #32404d;background:rgba(5,10,16,.88);color:#dce5ee;box-shadow:0 8px 28px #0008;backdrop-filter:blur(12px);font-size:22px;cursor:pointer}.mtrw-map-tool:hover{border-color:#60758b}.mtrw-map-tool.alert{border-color:#ff4d27;color:#ff623d}.mtrw-alert-count{position:absolute;right:-7px;top:-6px;min-width:28px;height:28px;padding:0 6px;border-radius:99px;background:#ff5b2e;color:#fff;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:900}
.mtrw-map-tools .mtrw-tooltip{position:absolute;right:64px;top:50%;transform:translateY(-50%);white-space:nowrap;padding:7px 9px;border-radius:8px;background:#0b1118;color:#aeb9c6;border:1px solid #263443;font-size:9px;opacity:0;pointer-events:none;transition:.15s}.mtrw-map-tool:hover .mtrw-tooltip{opacity:1}
.bottom-nav{height:88px!important;left:15px!important;right:15px!important;bottom:max(12px,env(safe-area-inset-bottom))!important;border-radius:27px!important;background:rgba(3,8,13,.95)!important;border-color:rgba(120,145,170,.28)!important;box-shadow:0 18px 60px #000d,inset 0 1px rgba(255,255,255,.04)!important;padding:7px!important;gap:4px!important}
.bottom-btn{border-radius:21px!important;color:#7f8997!important}.bottom-btn span{font-size:25px!important}.bottom-btn small{font-size:10px!important;letter-spacing:1.2px!important}.bottom-btn.active{background:rgba(41,55,72,.35)!important;color:#ffd05a!important;box-shadow:inset 0 0 28px rgba(255,205,80,.03)!important}
.leaflet-container{filter:brightness(.62) saturate(.7) contrast(1.08)!important;background:#050a0f!important}.leaflet-tile{opacity:.9!important}.leaflet-control-attribution{background:rgba(3,8,13,.7)!important;color:#7d8996!important}.leaflet-control-attribution a{color:#9ba7b4!important}
@media(max-width:800px){
 .hud{height:70px!important;padding:7px 8px!important;gap:6px!important}.hud .icon-btn{width:38px!important;height:38px!important;font-size:18px!important}.hud-brand{flex:1!important;min-width:90px!important}.hud-brand b{font-size:13px!important;letter-spacing:2px!important}.hud-brand span{font-size:7px!important;letter-spacing:1px!important}.hud-stats{height:48px!important;overflow:hidden!important}.hud-stats .hud-stat{min-width:42px!important;height:48px!important;padding:4px 5px!important;border-left:1px solid rgba(120,145,170,.14)!important}.hud-stats .hud-stat small{font-size:6px!important;letter-spacing:.5px!important}.hud-stats .hud-stat b{font-size:10px!important}.mtrw-level-wrap{width:34px;height:4px}.mtrw-map-legend{display:none}.mtrw-map-tools{right:9px;top:88px;gap:7px}.mtrw-map-tool{width:42px;height:42px;font-size:18px}.mtrw-map-tools .mtrw-tooltip{display:none}.bottom-nav{left:8px!important;right:8px!important;height:72px!important;border-radius:23px!important}.bottom-btn span{font-size:20px!important}.bottom-btn small{font-size:7px!important;letter-spacing:.7px!important}.drawer{bottom:86px!important}
}
`;
document.head.appendChild(css);
const getSave=()=>{try{const id=window.__mtrwUserId;if(id)return JSON.parse(localStorage.getItem('mafivera:v1:save:'+id)||'{}');const k=Object.keys(localStorage).find(x=>x.startsWith('mafivera:v1:save:'));return k?JSON.parse(localStorage.getItem(k)||'{}'):{} }catch(e){return{}}};
const setupHud=()=>{const stats=document.querySelector('.hud-stats');if(!stats)return false;stats.innerHTML=`<span class="hud-stat hud-money"><small>GELD</small><b id="money">0</b></span><span class="hud-stat hud-material"><small>MATERIAL</small><b id="material">0</b></span><span class="hud-stat hud-recruit"><small>SCHLÄGER</small><b id="recruitCount">0</b></span><span class="hud-stat hud-tiles"><small>KACHELN</small><b id="territoryCount">0</b></span><span class="hud-stat hud-level"><small>LEVEL <span id="ruhmText">0 RUHM</span></small><b id="level">1</b><div class="mtrw-level-wrap"><i id="levelProgress"></i></div></span>`;return true};
const refreshHud=()=>{const s=getSave(),set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=(Number(v)||0).toLocaleString('de-DE')};set('money',s.money);set('material',s.material);set('recruitCount',s.hitmen);set('territoryCount',s.territories||Object.keys(s.fields||{}).length);set('level',s.level||1);const r=Math.max(0,Number(s.reputation??s.influence)||0);set('ruhmText',`${Math.floor(r)} RUHM`);const p=document.getElementById('levelProgress');if(p)p.style.width=`${Math.min(100,r%100)}%`};
const addMapChrome=()=>{const game=document.querySelector('.mafivera-game');if(!game)return false;if(!game.querySelector('.mtrw-map-legend')){const legend=document.createElement('aside');legend.className='mtrw-map-legend';legend.innerHTML='<h4>Gebietsübersicht</h4><div><i class="own"></i>Eigene Gebiete</div><div><i class="ally"></i>Verbundete</div><div><i class="enemy"></i>Fremde Gebiete</div><div><i class="heist"></i>Heist Ziele</div><div><i class="industry"></i>Industrie</div><div><i class="city"></i>Stadtgebiet</div>';game.appendChild(legend)}
if(!game.querySelector('.mtrw-map-tools')){const tools=document.createElement('div');tools.className='mtrw-map-tools';tools.innerHTML='<button class="mtrw-map-tool" data-tool="locate">⌖<span class="mtrw-tooltip">GPS-Standort</span></button><button class="mtrw-map-tool" data-tool="info">ⓘ<span class="mtrw-tooltip">Karteninfo</span></button><button class="mtrw-map-tool alert" data-tool="heists">»<span class="mtrw-alert-count">0</span><span class="mtrw-tooltip">Bedrohte Felder</span></button><button class="mtrw-map-tool" data-tool="grid">▦<span class="mtrw-tooltip">Kachelraster</span></button>';game.appendChild(tools);tools.querySelector('[data-tool="locate"]').onclick=()=>document.getElementById('locateBtn')?.click();tools.querySelector('[data-tool="info"]').onclick=()=>document.getElementById('menuBtn')?.click();tools.querySelector('[data-tool="heists"]').onclick=()=>document.querySelector('[data-panel="more"]')?.click();tools.querySelector('[data-tool="grid"]').onclick=()=>{const paths=document.querySelectorAll('.leaflet-overlay-pane svg path');const hidden=paths.length&&paths[0].style.opacity==='0';paths.forEach(p=>p.style.opacity=hidden?'':'0')}}const alert=document.querySelector('.mtrw-alert-count');if(alert){const s=getSave();alert.textContent=String((s.threatFields||[]).length||0)}return true};
const patchNav=()=>{const nav=document.querySelector('.bottom-nav');if(!nav)return;const profile=nav.querySelector('[data-panel="profile"]');if(profile)profile.style.display='none';const recruit=nav.querySelector('#recruitNav');const social=nav.querySelector('[data-panel="social"]');if(recruit&&social)nav.insertBefore(recruit,social);const business=nav.querySelector('[data-panel="business"]');if(business){const small=business.querySelector('small');if(small)small.textContent='GESCHÄFTE'}nav.style.gridTemplateColumns='repeat(6,1fr)'};
const patchLabels=()=>{document.querySelectorAll('.drawer,.leaflet-popup-content').forEach(x=>{x.innerHTML=x.innerHTML.replaceAll('Ruf','Ruhmpunkte').replaceAll('RUF','RUHMPUNKTE')})};
const loadPassive=()=>{if(window.mtrwPassiveResourcesV1)return;const s=document.createElement('script');s.src='./passive-resources-v1.js?v=2';s.onload=()=>refreshHud();document.body.appendChild(s)};
const boot=()=>{loadPassive();setupHud();addMapChrome();patchNav();refreshHud();patchLabels();setTimeout(()=>{const map=document.getElementById('worldMap');if(map&&!map.querySelector('.leaflet-tile'))document.getElementById('mapReload')?.click()},1200);setInterval(()=>{setupHud();addMapChrome();patchNav();refreshHud()},1000);const root=document.getElementById('gameRoot');if(root)new MutationObserver(()=>{setupHud();addMapChrome();patchNav()}).observe(root,{subtree:true,childList:true})};
let tries=0;const timer=setInterval(()=>{if(boot()||++tries>120)clearInterval(timer)},250);
})();