/* MAFIVERA — Razzia-System v1 */
(()=>{'use strict';
let active=null,timer=null,marker=null;
const $=id=>document.getElementById(id);
const fmt=n=>Number(n||0).toLocaleString('de-DE');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function css(){if($('mtrwRaidCSS'))return;const s=document.createElement('style');s.id='mtrwRaidCSS';s.textContent=
'@keyframes mtrwPoliceRaid{0%,49%{fill:#1667ff!important;fill-opacity:.58!important;filter:drop-shadow(0 0 7px #1769ff)}50%,100%{fill:#e31b23!important;fill-opacity:.58!important;filter:drop-shadow(0 0 7px #e31b23)}}'+
'.mtrw-raid-field{animation:mtrwPoliceRaid .7s steps(1,end) infinite!important;stroke:#fff!important;stroke-width:3!important}'+
'#mtrwRaidPanel{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:99999;width:min(430px,calc(100vw - 28px));box-sizing:border-box;background:#0b1119f5;border:2px solid #e31b23;border-radius:16px;color:#fff;padding:12px;box-shadow:0 10px 40px #000c;font-family:Arial,sans-serif}'+
'#mtrwRaidPanel .rh{display:flex;justify-content:space-between;gap:10px;align-items:center}#mtrwRaidPanel b{font-size:16px}#mtrwRaidPanel small{display:block;color:#cbd5e1;margin-top:3px;line-height:1.3}#mtrwRaidPanel .rs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:9px 0}.mtrw-rs{padding:7px;border-radius:9px;background:#151e29;text-align:center}.mtrw-rs strong{display:block;font-size:17px}.mtrw-rs span{font-size:10px;color:#9ca8b6}.mtrw-raid-actions{display:flex;gap:7px}.mtrw-raid-actions button{flex:1;border:0;border-radius:10px;padding:10px;font-weight:900;cursor:pointer}.mtrw-raid-send{background:#2563eb;color:#fff}.mtrw-raid-center{background:#27313d;color:#fff}';
document.head.appendChild(s)}
function buildingName(t){return ({lab:'Chemielabor',weapon_factory:'Waffenfabrik',money:'Geldwäsche',club:'Clubhaus',warehouse:'Lager',market:'Schwarzmarkt',watch:'Wachposten',hideout:'Gangversteck',recruitment:'Rekrutierungszentrum'})[t]||t}
function clearVisual(){document.querySelectorAll('.mtrw-raid-field').forEach(x=>x.classList.remove('mtrw-raid-field'));if(marker){try{window.__mtrwMap?.removeLayer(marker)}catch(_){}marker=null}}
function applyVisual(r){clearVisual();if(!r?.active)return;const rects=window.__mtrwGridRects||[];let found=false;for(const x of rects){if(x?.__mtrwZone===r.zone_key){x.classList?.add('mtrw-raid-field');found=true}}if(!found&&window.__mtrwMap&&Number.isFinite(Number(r.lat))&&Number.isFinite(Number(r.lng))){marker=L.marker([r.lat,r.lng],{icon:L.divIcon({className:'',html:'<div style="width:42px;height:42px;border:4px solid #1769ff;border-radius:50%;box-shadow:0 0 16px #1769ff;background:#e31b23aa;animation:mtrwPoliceRaid .7s steps(1,end) infinite"></div>',iconSize:[42,42],iconAnchor:[21,21]})}).addTo(window.__mtrwMap)}}
function panel(){if(!active?.active){$('mtrwRaidPanel')?.remove();return}let p=$('mtrwRaidPanel');if(!p){p=document.createElement('section');p.id='mtrwRaidPanel';document.body.appendChild(p)}const sec=Math.max(0,Math.ceil((new Date(active.ends_at).getTime()-Date.now())/1000));p.innerHTML='<div class="rh"><div><b>🚨 POLIZEI-RAZZIA</b><small>'+esc(buildingName(active.building_type))+' · Stufe '+active.building_level+'</small></div><b>'+sec+'s</b></div><div class="rs"><div class="mtrw-rs"><strong>'+fmt(active.committed_hitmen)+'</strong><span>Schläger eingesetzt</span></div><div class="mtrw-rs"><strong>'+fmt(active.police_strength)+'</strong><span>Polizeistärke</span></div></div><div class="mtrw-raid-actions"><button class="mtrw-raid-send">👊 Schläger schicken</button><button class="mtrw-raid-center">📍 Feld zeigen</button></div>';
p.querySelector('.mtrw-raid-send').onclick=async()=>{const n=Math.max(1,Math.floor(Number(prompt('Wie viele Schläger zur Razzia schicken?','5'))||0));if(!n)return;const q=await window.db.rpc('mtrw_raid_defend',{p_raid_id:active.id,p_hitmen:n});if(q.error){alert(q.error.message);return}await poll(true)};
p.querySelector('.mtrw-raid-center').onclick=()=>{const m=window.__mtrwMap;if(m&&Number.isFinite(Number(active.lat))&&Number.isFinite(Number(active.lng)))m.setView([active.lat,active.lng],Math.max(m.getZoom(),17),{animate:true})}}
async function poll(force){if(!window.db)return;try{const q=await window.db.rpc('mtrw_raid_snapshot');if(q.error)throw q.error;const r=q.data||{};if(r.active){active=r;applyVisual(r);panel()}else if(active){active=null;clearVisual();$('mtrwRaidPanel')?.remove();try{window.mtrwMailboxReload?.()}catch(_){}}else active=null;if(force)window.dispatchEvent(new Event('mtrw:raid-updated'))}catch(e){console.error('Razzia:',e)}}
function boot(){css();if(!window.db)return setTimeout(boot,500);poll(false);timer=setInterval(()=>poll(false),10000);window.addEventListener('mtrw:location-updated',()=>poll(true))}
boot();window.mtrwRaidRefresh=()=>poll(true);
})();