/* MAFIVERA – shared global loot boxes */
(()=>{'use strict';
if(window.__mtrwLootLoaded)return;window.__mtrwLootLoaded=true;
const RADIUS=600,REFRESH=300000;let map=null,markers=new Map(),timer=null,channel=null,selected=null;
function pos(){const p=window.__mtrwPlayerLocation||window.__mtrwProfile||{};return{lat:Number(p.gps_lat),lng:Number(p.gps_lng)}}
function valid(p){return Number.isFinite(p.lat)&&Number.isFinite(p.lng)}
function dist(a,b){const R=6371000,la=a.lat*Math.PI/180,lb=b.lat*Math.PI/180,dl=(b.lat-a.lat)*Math.PI/180,dg=(b.lng-a.lng)*Math.PI/180;const x=Math.sin(dl/2)**2+Math.cos(la)*Math.cos(lb)*Math.sin(dg/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function icon(){return L.divIcon({className:'mtrw-loot-marker',html:'<div class="mtrw-loot-ring"><div class="mtrw-loot-box">📦</div></div><b>LOOTBOX</b>',iconSize:[82,86],iconAnchor:[41,43]})}
function css(){if(document.getElementById('mtrwLootStyle'))return;const s=document.createElement('style');s.id='mtrwLootStyle';s.textContent='.mtrw-loot-marker{background:transparent!important;border:0!important;text-align:center;filter:drop-shadow(0 5px 10px #000b);cursor:pointer}.mtrw-loot-marker .mtrw-loot-ring{width:64px;height:64px;margin:auto;border:2px solid #e3b341;border-radius:50%;background:radial-gradient(circle,#3a2812 0%,#151a21 68%);display:grid;place-items:center;box-shadow:0 0 18px #e3b34199,0 0 0 3px #111a}.mtrw-loot-marker .mtrw-loot-box{width:44px;height:38px;display:grid;place-items:center;border:2px solid #f2c14e;border-radius:8px;background:linear-gradient(145deg,#6b3d16,#b87924);font-size:25px;box-shadow:inset 0 2px 4px #fff3,0 0 10px #e3b34188}.mtrw-loot-marker b{display:block;margin-top:3px;font-size:10px;font-weight:900;letter-spacing:1.4px;color:#ffe9a3;text-shadow:0 2px 4px #000}.mtrw-loot-overlay{position:fixed;inset:0;z-index:100000;display:none;align-items:center;justify-content:center;background:#0009;backdrop-filter:blur(4px)}.mtrw-loot-overlay.show{display:flex}.mtrw-loot-card{width:min(88vw,380px);padding:22px;text-align:center;border:1px solid #c99835;border-radius:22px;background:linear-gradient(180deg,#1b2029,#0c1016);box-shadow:0 20px 70px #000d;color:#fff}.mtrw-loot-big{font-size:86px;line-height:1;margin:12px 0 20px;cursor:pointer;transition:transform .25s}.mtrw-loot-big.opening{animation:mtrwLootOpen .75s ease-in-out}.mtrw-loot-reward{min-height:42px;font-size:20px;font-weight:800;color:#ffd66b}.mtrw-loot-hint{color:#aeb7c3;font-size:13px}.mtrw-loot-close{position:absolute;top:18px;right:18px;border:1px solid #52606e;background:#111722;color:#fff;border-radius:12px;width:44px;height:44px;font-size:25px}.mtrw-loot-card h2{margin:0}.mtrw-loot-card .mtrw-loot-distance{font-size:12px;color:#84909d;margin-top:5px}@keyframes mtrwLootOpen{0%{transform:scale(1) rotate(0)}25%{transform:scale(1.12) rotate(-5deg)}50%{transform:scale(.94) rotate(5deg)}75%{transform:scale(1.18) rotate(-3deg)}100%{transform:scale(.15) rotate(15deg);opacity:.1}}';document.head.appendChild(s)}
function overlay(){let o=document.getElementById('mtrwLootOverlay');if(o)return o;o=document.createElement('div');o.id='mtrwLootOverlay';o.className='mtrw-loot-overlay';o.innerHTML='<button class="mtrw-loot-close" type="button">×</button><div class="mtrw-loot-card"><h2>📦 Lootbox</h2><div class="mtrw-loot-distance"></div><div class="mtrw-loot-big">📦</div><div class="mtrw-loot-reward"></div><div class="mtrw-loot-hint">Tippe die Lootbox an, um sie zu öffnen.</div></div>';document.body.appendChild(o);o.querySelector('.mtrw-loot-close').onclick=close;o.addEventListener('click',e=>{if(e.target===o)close()});return o}
function close(){const o=document.getElementById('mtrwLootOverlay');if(o)o.classList.remove('show');selected=null}
async function load(){if(!window.db)return;try{await window.db.rpc('mtrw_loot_spawn_cycle')}catch(e){}const q=await window.db.from('mtrw_loot_boxes').select('*').is('claimed_at',null).order('created_at',{ascending:false}).limit(100);if(q.error)return;render(q.data||[])}
function render(rows){if(!map)return;const p=pos();if(!valid(p))return;const keep=new Set();for(const b of rows){const bp={lat:Number(b.lat),lng:Number(b.lng)};if(!valid(bp)||dist(p,bp)>RADIUS)continue;keep.add(b.id);if(markers.has(b.id))continue;const m=L.marker([bp.lat,bp.lng],{icon:icon(),zIndexOffset:1200,interactive:true}).addTo(map);m.on('click',()=>focus(b));markers.set(b.id,m)}for(const [id,m] of markers){if(!keep.has(id)){m.remove();markers.delete(id)}}}
function focus(b){selected=b;const map2=window.__mtrwMap;if(map2)map2.flyTo([b.lat,b.lng],Math.max(map2.getZoom(),18),{duration:.7});const o=overlay(),big=o.querySelector('.mtrw-loot-big'),reward=o.querySelector('.mtrw-loot-reward'),hint=o.querySelector('.mtrw-loot-hint');reward.textContent='';big.textContent='📦';big.className='mtrw-loot-big';hint.textContent='Tippe die Lootbox an, um sie zu öffnen.';const p=pos();o.querySelector('.mtrw-loot-distance').textContent=valid(p)?Math.round(dist(p,{lat:b.lat,lng:b.lng}))+' m entfernt':'';o.classList.add('show');big.onclick=()=>claim(b,big,reward,hint)}
async function claim(b,big,reward,hint){if(!selected||big.classList.contains('opening'))return;big.classList.add('opening');hint.textContent='Die Lootbox wird geöffnet …';try{const r=await window.db.rpc('mtrw_claim_loot_box',{p_box_id:b.id});if(r.error)throw r.error;const x=r.data||{};setTimeout(()=>{big.textContent='🎁';big.className='mtrw-loot-big';reward.textContent='Gefunden: '+(x.display||'Belohnung');hint.textContent='Die Lootbox ist für alle Spieler verschwunden.';remove(b.id)},650)}catch(e){big.classList.remove('opening');hint.textContent=e.message==='loot_box_too_far'?'Du bist noch zu weit entfernt.':e.message==='loot_box_unavailable'?'Die Lootbox wurde bereits von jemand anderem geöffnet.':'Lootbox konnte nicht geöffnet werden.';if(e.message==='loot_box_unavailable')remove(b.id)}}
function remove(id){const m=markers.get(id);if(m){m.remove();markers.delete(id)}}
function realtime(){if(channel||!window.db)return;channel=window.db.channel('mtrw-loot-boxes').on('postgres_changes',{event:'*',schema:'public',table:'mtrw_loot_boxes'},()=>load()).subscribe()}
function boot(){css();map=window.__mtrwMap;realtime();load();timer=setInterval(load,REFRESH)}
function wait(){if(window.db&&window.__mtrwMap)boot();else setTimeout(wait,300)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait);else wait();
window.addEventListener('beforeunload',()=>{if(timer)clearInterval(timer);if(channel&&window.db)window.db.removeChannel(channel)});
})();