/* MAFIVERA V1 — production, business tasks, dealer market & player radar */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let db=null,dealer=null,radar=null,radarTimer=null,playerMarkers=null;
const drugs={cocaine:'Kokain',weed:'Cannabis',meth:'Methamphetamin',heroin:'Heroin'};
const tasks={bribe:['Leute bestechen',250,'30 Min.','+25 Ruf · +40 XP'],gang_attack:['Bandenangriff',500,'1 Std.','+1.200 $ · +100 Material · +10 Ruf · +75 XP'],smuggling:['Schmuggelauftrag',1000,'2 Std.','+2.500 $ · +200 Material · +20 Ruf · +1 Droge · +120 XP'],protection:['Schutzgeld eintreiben',750,'90 Min.','+1.800 $ · +15 Ruf · +90 XP']};
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString('de-DE');
async function rpc(n,a={}){if(!db)db=window.db;const r=await db.rpc(n,a);if(r.error)throw r.error;return r.data}
function panel(title,html){const d=$('drawer'),t=$('drawerTitle'),b=$('drawerBody');if(!d||!t||!b)return;t.textContent=title;b.innerHTML=html;d.classList.remove('hidden');b.querySelectorAll('[data-market]').forEach(x=>x.onclick=()=>marketAction(x.dataset.market,x.dataset.id))}
function close(){ $('drawer')?.classList.add('hidden') }
async function business(){panel('Geschäfte',`<div class="hero"><span class="hero-icon">🏢</span><div><b>Geschäfte</b><p>Produktion läuft serverseitig. Bis zu 3 Unternehmungen können gleichzeitig im Hintergrund laufen. Der Drogenverkauf erfolgt ausschließlich über Dealer.</p></div></div><div class="market-menu"><button class="action primary" data-market="production">⚗️ Drogenproduktion</button><button class="action" data-market="tasks">📋 Unternehmungen</button></div><div class="hint">Dealer erscheinen alle 30 Minuten für ca. 2–3 Minuten. Spieler und Dealer in deinem Radar können direkt angeklickt werden.</div>`)}
async function production(){let state=null;try{state=await rpc('mafivera_collect_production')}catch(e){}const prof=await rpc('mafivera_bootstrap'),p=prof?.profile||{},active=state?.running,max=Math.floor((p.material||0)/3),inv=await db.from('mtrw_drug_inventory').select('drug_type,quantity').eq('user_id',p.id),rows=inv.data||[];panel('Produktion',`<div class="hero"><span class="hero-icon">⚗️</span><div><b>Drogenproduktion</b><p>3 Material → 1 Droge · 30 Sekunden pro Stück · läuft serverseitig weiter.</p></div></div><div class="statgrid"><div><b>${fmt(p.material)}</b><small>Material</small></div><div><b>${fmt(p.product)}</b><small>Drogen</small></div><div><b>${fmt(max)}</b><small>max. Auftrag</small></div></div>${active?`<div class="production-card"><h3>⏳ Produktion läuft</h3><div><b>${active.quantity}× ${esc(drugs[active.drug_type]||active.drug_type)}</b><small>Fertig: ${new Date(active.finish_at).toLocaleTimeString('de-DE')}</small></div></div>`:`<div class="production-card"><h3>Neue Produktion</h3><label>Droge</label><select id="marketDrug"><option value="cocaine">Kokain</option><option value="weed">Cannabis</option><option value="meth">Methamphetamin</option><option value="heroin">Heroin</option></select><label>Menge</label><input id="marketQty" type="number" min="1" max="${Math.max(1,max)}" value="${max?1:0}"><button class="action primary" data-market="start-production">▶️ Produktion starten</button><small>${max} Stück sind mit deinem aktuellen Material möglich.</small></div>`}${rows.length?`<div class="list"><h3>Lagerbestand</h3>${rows.map(r=>`<div class="row"><span>💊 ${esc(drugs[r.drug_type]||r.drug_type)}</span><b>${fmt(r.quantity)}</b></div>`).join('')}</div>`:''}`)}
async function tasksPanel(){let processed=[];try{processed=await rpc('mafivera_process_business_tasks')}catch(e){}const q=await db.from('mtrw_business_tasks').select('id,task_type,title,cost_money,reward_money,reward_material,reward_reputation,reward_product,reward_xp,started_at,finish_at,status,collected_at').order('created_at',{ascending:false}).limit(20);if(q.error)throw q.error;const rows=q.data||[],running=rows.filter(x=>x.status==='running');panel('Unternehmungen',`<div class="hero"><span class="hero-icon">📋</span><div><b>Hintergrund-Aufgaben</b><p>Bis zu 3 Aufgaben laufen gleichzeitig und werden serverseitig weitergeführt – auch wenn du offline bist.</p></div></div>${processed.length?`<div class="task-complete">✅ ${processed.length} Aufgabe${processed.length===1?'':'n'} abgeschlossen. Die Belohnung wurde automatisch gutgeschrieben.</div>`:''}<h3>Aktive Aufgaben · ${running.length}/3</h3><div class="list">${running.map(t=>`<div class="task-card"><div><b>${esc(t.title)}</b><small>Fertig: ${new Date(t.finish_at).toLocaleString('de-DE')}</small><small>${rewardText(t)}</small></div><span>⏳</span></div>`).join('')||'<div class="hint">Keine aktiven Aufgaben.</div>'}</div><h3>Neue Unternehmung</h3><div class="list">${Object.entries(tasks).map(([k,v])=>`<div class="task-card"><div><b>${v[0]}</b><small>${fmt(v[1])} $ · ${v[2]}</small><small>${v[3]}</small></div><button class="mini" data-market="start-task" data-id="${k}" ${running.length>=3?'disabled':''}>Start</button></div>`).join('')}</div>`)}
function rewardText(t){return `Belohnung: +${fmt(t.reward_money)} $ · +${fmt(t.reward_material)} Material · +${fmt(t.reward_reputation)} Ruf · +${fmt(t.reward_product)} Drogen · +${fmt(t.reward_xp)} XP`}
async function dealerState(){try{const s=await rpc('mtrw_dealer_state');dealer=s;if(s?.active){showDealer(s);if(!dealerMarker&&window.__mtrwMap&&window.L){dealerMarker=L.marker([s.lat,s.lng],{icon:L.divIcon({className:'dealer-marker',html:'<span>💊</span><b>DEALER</b>',iconSize:[72,48],iconAnchor:[36,24]})}).addTo(window.__mtrwMap);dealerMarker.on('click',dealerMenu)}}else hideDealer()}catch(e){hideDealer()}}
function showDealer(s){let x=$('dealerAlert');if(!x){x=document.createElement('button');x.id='dealerAlert';x.className='dealer-alert';document.querySelector('.mf-app')?.appendChild(x);x.onclick=dealerMenu}x.innerHTML=`💊 DEALER AKTIV · ${esc(drugs[s.drug_type]||s.drug_type)} · ${fmt(s.price)} /* MAFIVERA V1 — production, business tasks, dealer market & player radar */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let db=null,dealer=null,radar=null,radarTimer=null,playerMarkers=null;
const drugs={cocaine:'Kokain',weed:'Cannabis',meth:'Methamphetamin',heroin:'Heroin'};
const tasks={bribe:['Leute bestechen',250,'30 Min.','+25 Ruf · +40 XP'],gang_attack:['Bandenangriff',500,'1 Std.','+1.200 $ · +100 Material · +10 Ruf · +75 XP'],smuggling:['Schmuggelauftrag',1000,'2 Std.','+2.500 $ · +200 Material · +20 Ruf · +1 Droge · +120 XP'],protection:['Schutzgeld eintreiben',750,'90 Min.','+1.800 $ · +15 Ruf · +90 XP']};
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString('de-DE');
async function rpc(n,a={}){if(!db)db=window.db;const r=await db.rpc(n,a);if(r.error)throw r.error;return r.data}
function panel(title,html){const d=$('drawer'),t=$('drawerTitle'),b=$('drawerBody');if(!d||!t||!b)return;t.textContent=title;b.innerHTML=html;d.classList.remove('hidden');b.querySelectorAll('[data-market]').forEach(x=>x.onclick=()=>marketAction(x.dataset.market,x.dataset.id))}
function close(){ $('drawer')?.classList.add('hidden') }
;x.style.display='block';if(dealerMarker)dealerMarker.setLatLng([s.lat,s.lng])}
function hideDealer(){if($('dealerAlert'))$('dealerAlert').style.display='none';if(dealerMarker){dealerMarker.remove();dealerMarker=null}}
async function dealerMenu(){if(!dealer?.active)return panel('Dealer','<div class="hint">Der Dealer ist gerade nicht aktiv.</div>');const sid=(await db.auth.getSession()).data.session.user.id,inv=await db.from('mtrw_drug_inventory').select('quantity').eq('user_id',sid).eq('drug_type',dealer.drug_type).maybeSingle(),have=Number(inv.data?.quantity||0),max=Math.min(have,Number(dealer.remaining||0));panel('Dealer',`<div class="hero"><span class="hero-icon">🕴️</span><div><b>${esc(drugs[dealer.drug_type]||dealer.drug_type)}-Dealer</b><p>Aktueller Preis: <b>${fmt(dealer.price)} $</b> pro Stück</p></div></div><div class="statgrid"><div><b>${have}</b><small>Dein Bestand</small></div><div><b>${dealer.remaining}</b><small>Dealer-Abnahme</small></div><div><b>${max}</b><small>Verkauf möglich</small></div></div>${max?`<label>Menge</label><input id="dealerQty" type="number" min="1" max="${max}" value="1"><button class="action primary" data-market="sell">💰 Verkaufen</button>`:'<div class="hint">Kein passender Bestand oder der Dealer hat seine Abnahmemenge ausgeschöpft.</div>'}<div class="hint">Der Dealer bleibt nur kurz aktiv und nimmt maximal ${dealer.remaining} Stück ab.</div>`)}
async function playerMenu(p){panel('Spielerprofil',`<div class="player-profile"><div class="player-avatar">👤</div><div><h2>${esc(p.username||'Spieler')}</h2><small>${esc(p.mafia_name||'Keine Familie')} · Level ${fmt(p.level||1)}</small></div></div><div class="statgrid"><div><b>${fmt(p.level||1)}</b><small>Level</small></div><div><b>${fmt(p.xp||0)}</b><small>XP</small></div><div><b>${fmt(Math.round(p.distance_m||0))} m</b><small>Entfernung</small></div></div><div class="list"><button class="action" data-market="friend" data-id="${p.id}">🤝 Freundschaftsanfrage senden</button><button class="action primary" data-market="family" data-id="${p.id}">♜ In meine Familie einladen</button></div><div class="hint">Nur öffentliche Profildaten werden im Radar angezeigt. Aktionen sind serverseitig geschützt.</div>`)}
async function radarState(){try{const rows=await rpc('mtrw_nearby_players',{p_radius_m:500}),map=window.__mtrwMap;if(!map||!window.L)return;if(!playerMarkers)playerMarkers=L.layerGroup().addTo(map);playerMarkers.clearLayers();rows.forEach(p=>{const m=L.marker([p.lat,p.lng],{icon:L.divIcon({className:'near-player-marker',html:`<span>👤</span><b>${esc(p.username||'Spieler')}</b>`,iconSize:[90,44],iconAnchor:[45,22]})});m.on('click',()=>playerMenu(p));m.addTo(playerMarkers)});if(window.__mtrwProfile?.gps_lat&&window.__mtrwProfile?.gps_lng)drawRadar(window.__mtrwProfile.gps_lat,window.__mtrwProfile.gps_lng);else{const c=map.getCenter();drawRadar(c.lat,c.lng)}}catch(e){}}
function drawRadar(lat,lng){const map=window.__mtrwMap;if(!map||!window.L)return;if(!radar)radar=L.circle([lat,lng],{radius:500,color:'#45e06f',weight:2,fillColor:'#45e06f',fillOpacity:.06,interactive:false}).addTo(map);else radar.setLatLng([lat,lng])}
async function marketAction(a,id){try{if(a==='production')return production();if(a==='tasks')return tasksPanel();if(a==='start-production'){const n=Math.max(1,Math.floor(Number($('marketQty')?.value||0))),d=$('marketDrug')?.value||'cocaine';await rpc('mafivera_start_production',{p_quantity:n,p_drug_type:d});return production()}if(a==='start-task'){await rpc('mafivera_start_business_task',{p_task_type:id});toast('Aufgabe gestartet – sie läuft im Hintergrund weiter.');return tasksPanel()}if(a==='sell'){const n=Math.max(1,Math.floor(Number($('dealerQty')?.value||0))),r=await rpc('mtrw_sell_to_dealer',{p_spawn_id:dealer.id,p_drug_type:dealer.drug_type,p_quantity:n});await rpc('mafivera_bootstrap');dealer.remaining=r.remaining;await dealerMenu();showDealer(dealer);toast(`Verkauft: ${r.sold} · +${fmt(r.earned)} /* MAFIVERA V1 — production, business tasks, dealer market & player radar */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let db=null,dealer=null,radar=null,radarTimer=null,playerMarkers=null;
const drugs={cocaine:'Kokain',weed:'Cannabis',meth:'Methamphetamin',heroin:'Heroin'};
const tasks={bribe:['Leute bestechen',250,'30 Min.','+25 Ruf · +40 XP'],gang_attack:['Bandenangriff',500,'1 Std.','+1.200 $ · +100 Material · +10 Ruf · +75 XP'],smuggling:['Schmuggelauftrag',1000,'2 Std.','+2.500 $ · +200 Material · +20 Ruf · +1 Droge · +120 XP'],protection:['Schutzgeld eintreiben',750,'90 Min.','+1.800 $ · +15 Ruf · +90 XP']};
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString('de-DE');
async function rpc(n,a={}){if(!db)db=window.db;const r=await db.rpc(n,a);if(r.error)throw r.error;return r.data}
function panel(title,html){const d=$('drawer'),t=$('drawerTitle'),b=$('drawerBody');if(!d||!t||!b)return;t.textContent=title;b.innerHTML=html;d.classList.remove('hidden');b.querySelectorAll('[data-market]').forEach(x=>x.onclick=()=>marketAction(x.dataset.market,x.dataset.id))}
function close(){ $('drawer')?.classList.add('hidden') }
);return}if(a==='friend'){await rpc('mtrw_send_friend_invite',{p_user_id:id});toast('Freundschaftsanfrage gesendet.');return}if(a==='family'){await rpc('mtrw_invite_nearby_to_family',{p_user_id:id});toast('Familieneinladung gesendet.');return}}catch(e){const x=$('toast');if(x){x.textContent=e.message||'Aktion fehlgeschlagen';x.className='toast show error';setTimeout(()=>x.className='toast',2800)}}}
function capture(){document.querySelectorAll('.bottom-btn[data-panel="business"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();business()},true));$('drawerClose')?.addEventListener('click',close)}
function boot(){if(!window.L)return;const old=L.map;L.map=function(){const m=old.apply(this,arguments);window.__mtrwMap=m;setTimeout(()=>{dealerState();radarState()},500);return m};const style=document.createElement('style');style.textContent='.dealer-marker,.near-player-marker{background:transparent!important;border:0!important;text-align:center}.dealer-marker span,.near-player-marker span{display:block;font-size:25px;line-height:25px;filter:drop-shadow(0 2px 4px #000)}.dealer-marker b,.near-player-marker b{display:block;background:#080d13e8;border:1px solid #45e06f;border-radius:7px;padding:2px 5px;font-size:8px;color:#8dff9f;white-space:nowrap}.dealer-marker b{border-color:#d86cff;color:#f0c8ff}.dealer-alert{position:absolute;left:50%;transform:translateX(-50%);top:94px;z-index:45;border:1px solid #d86cff;background:#17101eea;color:#f0c8ff;border-radius:20px;padding:9px 15px;font-weight:900;font-size:11px;box-shadow:0 8px 25px #0008;display:none}.production-card label,.production-card input,.production-card select{display:block;width:100%;margin-top:9px}.production-card input,.production-card select{height:48px;border:1px solid #394653;border-radius:11px;background:#0b1016;color:#fff;padding:0 12px;font-size:17px}.production-card label{color:#aeb7c3;font-weight:800}.production-card small,.task-card small{display:block;color:#7f8997;margin-top:5px}.market-menu{display:grid;grid-template-columns:1fr 1fr;gap:10px}.task-card{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px;border:1px solid #28333f;border-radius:13px;background:#0c1219;margin:8px 0}.task-card>div{min-width:0}.task-complete{padding:12px;border:1px solid #45e06f;border-radius:12px;background:#122016;color:#aaffb0;font-weight:800}.player-profile{display:flex;align-items:center;gap:14px;padding:12px 0}.player-profile h2{margin:0 0 4px}.player-avatar{width:54px;height:54px;border-radius:50%;display:grid;place-items:center;background:#15231a;border:1px solid #45e06f;font-size:28px}';document.head.appendChild(style);let tries=0;const t=setInterval(()=>{if(window.db&&document.querySelector('.bottom-btn[data-panel="business"]')){clearInterval(t);capture();dealerState();radarState();radarTimer=setInterval(()=>{dealerState();radarState()},5000)}else if(++tries>60)clearInterval(t)},500);
window.addEventListener('mtrw:gps',e=>{if(e.detail?.lat&&e.detail?.lng){window.__mtrwProfile={gps_lat:e.detail.lat,gps_lng:e.detail.lng};drawRadar(e.detail.lat,e.detail.lng)}});
// Eigener GPS-Fallback: Der Radarkreis hängt ausschließlich an der echten Position des Spielers,
// niemals am Kartenmittelpunkt. Dadurch bleibt der Spieler immer das Zentrum des 500-m-Radius.
if(navigator.geolocation){navigator.geolocation.watchPosition(p=>{const lat=p.coords.latitude,lng=p.coords.longitude;window.__mtrwProfile={gps_lat:lat,gps_lng:lng};drawRadar(lat,lng)},()=>{}, {enableHighAccuracy:true,maximumAge:5000,timeout:15000});}
}
async function tasksPanel(){let processed=[];try{processed=await rpc('mafivera_process_business_tasks')}catch(e){}const q=await db.from('mtrw_business_tasks').select('id,task_type,title,cost_money,reward_money,reward_material,reward_reputation,reward_product,reward_xp,started_at,finish_at,status,collected_at').order('created_at',{ascending:false}).limit(20);if(q.error)throw q.error;const rows=q.data||[],running=rows.filter(x=>x.status==='running');panel('Unternehmungen',`<div class="hero"><span class="hero-icon">📋</span><div><b>Hintergrund-Aufgaben</b><p>Bis zu 3 Aufgaben laufen gleichzeitig und werden serverseitig weitergeführt – auch wenn du offline bist.</p></div></div>${processed.length?`<div class="task-complete">✅ ${processed.length} Aufgabe${processed.length===1?'':'n'} abgeschlossen. Die Belohnung wurde automatisch gutgeschrieben.</div>`:''}<h3>Aktive Aufgaben · ${running.length}/3</h3><div class="list">${running.map(t=>`<div class="task-card"><div><b>${esc(t.title)}</b><small>Fertig: ${new Date(t.finish_at).toLocaleString('de-DE')}</small><small>${rewardText(t)}</small></div><span>⏳</span></div>`).join('')||'<div class="hint">Keine aktiven Aufgaben.</div>'}</div><h3>Neue Unternehmung</h3><div class="list">${Object.entries(tasks).map(([k,v])=>`<div class="task-card"><div><b>${v[0]}</b><small>${fmt(v[1])} $ · ${v[2]}</small><small>${v[3]}</small></div><button class="mini" data-market="start-task" data-id="${k}" ${running.length>=3?'disabled':''}>Start</button></div>`).join('')}</div>`)}
function rewardText(t){return `Belohnung: +${fmt(t.reward_money)} $ · +${fmt(t.reward_material)} Material · +${fmt(t.reward_reputation)} Ruf · +${fmt(t.reward_product)} Drogen · +${fmt(t.reward_xp)} XP`}
// Dealer-Status wird hier nur noch für das Geschäfte-Menü gehalten. Marker und sichtbare
// Dealer-Anzeige gehören ausschließlich mafivera-dealer-v2.js, damit keine Doppelanzeige entsteht.
async function dealerState(){try{dealer=await rpc('mtrw_dealer_state')}catch(e){/* Dealer-V2 besitzt die sichtbare Fehlerbehandlung. */}}
function showDealer(s){dealer=s}
function hideDealer(){}
async function dealerMenu(){if(!dealer?.active)return panel('Dealer','<div class="hint">Der Dealer ist gerade nicht aktiv.</div>');const sid=(await db.auth.getSession()).data.session.user.id,inv=await db.from('mtrw_drug_inventory').select('quantity').eq('user_id',sid).eq('drug_type',dealer.drug_type).maybeSingle(),have=Number(inv.data?.quantity||0),max=Math.min(have,Number(dealer.remaining||0));panel('Dealer',`<div class="hero"><span class="hero-icon">🕴️</span><div><b>${esc(drugs[dealer.drug_type]||dealer.drug_type)}-Dealer</b><p>Aktueller Preis: <b>${fmt(dealer.price)} $</b> pro Stück</p></div></div><div class="statgrid"><div><b>${have}</b><small>Dein Bestand</small></div><div><b>${dealer.remaining}</b><small>Dealer-Abnahme</small></div><div><b>${max}</b><small>Verkauf möglich</small></div></div>${max?`<label>Menge</label><input id="dealerQty" type="number" min="1" max="${max}" value="1"><button class="action primary" data-market="sell">💰 Verkaufen</button>`:'<div class="hint">Kein passender Bestand oder der Dealer hat seine Abnahmemenge ausgeschöpft.</div>'}<div class="hint">Der Dealer bleibt nur kurz aktiv und nimmt maximal ${dealer.remaining} Stück ab.</div>`)}
async function playerMenu(p){panel('Spielerprofil',`<div class="player-profile"><div class="player-avatar">👤</div><div><h2>${esc(p.username||'Spieler')}</h2><small>${esc(p.mafia_name||'Keine Familie')} · Level ${fmt(p.level||1)}</small></div></div><div class="statgrid"><div><b>${fmt(p.level||1)}</b><small>Level</small></div><div><b>${fmt(p.xp||0)}</b><small>XP</small></div><div><b>${fmt(Math.round(p.distance_m||0))} m</b><small>Entfernung</small></div></div><div class="list"><button class="action" data-market="friend" data-id="${p.id}">🤝 Freundschaftsanfrage senden</button><button class="action primary" data-market="family" data-id="${p.id}">♜ In meine Familie einladen</button></div><div class="hint">Nur öffentliche Profildaten werden im Radar angezeigt. Aktionen sind serverseitig geschützt.</div>`)}
async function radarState(){try{const rows=await rpc('mtrw_nearby_players',{p_radius_m:500}),map=window.__mtrwMap;if(!map||!window.L)return;if(!playerMarkers)playerMarkers=L.layerGroup().addTo(map);playerMarkers.clearLayers();rows.forEach(p=>{const m=L.marker([p.lat,p.lng],{icon:L.divIcon({className:'near-player-marker',html:`<span>👤</span><b>${esc(p.username||'Spieler')}</b>`,iconSize:[90,44],iconAnchor:[45,22]})});m.on('click',()=>playerMenu(p));m.addTo(playerMarkers)});if(window.__mtrwProfile?.gps_lat&&window.__mtrwProfile?.gps_lng)drawRadar(window.__mtrwProfile.gps_lat,window.__mtrwProfile.gps_lng);else{const c=map.getCenter();drawRadar(c.lat,c.lng)}}catch(e){}}
function drawRadar(lat,lng){const map=window.__mtrwMap;if(!map||!window.L)return;if(!radar)radar=L.circle([lat,lng],{radius:500,color:'#45e06f',weight:2,fillColor:'#45e06f',fillOpacity:.06,interactive:false}).addTo(map);else radar.setLatLng([lat,lng])}
async function marketAction(a,id){try{if(a==='production')return production();if(a==='tasks')return tasksPanel();if(a==='start-production'){const n=Math.max(1,Math.floor(Number($('marketQty')?.value||0))),d=$('marketDrug')?.value||'cocaine';await rpc('mtrw_start_production',{p_quantity:n,p_drug_type:d});return production()}if(a==='start-weapon-production'){const n=Math.max(1,Math.floor(Number($('marketWeaponQty')?.value||0))),d=$('marketWeapon')?.value||'weapon_melee';await rpc('mtrw_start_production',{p_quantity:n,p_drug_type:d});return production()}if(a==='start-task'){await rpc('mafivera_start_business_task',{p_task_type:id});toast('Aufgabe gestartet – sie läuft im Hintergrund weiter.');return tasksPanel()}if(a==='sell'){const n=Math.max(1,Math.floor(Number($('dealerQty')?.value||0))),r=await rpc('mtrw_sell_to_dealer',{p_spawn_id:dealer.id,p_drug_type:dealer.drug_type,p_quantity:n});await rpc('mafivera_bootstrap');dealer.remaining=r.remaining;await dealerMenu();showDealer(dealer);toast(`Verkauft: ${r.sold} · +${fmt(r.earned)} $`);return}if(a==='friend'){await rpc('mtrw_send_friend_invite',{p_user_id:id});toast('Freundschaftsanfrage gesendet.');return}if(a==='family'){await rpc('mtrw_invite_nearby_to_family',{p_user_id:id});toast('Familieneinladung gesendet.');return}}catch(e){const x=$('toast');if(x){x.textContent=e.message||'Aktion fehlgeschlagen';x.className='toast show error';setTimeout(()=>x.className='toast',2800)}}}
function capture(){document.querySelectorAll('.bottom-btn[data-panel="business"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();business()},true));$('drawerClose')?.addEventListener('click',close)}
function boot(){if(!window.L)return;const old=L.map;L.map=function(){const m=old.apply(this,arguments);window.__mtrwMap=m;setTimeout(()=>{dealerState();radarState()},500);return m};const style=document.createElement('style');style.textContent='.dealer-marker,.near-player-marker{background:transparent!important;border:0!important;text-align:center}.dealer-marker span,.near-player-marker span{display:block;font-size:25px;line-height:25px;filter:drop-shadow(0 2px 4px #000)}.dealer-marker b,.near-player-marker b{display:block;background:#080d13e8;border:1px solid #45e06f;border-radius:7px;padding:2px 5px;font-size:8px;color:#8dff9f;white-space:nowrap}.dealer-marker b{border-color:#d86cff;color:#f0c8ff}.dealer-alert{display:none!important}.production-card label,.production-card input,.production-card select{display:block;width:100%;margin-top:9px}.production-card input,.production-card select{height:48px;border:1px solid #394653;border-radius:11px;background:#0b1016;color:#fff;padding:0 12px;font-size:17px}.production-card label{color:#aeb7c3;font-weight:800}.production-card small,.task-card small{display:block;color:#7f8997;margin-top:5px}.market-menu{display:grid;grid-template-columns:1fr 1fr;gap:10px}.task-card{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px;border:1px solid #28333f;border-radius:13px;background:#0c1219;margin:8px 0}.task-card>div{min-width:0}.task-complete{padding:12px;border:1px solid #45e06f;border-radius:12px;background:#122016;color:#aaffb0;font-weight:800}.player-profile{display:flex;align-items:center;gap:14px;padding:12px 0}.player-profile h2{margin:0 0 4px}.player-avatar{width:54px;height:54px;border-radius:50%;display:grid;place-items:center;background:#15231a;border:1px solid #45e06f;font-size:28px}';document.head.appendChild(style);let tries=0;const t=setInterval(()=>{if(window.db&&document.querySelector('.bottom-btn[data-panel="business"]')){clearInterval(t);capture();dealerState();radarState();radarTimer=setInterval(()=>{dealerState();radarState()},5000)}else if(++tries>60)clearInterval(t)},500);
window.addEventListener('mtrw:gps',e=>{if(e.detail?.lat&&e.detail?.lng){window.__mtrwProfile={gps_lat:e.detail.lat,gps_lng:e.detail.lng};drawRadar(e.detail.lat,e.detail.lng)}});
if(navigator.geolocation){navigator.geolocation.watchPosition(p=>{const lat=p.coords.latitude,lng=p.coords.longitude;window.__mtrwProfile={gps_lat:lat,gps_lng:lng};drawRadar(lat,lng)},()=>{}, {enableHighAccuracy:true,maximumAge:5000,timeout:15000});}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();