/* MAFIVERA V1 — dealer market */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db=null,dealer=null,marker=null,timer=null;
const drugs={cocaine:'Kokain',weed:'Cannabis',meth:'Methamphetamin',heroin:'Heroin'},$=id=>document.getElementById(id);
async function rpc(n,a={}){if(!db)db=window.db;const r=await db.rpc(n,a);if(r.error)throw r.error;return r.data}
function panel(title,html){const d=$('drawer'),t=$('drawerTitle'),b=$('drawerBody');if(!d||!t||!b)return;t.textContent=title;b.innerHTML=html;d.classList.remove('hidden');b.querySelectorAll('[data-market]').forEach(x=>x.onclick=()=>marketAction(x.dataset.market));}
function close(){ $('drawer')?.classList.add('hidden') }
async function business(){panel('Geschäfte',`<div class="hero"><span class="hero-icon">🏢</span><div><b>Geschäfte</b><p>Hier findest du deine Produktion. Der Verkauf erfolgt ausschließlich über aktive Dealer.</p></div></div><button class="action primary" data-market="production">⚗️ Produktion</button><div class="hint">Dealer erscheinen alle 30 Minuten für kurze Zeit an einem erreichbaren Standort in deiner Nähe. Dort kannst du deine Drogen zum aktuellen Preis verkaufen.</div>`)}
async function production(){let state=null;try{state=await rpc('mafivera_collect_production')}catch(e){}const prof=await rpc('mafivera_bootstrap'),p=prof?.profile||{},active=state?.running,max=Math.floor((p.material||0)/3),inv=await db.from('mtrw_drug_inventory').select('drug_type,quantity').eq('user_id',p.id),rows=inv.data||[];panel('Produktion',`<div class="hero"><span class="hero-icon">⚗️</span><div><b>Drogenproduktion</b><p>3 Material → 1 Droge · 30 Sekunden pro Stück · läuft serverseitig weiter.</p></div></div><div class="statgrid"><div><b>${Number(p.material||0).toLocaleString('de-DE')}</b><small>Material</small></div><div><b>${Number(p.product||0).toLocaleString('de-DE')}</b><small>Drogen</small></div><div><b>${max.toLocaleString('de-DE')}</b><small>max. Auftrag</small></div></div>${active?`<div class="production-card"><h3>⏳ Produktion läuft</h3><div><b>${active.quantity}× ${esc(drugs[active.drug_type]||active.drug_type)}</b><small>Fertig: ${new Date(active.finish_at).toLocaleTimeString('de-DE')}</small></div></div>`:`<div class="production-card"><h3>Neue Produktion</h3><label>Droge</label><select id="marketDrug"><option value="cocaine">Kokain</option><option value="weed">Cannabis</option><option value="meth">Methamphetamin</option><option value="heroin">Heroin</option></select><label>Wie viel willst du produzieren?</label><input id="marketQty" type="number" min="1" max="${Math.max(1,max)}" value="${max?1:0}"><button class="action primary" data-market="start-production">▶️ Produktion starten</button><small>${max} Stück sind mit deinem aktuellen Material möglich.</small></div>`}${rows.length?`<div class="list"><h3>Lagerbestand</h3>${rows.map(r=>`<div class="row"><span>💊 ${esc(drugs[r.drug_type]||r.drug_type)}</span><b>${Number(r.quantity).toLocaleString('de-DE')}</b></div>`).join('')}</div>`:''}`)}
async function dealerState(){try{const s=await rpc('mtrw_dealer_state');dealer=s;if(s?.active){showDealer(s);if(!marker&&window.__mtrwMap&&window.L){marker=L.marker([s.lat,s.lng],{icon:L.divIcon({className:'dealer-marker',html:'<span>💊</span><b>DEALER</b>',iconSize:[72,48],iconAnchor:[36,24]})}).addTo(window.__mtrwMap);marker.on('click',dealerMenu)}}else hideDealer()}catch(e){hideDealer()}}
function showDealer(s){let x=$('dealerAlert');if(!x){x=document.createElement('button');x.id='dealerAlert';x.className='dealer-alert';document.querySelector('.mf-app')?.appendChild(x);x.onclick=dealerMenu}x.innerHTML=`💊 DEALER AKTIV · ${esc(drugs[s.drug_type]||s.drug_type)} · ${s.price.toLocaleString('de-DE')} $`;x.style.display='block';if(marker)marker.setLatLng([s.lat,s.lng])}
function hideDealer(){if($('dealerAlert'))$('dealerAlert').style.display='none';if(marker){marker.remove();marker=null}}
async function dealerMenu(){if(!dealer?.active)return panel('Dealer','<div class="hint">Der Dealer ist gerade nicht aktiv.</div>');const sid=(await db.auth.getSession()).data.session.user.id,inv=await db.from('mtrw_drug_inventory').select('quantity').eq('user_id',sid).eq('drug_type',dealer.drug_type).maybeSingle(),have=Number(inv.data?.quantity||0),max=Math.min(have,Number(dealer.remaining||0));panel('Dealer',`<div class="hero"><span class="hero-icon">🕴️</span><div><b>${esc(drugs[dealer.drug_type]||dealer.drug_type)}-Dealer</b><p>Aktueller Preis: <b>${dealer.price.toLocaleString('de-DE')} $</b> pro Stück</p></div></div><div class="statgrid"><div><b>${have}</b><small>Dein Bestand</small></div><div><b>${dealer.remaining}</b><small>Abnahme möglich</small></div><div><b>${max}</b><small>Du kannst verkaufen</small></div></div>${max?`<label>Menge</label><input id="dealerQty" type="number" min="1" max="${max}" value="1"><button class="action primary" data-market="sell">💰 Verkaufen</button>`:'<div class="hint">Du hast diese Droge nicht im Lager oder der Dealer hat seine Abnahmemenge ausgeschöpft.</div>'}<div class="hint">Der Dealer bleibt nur kurz und nimmt maximal ${dealer.remaining} Stück ab.</div>`)}
async function marketAction(a){try{if(a==='production')return production();if(a==='start-production'){const n=Math.max(1,Math.floor(Number($('marketQty')?.value||0))),d=$('marketDrug')?.value||'cocaine';await rpc('mafivera_start_production',{p_quantity:n,p_drug_type:d});return production()}if(a==='sell'){const n=Math.max(1,Math.floor(Number($('dealerQty')?.value||0))),r=await rpc('mtrw_sell_to_dealer',{p_spawn_id:dealer.id,p_drug_type:dealer.drug_type,p_quantity:n});await rpc('mafivera_bootstrap');dealer.remaining=r.remaining;await dealerMenu();showDealer(dealer)}}catch(e){const x=$('toast');if(x){x.textContent=e.message||'Aktion fehlgeschlagen';x.className='toast show error';setTimeout(()=>x.className='toast',2800)}}}
function capture(){document.querySelectorAll('.bottom-btn[data-panel="business"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();business()},true));$('drawerClose')?.addEventListener('click',close)}
function boot(){const old=L.map;L.map=function(){const m=old.apply(this,arguments);window.__mtrwMap=m;setTimeout(dealerState,500);return m};const style=document.createElement('style');style.textContent='.dealer-marker{background:transparent!important;border:0!important;text-align:center}.dealer-marker span{display:block;font-size:27px;line-height:27px;filter:drop-shadow(0 2px 4px #000)}.dealer-marker b{display:block;background:#080d13e8;border:1px solid #d86cff;border-radius:7px;padding:2px 5px;font-size:8px;color:#d86cff}.dealer-alert{position:absolute;left:50%;transform:translateX(-50%);top:94px;z-index:45;border:1px solid #d86cff;background:#17101eea;color:#f0c8ff;border-radius:20px;padding:9px 15px;font-weight:900;font-size:11px;box-shadow:0 8px 25px #0008;display:none}.production-card label,.production-card input,.production-card select{display:block;width:100%;margin-top:9px}.production-card input,.production-card select{height:48px;border:1px solid #394653;border-radius:11px;background:#0b1016;color:#fff;padding:0 12px;font-size:17px}.production-card label{color:#aeb7c3;font-weight:800}.production-card small{display:block;color:#7f8997;margin-top:8px}';document.head.appendChild(style);let tries=0;const t=setInterval(()=>{if(window.db&&document.querySelector('.bottom-btn[data-panel="business"]')){clearInterval(t);capture();dealerState();timer=setInterval(dealerState,10000)}else if(++tries>60)clearInterval(t)},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();