(()=>{'use strict';
const boot=()=>{if(document.getElementById('mtrwMailbox'))return; if(!window.db)return setTimeout(boot,500);
const css=document.createElement('style');css.textContent=`
#mtrwMailbox{position:fixed;left:10px;top:50%;transform:translateY(-50%);z-index:100000}
#mtrwMailboxBtn{width:54px;height:54px;border:1px solid #394653;border-radius:16px;background:#10151eeb;color:#fff;font-size:25px;box-shadow:0 6px 20px #0008;cursor:pointer;position:relative}
#mtrwMailboxBadge{position:absolute;right:-5px;top:-5px;min-width:20px;height:20px;padding:0 5px;border-radius:10px;background:#d33;color:#fff;font:700 12px/20px Arial;text-align:center;display:none}
#mtrwMailboxPanel{display:none;position:fixed;left:74px;top:50%;transform:translateY(-50%);width:min(390px,calc(100vw - 90px));max-height:75vh;overflow:auto;background:#0b1018f5;border:1px solid #394653;border-radius:16px;box-shadow:0 12px 40px #000b;color:#eef2f7;padding:12px;font-family:Arial,sans-serif}
#mtrwMailboxPanel.open{display:block}.mtrw-mh{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.mtrw-mh b{font-size:18px}.mtrw-close{background:none;border:0;color:#aaa;font-size:22px}.mtrw-n{border:1px solid #293542;border-radius:12px;padding:10px;margin:8px 0;background:#111822}.mtrw-n.unread{border-color:#8c6a20}.mtrw-nt{font-weight:700}.mtrw-nm{font-size:13px;color:#c8d0d9;margin:5px 0}.mtrw-time{font-size:11px;color:#8995a3}.mtrw-actions{display:flex;gap:7px;margin-top:8px}.mtrw-actions button{flex:1;border:1px solid #445261;border-radius:8px;padding:8px;background:#18212c;color:#fff;cursor:pointer}.mtrw-actions .ok{background:#245b38}.mtrw-actions .no{background:#632d2d}.mtrw-actions button.claimed{background:#2a3037!important;border-color:#4b5563!important;color:#8d98a6!important;cursor:default!important;opacity:.9}.mtrw-gains{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:7px;font-size:12px}.mtrw-gains span{background:#17202a;padding:6px;border-radius:7px}
@media(max-width:600px){#mtrwMailbox{left:7px}#mtrwMailboxBtn{width:50px;height:50px}#mtrwMailboxPanel{left:64px;width:calc(100vw - 76px);max-height:78vh}}
`;document.head.appendChild(css);
const root=document.createElement('div');root.id='mtrwMailbox';root.innerHTML='<button id="mtrwMailboxBtn" aria-label="Mailbox">📬<span id="mtrwMailboxBadge"></span></button><div id="mtrwMailboxPanel"><div class="mtrw-mh"><b>📬 Mailbox</b><button class="mtrw-close">×</button></div><div id="mtrwMailboxList">Lade…</div></div>';document.body.appendChild(root);
const list=root.querySelector('#mtrwMailboxList'),badge=root.querySelector('#mtrwMailboxBadge'),panel=root.querySelector('#mtrwMailboxPanel');
const centerEvent=async n=>{const d=n?.action_data||{};const lat=Number(d.lat??d.latitude??d.gps_lat),lng=Number(d.lng??d.longitude??d.gps_lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||!window.__mtrwMap)return false;panel.classList.remove('open');const m=window.__mtrwMap;m.setView([lat,lng],Math.max(m.getZoom(),17),{animate:true});return true};
root.querySelector('#mtrwMailboxBtn').onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))load()};
root.querySelector('.mtrw-close').onclick=()=>panel.classList.remove('open');
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmt=t=>new Date(t).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'});
async function rpc(name,args={}){const r=await window.db.rpc(name,args);if(r.error)throw r.error;return r.data}
async function action(n,fn){try{await fn();await rpc('mtrw_notification_resolve',{p_id:n.id});await load()}catch(e){alert(e.message||'Aktion fehlgeschlagen')}}
function render(n){const d=n.action_data||{};let body=esc(n.message);let actions='';
if(n.action_type==='trade_offer'&&d.trade_id){actions='<div class="mtrw-actions"><button class="ok" data-ok>✓ Annehmen</button><button class="no" data-no>✕ Ablehnen</button></div>'}
else if(n.action_type==='friend_request'){actions='<div class="mtrw-actions"><button data-friend>👥 Freundesmenü öffnen</button></div>'}
else if(n.action_type==='update_reward'){const a=Number(d.reward_money||100);body+='<div class="mtrw-gains"><span>💵 '+a.toLocaleString('de-DE')+' $ Update-Belohnung</span></div><div class="mtrw-actions">'+(n.resolved_at?'<button class="claimed" type="button" disabled>✓ Bereits beansprucht</button>':'<button class="ok" data-update-reward>🎁 Belohnung abholen</button>')+'</div>'}
else if(n.action_type==='announcement_reward'){const rt=d.reward_type,ra=Number(d.reward_amount||0),labels={money:'💵 {const money=Number(d.reward_money||10000),mat=Number(d.reward_material||500),parts=Number(d.reward_weapon_parts||500);body+='<div class="mtrw-gains"><span>💵 '+money.toLocaleString('de-DE')+' $</span><span>🧱 '+mat.toLocaleString('de-DE')+' Material</span><span>🔩 '+parts.toLocaleString('de-DE')+' Waffenteile</span></div><div class="mtrw-actions">'+(n.resolved_at?'<button class="claimed" type="button" disabled>✓ Bereits beansprucht</button>':'<button class="ok" data-version-reward>🎁 Belohnung abholen</button>')+'</div>'}
else if(n.action_type==='offline_report'){const g=d.gains||{};body+='<div class="mtrw-gains"><span>💵 '+Number(g.money||0).toLocaleString('de-DE')+' $</span><span>🧱 '+Number(g.material||0).toLocaleString('de-DE')+' Material</span><span>🔩 '+Number(g.weapon_parts||0).toLocaleString('de-DE')+' Waffenteile</span><span>⭐ '+Number(g.reputation||0).toLocaleString('de-DE')+' Reputation</span></div>'}
return '<article class="mtrw-n '+(n.read_at?'':'unread')+'" data-id="'+esc(n.id)+'"><div class="mtrw-nt">'+esc(n.title)+'</div><div class="mtrw-nm">'+body+'</div><div class="mtrw-time">'+fmt(n.created_at)+'</div>'+actions+'</article>'}
async function load(){try{const rows=await rpc('mtrw_my_notifications',{p_limit:100})||[];badge.textContent=rows.filter(x=>!x.read_at&&!x.resolved_at).length||'';badge.style.display=badge.textContent?'block':'none';list.innerHTML=rows.length?rows.map(render).join(''):'Keine neuen Nachrichten.';rows.forEach(n=>{const el=list.querySelector('[data-id="'+n.id+'"]');if(!el)return;el.onclick=async e=>{const b=e.target;if(b.matches('[data-ok]'))return action(n,()=>rpc('mtrw_accept_trade',{p_trade_id:n.action_data.trade_id}));if(b.matches('[data-no]'))return action(n,()=>rpc('mtrw_reject_trade',{p_trade_id:n.action_data.trade_id}));if(b.matches('[data-update-reward]')&&!n.resolved_at)return action(n,()=>rpc('mtrw_claim_update_reward',{p_notification_id:n.id}));if(b.matches('[data-ann-reward]')&&!n.resolved_at)return action(n,()=>rpc('mtrw_claim_announcement_reward',{p_notification_id:n.id}));
if(b.matches('[data-version-reward]')&&!n.resolved_at)return action(n,()=>rpc('mtrw_claim_version_7_reward',{p_notification_id:n.id}));if(b.matches('[data-friend]')){await rpc('mtrw_notification_read',{p_id:n.id});try{if(window.mtrwSocialV2)window.mtrwSocialV2();setTimeout(()=>document.getElementById('socialRequestsTab')?.click(),250)}catch(_){}return}if(n.action_type==='dealer'||n.action_type==='weapon_dealer'||n.action_type==='raid'){await rpc('mtrw_notification_read',{p_id:n.id});await centerEvent(n);el.classList.remove('unread');await load();return}await rpc('mtrw_notification_read',{p_id:n.id});el.classList.remove('unread');await load()}})}catch(e){list.innerHTML='<div class="mtrw-n">Mailbox konnte nicht geladen werden.</div>';console.error(e)}}
window.mtrwMailboxReload=load;window.addEventListener('online',load);load();setInterval(load,30000);
};boot()})();
,material:'🧱 Material',weapon_parts:'🔩 Waffenteile',reputation:'⭐ Reputation',hitmen:'🥊 Schläger'};body+='<div class="mtrw-gains"><span>🎁 '+ra.toLocaleString('de-DE')+' '+esc(labels[rt]||rt)+'</span></div><div class="mtrw-actions">'+(n.resolved_at?'<button class="claimed" type="button" disabled>✓ Bereits beansprucht</button>':'<button class="ok" data-ann-reward>🎁 Belohnung abholen</button>')+'</div>'}
else if(n.action_type==='version_reward'){const money=Number(d.reward_money||10000),mat=Number(d.reward_material||500),parts=Number(d.reward_weapon_parts||500);body+='<div class="mtrw-gains"><span>💵 '+money.toLocaleString('de-DE')+' $</span><span>🧱 '+mat.toLocaleString('de-DE')+' Material</span><span>🔩 '+parts.toLocaleString('de-DE')+' Waffenteile</span></div><div class="mtrw-actions">'+(n.resolved_at?'<button class="claimed" type="button" disabled>✓ Bereits beansprucht</button>':'<button class="ok" data-version-reward>🎁 Belohnung abholen</button>')+'</div>'}
else if(n.action_type==='offline_report'){const g=d.gains||{};body+='<div class="mtrw-gains"><span>💵 '+Number(g.money||0).toLocaleString('de-DE')+' $</span><span>🧱 '+Number(g.material||0).toLocaleString('de-DE')+' Material</span><span>🔩 '+Number(g.weapon_parts||0).toLocaleString('de-DE')+' Waffenteile</span><span>⭐ '+Number(g.reputation||0).toLocaleString('de-DE')+' Reputation</span></div>'}
return '<article class="mtrw-n '+(n.read_at?'':'unread')+'" data-id="'+esc(n.id)+'"><div class="mtrw-nt">'+esc(n.title)+'</div><div class="mtrw-nm">'+body+'</div><div class="mtrw-time">'+fmt(n.created_at)+'</div>'+actions+'</article>'}
async function load(){try{const rows=await rpc('mtrw_my_notifications',{p_limit:100})||[];badge.textContent=rows.filter(x=>!x.read_at&&!x.resolved_at).length||'';badge.style.display=badge.textContent?'block':'none';list.innerHTML=rows.length?rows.map(render).join(''):'Keine neuen Nachrichten.';rows.forEach(n=>{const el=list.querySelector('[data-id="'+n.id+'"]');if(!el)return;el.onclick=async e=>{const b=e.target;if(b.matches('[data-ok]'))return action(n,()=>rpc('mtrw_accept_trade',{p_trade_id:n.action_data.trade_id}));if(b.matches('[data-no]'))return action(n,()=>rpc('mtrw_reject_trade',{p_trade_id:n.action_data.trade_id}));if(b.matches('[data-update-reward]')&&!n.resolved_at)return action(n,()=>rpc('mtrw_claim_update_reward',{p_notification_id:n.id}));
if(b.matches('[data-version-reward]')&&!n.resolved_at)return action(n,()=>rpc('mtrw_claim_version_7_reward',{p_notification_id:n.id}));if(b.matches('[data-friend]')){await rpc('mtrw_notification_read',{p_id:n.id});try{if(window.mtrwSocialV2)window.mtrwSocialV2();setTimeout(()=>document.getElementById('socialRequestsTab')?.click(),250)}catch(_){}return}if(n.action_type==='dealer'||n.action_type==='weapon_dealer'||n.action_type==='raid'){await rpc('mtrw_notification_read',{p_id:n.id});await centerEvent(n);el.classList.remove('unread');await load();return}await rpc('mtrw_notification_read',{p_id:n.id});el.classList.remove('unread');await load()}})}catch(e){list.innerHTML='<div class="mtrw-n">Mailbox konnte nicht geladen werden.</div>';console.error(e)}}
window.mtrwMailboxReload=load;window.addEventListener('online',load);load();setInterval(load,30000);
};boot()})();
