/* MAFIVERA – Admin & Moderation */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString('de-DE');
let state=null,selected=null,timer=null,players=[];
async function rpc(name,args={}){const r=await window.db.rpc(name,args);if(r.error)throw r.error;return r.data}
function toast(t,error=false){const x=$('toast');if(!x)return;x.textContent=t;x.className='toast show'+(error?' error':'');setTimeout(()=>x.className='toast',3000)}
function panel(html){const d=$('drawer'),t=$('drawerTitle'),b=$('drawerBody');if(!d||!t||!b)return;t.textContent='Admin-Zentrale';b.innerHTML=html;d.classList.remove('hidden')}
function can(a){return state?.role==='master'||state?.role==='administrator'||state?.role==='moderator'&&['mute','kick','temp_ban'].includes(a)||state?.role==='supporter'&&['mute','kick'].includes(a)}
async function loadState(){try{state=await rpc('mtrw_admin_bootstrap');window.__mtrwAdmin=state;window.__mtrwMuted=!!state.muted;if(state.banned||state.kicked){await window.db.auth.signOut();location.reload();return false}return true}catch(e){return false}}
function addButton(){if(!state?.can_admin)return;let b=$('mtrwAdminButton');if(!b){b=document.createElement('button');b.id='mtrwAdminButton';b.type='button';b.title='Admin-Zentrale';b.innerHTML='<span>🛡️</span><b>ADMIN</b>';b.onclick=openAdmin;document.body.appendChild(b)}b.style.display='flex'}
function removeButton(){const b=$('mtrwAdminButton');if(b)b.remove()}
function renderPlayers(rows){players=Array.isArray(rows)?rows:[];const box=$('adminResults');if(!box)return;box.innerHTML=players.length?players.map(p=>`<button class="admin-player" data-id="${p.user_id}"><span class="admin-avatar">👤</span><span class="admin-player-main"><b>${esc(p.username||'Unbekannt')}</b><small>${esc(p.mafia_name||'Keine Familie')} · Level ${fmt(p.level)} · ${esc(p.admin_role||'player')}</small></span><span class="admin-status">${p.banned?'⛔':p.muted?'🔇':'🟢'}</span></button>`).join(''):'<div class="hint">Keine Spieler gefunden.</div>';box.querySelectorAll('.admin-player').forEach(x=>x.onclick=()=>player(x.dataset.id))}
async function loadPlayers(q=''){try{const rows=await rpc('mtrw_admin_players',{p_search:q});renderPlayers(rows)}catch(e){toast(e.message||'Spielerliste konnte nicht geladen werden',true)}}
async function openAdmin(){if(!state?.can_admin)return;panel('<div class="admin-hero"><div class="admin-icon">🛡️</div><div><b>Admin-Zentrale</b><p>Rolle: '+esc(state.role)+'</p></div></div><div class="admin-search"><input id="adminSearch" placeholder="Spieler oder Mafianame suchen …" autocomplete="off"><button id="adminSearchBtn" class="action primary">🔎 Suchen</button></div><div class="admin-list-head"><h3>Spielerliste</h3><span id="adminCount" class="hint">Lade …</span></div><div id="adminResults" class="list"><div class="hint">Spielerliste wird geladen …</div></div>'+((state.role==='master')?'<div class="admin-manage"><h3>Admin-Rechte</h3><p class="hint">Nur der Master kann Rollen vergeben oder entziehen.</p></div>':'') );
$('adminSearchBtn').onclick=()=>loadPlayers(($('adminSearch')?.value||'').trim());
$('adminSearch').oninput=()=>{clearTimeout(openAdmin.searchTimer);openAdmin.searchTimer=setTimeout(()=>loadPlayers(($('adminSearch')?.value||'').trim()),180)};
$('adminSearch').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();loadPlayers(($('adminSearch')?.value||'').trim())}};
await loadPlayers('');
}
async function player(id){try{const p=players.find(x=>x.user_id===id);if(!p){const rows=await rpc('mtrw_admin_players',{p_search:''});renderPlayers(rows);const fresh=players.find(x=>x.user_id===id);if(!fresh){toast('Spieler nicht gefunden',true);return}return player(id)}selected=p;const controls=[];if(can('mute'))controls.push('<button class="action" data-san="mute">🔇 Mute</button>');if(can('kick'))controls.push('<button class="action" data-san="kick">👢 Kick</button>');if(can('temp_ban'))controls.push('<button class="action" data-san="temp_ban">⏱️ Temp-Bann</button>');if(can('perm_ban'))controls.push('<button class="action danger" data-san="perm_ban">⛔ Dauerbann</button>');let role='';if(state.role==='master')role=`<div class="admin-role-box"><label>Admin-Rolle</label><select id="adminRole"><option value="player">Spieler</option><option value="supporter">Supporter</option><option value="moderator">Moderator</option><option value="administrator">Administrator</option></select><button id="saveRole" class="action primary">🛡️ Rolle speichern</button></div>`;panel(`<div class="admin-profile"><div class="admin-avatar big">👤</div><div><h2>${esc(p.username||'Unbekannt')}</h2><small>${esc(p.mafia_name||'Keine Familie')} · ${esc(p.admin_role||'player')}</small></div></div><div class="statgrid"><div><b>${fmt(p.level)}</b><small>Level</small></div><div><b>${fmt(p.xp)}</b><small>XP</small></div><div><b>${fmt(p.reputation)}</b><small>Ruf</small></div><div><b>${fmt(p.money)} $</b><small>Geld</small></div><div><b>${fmt(p.material)}</b><small>Material</small></div><div><b>${fmt(p.hitmen)}</b><small>Schläger</small></div></div><div class="hint">Status: ${p.banned?'⛔ Gebannt':p.muted?'🔇 Gemutet':'🟢 Aktiv'}</div><h3>Sanktionen</h3><div class="admin-actions">${controls.join('')||'<div class="hint">Keine Sanktion-Rechte für diese Rolle.</div>'}</div>${role}`);const sel=$('adminRole');if(sel)sel.value=p.admin_role||'player';$('saveRole')?.addEventListener('click',async()=>{try{await rpc('mtrw_admin_set_role',{p_user_id:id,p_role:$('adminRole').value});toast('Admin-Rolle gespeichert.');await openAdmin()}catch(e){toast(e.message||'Rolle konnte nicht geändert werden',true)}});document.querySelectorAll('[data-san]').forEach(x=>x.onclick=()=>sanction(x.dataset.san,id));}catch(e){toast(e.message||'Spieler konnte nicht geladen werden',true)}}
async function sanction(type,id){if(!can(type))return;let minutes=null;if(type==='mute'||type==='temp_ban'){minutes=Number(prompt(type==='mute'?'Mute-Dauer in Minuten:':'Temp-Bann-Dauer in Minuten:','60'));if(!Number.isFinite(minutes)||minutes<1)return}const reason=prompt('Grund für die Sanktion:','Verstoß gegen die Spielregeln')??'';try{await rpc('mtrw_admin_sanction',{p_user_id:id,p_type:type,p_reason:reason,p_minutes:minutes});toast(type==='perm_ban'?'Dauerbann ausgesprochen.':type==='temp_ban'?'Temp-Bann ausgesprochen.':type==='kick'?'Spieler gekickt.':'Mute ausgesprochen.');const rows=await rpc('mtrw_admin_players',{p_search:''});renderPlayers(rows);await player(id)}catch(e){toast(e.message||'Sanktion fehlgeschlagen',true)}}
async function boot(){if(!window.db)return;const ok=await loadState();if(!ok)return;if(state?.can_admin)addButton();else removeButton();if(timer)clearInterval(timer);timer=setInterval(async()=>{const ok=await loadState();if(ok&&state?.can_admin)addButton();else if(ok)removeButton()},15000)}
const style=document.createElement('style');style.textContent=`#mtrwAdminButton{position:fixed!important;right:10px!important;bottom:82px!important;z-index:99999!important;display:none;align-items:center;justify-content:center;gap:7px;min-width:82px;height:52px;padding:0 13px;border:2px solid #ff4b4b;border-radius:14px;background:linear-gradient(180deg,#b51f2a,#7c1018);color:#fff;box-shadow:0 8px 24px #000b,0 0 12px #ff303066;cursor:pointer;font-size:12px;font-weight:900}#mtrwAdminButton span{font-size:22px}#mtrwAdminButton b{font-size:12px;letter-spacing:.8px}.admin-hero{display:flex;align-items:center;gap:14px;padding:14px;background:#171d27;border:1px solid #3c4a59;border-radius:16px}.admin-icon{font-size:34px}.admin-hero b{font-size:20px}.admin-hero p{margin:4px 0 0;color:#aeb7c3;font-size:13px}.admin-search{display:grid;grid-template-columns:1fr auto;gap:8px;margin:14px 0}.admin-search input{width:100%;height:50px;border:1px solid #394653;border-radius:11px;background:#0b1016;color:#fff;padding:0 13px;font-size:17px}.admin-search .action{width:auto!important;margin:0!important}.admin-list-head{display:flex;align-items:center;justify-content:space-between;margin:4px 2px 8px}.admin-list-head h3{margin:0}.admin-player{width:100%;display:flex;align-items:center;gap:11px;padding:12px;background:#171d27;color:#fff;border:1px solid #293340;border-radius:13px;text-align:left;margin-bottom:6px}.admin-avatar{width:44px;height:44px;min-width:44px;border-radius:50%;display:grid;place-items:center;background:#121a24;border:1px solid #40505f;font-size:22px}.admin-avatar.big{width:62px;height:62px;min-width:62px;font-size:30px}.admin-player-main{flex:1;min-width:0}.admin-player-main b{display:block;font-size:16px}.admin-player-main small{display:block;color:#8f9aa8;margin-top:3px;font-size:12px}.admin-status{font-size:18px}.admin-profile{display:flex;align-items:center;gap:14px;padding:6px 0 14px}.admin-profile h2{margin:0 0 4px}.admin-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.admin-role-box{margin-top:16px;padding:14px;background:#171d27;border:1px solid #303b48;border-radius:15px}.admin-role-box label{display:block;font-weight:800;margin-bottom:7px}.admin-role-box select{width:100%;height:46px;background:#0b1016;color:#fff;border:1px solid #394653;border-radius:10px;padding:0 10px;font-size:16px}.admin-role-box .action{margin-top:8px}.mf-drawer .statgrid{grid-template-columns:repeat(3,1fr)}@media(max-width:600px){#mtrwAdminButton{right:8px!important;bottom:86px!important;min-width:88px;height:54px}.admin-actions{grid-template-columns:1fr}.mf-drawer .statgrid{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(style);
let tries=0;const wait=setInterval(()=>{if(window.db){clearInterval(wait);boot()}else if(++tries>120)clearInterval(wait)},500);
})();