/* MAFIVERA – Rechtstexte, Nutzungsbedingungen und Zustimmungsgate
   Version: 2026-09-17-v1
   Hinweis: Die Texte sind auf einen deutschen, kostenlosen GPS-Spielbetrieb zugeschnitten.
*/
(()=>{'use strict';
const VERSION='2026-09-17-v1';
let waiting=null;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const legal={
 terms:`<h2>Nutzungsbedingungen</h2><p><b>Stand: 17.09.2026 · Version ${VERSION}</b></p>
<h3>1. Anbieter und Geltungsbereich</h3><p>Diese Nutzungsbedingungen gelten für die Nutzung von MAFIVERA – The Real World (nachfolgend „MAFIVERA“). Anbieter ist Paul Rühlemann, Carl-Zeiss-Straße 27, 99097 Erfurt, Deutschland, E-Mail: mafiatherealworld@gmail.com.</p>
<h3>2. Gegenstand</h3><p>MAFIVERA ist ein kostenloses, webbasiertes GPS-Spiel. Die Spielwelt, Funktionen, Karten, Regeln, Balancing-Werte, virtuellen Gegenstände, Spielwährungen, Ranglisten und sonstigen Inhalte sind rein virtuell und begründen keinen Anspruch auf einen bestimmten Spielstand, eine bestimmte Verfügbarkeit oder einen bestimmten Funktionsumfang.</p>
<h3>3. Kein Echtgeldwert</h3><p>Virtuelles Geld, virtuelle Gegenstände, Gebiete, Ressourcen, Drogen, Einheiten, Reputation, Erfahrungspunkte und sonstige Spielwerte haben keinen realen Geldwert. Sie sind nicht auszahlbar, nicht übertragbar außerhalb des Spiels und dürfen nicht gegen echtes Geld gehandelt werden. MAFIVERA ist kein Glücksspielangebot und gewährt keinen Gewinnanspruch.</p>
<h3>4. Konto</h3><p>Ein Konto darf nur für die eigene Person erstellt werden. Zugangsdaten sind geheim zu halten. Mehrfachkonten, Identitätstäuschung, Account-Sharing, automatisierte Konten und die Umgehung von Sperren sind untersagt.</p>
<h3>5. Fair Play und technische Sicherheit</h3><p>Verboten sind insbesondere Cheats, Bots, Exploits, Manipulation von Client- oder Netzwerkdaten, unzulässige Automatisierung, Ausnutzen von Sicherheitslücken, Reverse Engineering mit dem Ziel der Manipulation sowie Angriffe auf Server, Datenbanken oder andere Spieler.</p>
<h3>6. Spielregeln und Sanktionen</h3><p>Der Anbieter darf bei Regelverstößen verhältnismäßige Maßnahmen ergreifen, insbesondere Verwarnung, Mute, Kick, zeitweilige Sperre oder dauerhafte Sperre. Bei schwerwiegenden oder wiederholten Verstößen kann eine sofortige Sperre erfolgen. Maßnahmen dürfen insbesondere zum Schutz anderer Nutzer, des Dienstes und der technischen Infrastruktur getroffen werden. Zwingende gesetzliche Rechte bleiben unberührt.</p>
<h3>7. Verfügbarkeit und Änderungen</h3><p>MAFIVERA wird im Rahmen der technischen Möglichkeiten betrieben. Wartungen, Updates, Störungen, Sicherheitsmaßnahmen oder Änderungen können die Verfügbarkeit beeinflussen. Der Anbieter darf Funktionen, Balancing und Spielinhalte ändern, wenn dies für Betrieb, Sicherheit, Weiterentwicklung oder Fehlerbehebung erforderlich ist. Eine Garantie auf dauerhafte Verfügbarkeit besteht nicht.</p>
<h3>8. Nutzerinhalte und Verhalten</h3><p>Rechtswidrige, beleidigende, bedrohen­de, diskriminierende, pornografische, extremistische, betrügerische oder sonst unzulässige Inhalte sowie personenbezogene Daten anderer Personen dürfen nicht über MAFIVERA verbreitet werden. Nutzer sind für eigene Inhalte und Handlungen verantwortlich.</p>
<h3>9. Haftung</h3><p>Es gelten die gesetzlichen Haftungsregeln. Eine Haftungsbeschränkung gilt insbesondere nicht bei Vorsatz, grober Fahrlässigkeit, Verletzung von Leben, Körper oder Gesundheit sowie in sonstigen Fällen zwingender gesetzlicher Haftung. Im Übrigen wird nur im gesetzlich zulässigen Umfang gehaftet.</p>
<h3>10. Kündigung und Sperre</h3><p>Das Nutzungsverhältnis kann von dir jederzeit durch Beendigung der Nutzung beendet werden. Der Anbieter kann das Nutzungsverhältnis aus wichtigem Grund beenden oder ein Konto sperren, insbesondere bei erheblichen oder wiederholten Regelverstößen. Gesetzliche Rechte bleiben unberührt.</p>
<h3>11. Minderjährige</h3><p>MAFIVERA ist wegen GPS-, Kontakt-, Kommunikations- und kriminellen Spielinhalten ausschließlich für Personen ab 18 Jahren vorgesehen. Mit der Registrierung bestätigst du, mindestens 18 Jahre alt zu sein.</p>
<h3>12. Schlussbestimmungen</h3><p>Es gilt deutsches Recht, soweit dem keine zwingenden Verbraucherschutzvorschriften entgegenstehen. Sollten einzelne Bestimmungen unwirksam sein, bleibt die Wirksamkeit der übrigen Bestimmungen unberührt; an die Stelle unwirksamer Bestimmungen tritt die gesetzliche Regelung.</p>`,
 privacy:`<h2>Datenschutzerklärung</h2><p><b>Stand: 17.09.2026 · Version ${VERSION}</b></p>
<h3>1. Verantwortlicher</h3><p>Paul Rühlemann, Carl-Zeiss-Straße 27, 99097 Erfurt, Deutschland, E-Mail: mafiatherealworld@gmail.com.</p>
<h3>2. Verarbeitete Daten</h3><p>MAFIVERA verarbeitet insbesondere E-Mail-Adresse, Konto-ID, Nutzername, Authentifizierungsdaten und spielbezogene Daten. Für GPS-Funktionen können Standortkoordinaten, Genauigkeit und Zeitpunkte der Standortaktualisierung verarbeitet werden. Für Sicherheit und Administration können technische Protokoll- und Sanktionsdaten verarbeitet werden.</p>
<h3>3. Zwecke und Rechtsgrundlagen</h3><p>Die Daten werden zur Kontoerstellung und Anmeldung, zur Bereitstellung des Spiels, zur Durchführung angeforderter Spielfunktionen, zur Missbrauchs- und Betrugsprävention, zur technischen Sicherheit und zur Durchsetzung der Spielregeln verarbeitet. Vertragsbezogene Verarbeitung erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, soweit die Voraussetzungen vorliegen; gesetzliche Pflichten auf Art. 6 Abs. 1 lit. c DSGVO; berechtigte Interessen an Sicherheit und Missbrauchsschutz auf Art. 6 Abs. 1 lit. f DSGVO. Eine gesonderte Einwilligung wird dort eingeholt, wo sie erforderlich ist.</p>
<h3>4. GPS und Standort</h3><p>GPS wird nur nach deiner ausdrücklichen Zustimmung für die ortsabhängigen Spielfunktionen verwendet. Die Zustimmung kann über die Geräte- bzw. Browserberechtigungen entzogen werden. Ohne Standortzugriff sind GPS-Funktionen nicht oder nur eingeschränkt nutzbar. Die Standortverarbeitung dient insbesondere der Positionierung auf der Spielkarte, Entfernungsberechnung und Anzeige von Spielern oder spielbezogenen Orten im vorgesehenen Radius.</p>
<h3>5. Empfänger und Dienstleister</h3><p>MAFIVERA nutzt GitHub Pages zur Bereitstellung der Webanwendung und Supabase für Authentifizierung und Spieldaten. Dabei können die für diese Dienste erforderlichen Daten verarbeitet werden. Es gelten zusätzlich die Datenschutzinformationen der jeweiligen Anbieter.</p>
<h3>6. Speicherdauer</h3><p>Daten werden nur so lange gespeichert, wie dies für die jeweiligen Zwecke, gesetzliche Aufbewahrungspflichten oder die Abwehr bzw. Durchsetzung rechtlicher Ansprüche erforderlich ist. Spiel- und Sanktionsdaten können zur Missbrauchsprävention angemessen vorgehalten werden.</p>
<h3>7. Rechte</h3><p>Du hast im Rahmen der gesetzlichen Voraussetzungen insbesondere Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit sowie das Recht, Einwilligungen mit Wirkung für die Zukunft zu widerrufen. Außerdem besteht ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde.</p>
<h3>8. Kontakt</h3><p>Datenschutzanfragen: mafiatherealworld@gmail.com.</p>`,
 community:`<h2>Community- und Spielregeln</h2><p><b>Stand: 17.09.2026 · Version ${VERSION}</b></p><p>1. Respektvoller Umgang. Keine Belästigung, Drohungen, Diskriminierung, Hassrede oder gezielte Schikanierung.</p><p>2. Kein Cheating, Botting, Exploiting oder Manipulieren von Spiel- und Standortdaten.</p><p>3. Keine Weitergabe fremder personenbezogener Daten, GPS-Daten oder Zugangsdaten.</p><p>4. Keine realen Drohungen oder Aufrufe zu realen Straftaten. Kriminelle Handlungen innerhalb des Spiels sind ausschließlich virtuelle Spielmechaniken.</p><p>5. Keine Umgehung von Sperren oder Adminmaßnahmen.</p><p>6. Werbung, Spam, Betrug, Phishing und schädliche Links sind verboten.</p><p>7. Meldungen an das Team müssen wahrheitsgemäß und nachvollziehbar sein.</p><p>8. Adminentscheidungen dürfen nicht durch Beleidigungen, Drohungen oder Massenmeldungen beeinflusst werden. Ein sachlicher Einspruch über den vorgesehenen Kontaktweg bleibt möglich.</p><p>9. Verstöße können nach Schwere und Wiederholung zu Mute, Kick, zeitweiliger oder dauerhafter Sperre führen.</p>`,
 imprint:`<h2>Impressum</h2><p><b>Angaben gemäß § 5 DDG</b></p><p>Paul Rühlemann<br>Carl-Zeiss-Straße 27<br>99097 Erfurt<br>Deutschland</p><p>E-Mail: <a href="mailto:mafiatherealworld@gmail.com">mafiatherealworld@gmail.com</a></p><p>Projekt: MAFIVERA – The Real World</p><p>Verantwortlich für den Inhalt nach den allgemeinen gesetzlichen Vorschriften: Paul Rühlemann, Anschrift wie oben.</p>`
};
function style(){if(document.getElementById('mtrwLegalStyle'))return;const s=document.createElement('style');s.id='mtrwLegalStyle';s.textContent=`#mtrwLegalGate{position:fixed;inset:0;z-index:20000;background:#05080df7;color:#fff;display:flex;align-items:center;justify-content:center;padding:14px;font-family:system-ui,sans-serif}#mtrwLegalCard{width:min(920px,100%);max-height:94vh;overflow:auto;background:#0c131c;border:1px solid #3c4a58;border-radius:20px;padding:20px;box-shadow:0 20px 70px #000b}#mtrwLegalCard h1{font-size:28px;margin:0 0 6px}#mtrwLegalCard .intro{color:#d7dde5;font-size:15px;line-height:1.5;margin-bottom:16px}.mtrwLegalChecks{display:grid;gap:10px;margin:16px 0}.mtrwLegalCheck{display:flex;gap:10px;align-items:flex-start;background:#111b26;border:1px solid #2e3b49;border-radius:12px;padding:12px;font-size:15px;line-height:1.45}.mtrwLegalCheck input{margin-top:4px;width:19px;height:19px;accent-color:#d6ad2d}.mtrwLegalLinks{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0 16px}.mtrwLegalLinks button{border:1px solid #536170;background:#182330;color:#fff;border-radius:10px;padding:9px 11px;font-weight:700}.mtrwLegalSubmit{width:100%;padding:14px;border:0;border-radius:12px;background:#d6ad2d;color:#111;font-size:17px;font-weight:900}.mtrwLegalSubmit:disabled{opacity:.45}.mtrwLegalError{min-height:22px;color:#ff8c8c;font-size:14px;margin-top:8px}.mtrwLegalModal{position:fixed;inset:0;z-index:21000;background:#000c;display:flex;align-items:center;justify-content:center;padding:14px}.mtrwLegalDoc{width:min(900px,100%);max-height:90vh;overflow:auto;background:#0c131c;border:1px solid #465464;border-radius:18px;padding:22px;color:#fff;line-height:1.55}.mtrwLegalDoc h2{font-size:27px}.mtrwLegalDoc h3{font-size:18px;margin-top:20px}.mtrwLegalDoc a{color:#e4c44d}.mtrwLegalClose{float:right;border:1px solid #526171;background:#17212c;color:#fff;border-radius:50%;width:42px;height:42px;font-size:25px}`;document.head.appendChild(s)}
function doc(title,html){style();const w=document.createElement('div');w.className='mtrwLegalModal';w.innerHTML=`<div class="mtrwLegalDoc"><button class="mtrwLegalClose">×</button>${html}</div>`;document.body.appendChild(w);w.querySelector('button').onclick=()=>w.remove();w.onclick=e=>{if(e.target===w)w.remove()}}
function gate(){style();return new Promise(resolve=>{const g=document.createElement('div');g.id='mtrwLegalGate';g.innerHTML=`<div id="mtrwLegalCard"><h1>⚖️ Rechtliche Zustimmung erforderlich</h1><div class="intro">Bevor du MAFIVERA nutzt, musst du die aktuellen Nutzungsbedingungen und Community-Regeln akzeptieren und die Datenschutzerklärung zur Kenntnis nehmen. Für die GPS-Spielmechanik ist eine gesonderte Zustimmung zur Standortverarbeitung erforderlich. MAFIVERA ist ausschließlich für Personen ab 18 Jahren vorgesehen.</div><div class="mtrwLegalLinks"><button data-doc="terms">Nutzungsbedingungen lesen</button><button data-doc="privacy">Datenschutzerklärung lesen</button><button data-doc="community">Community-Regeln lesen</button><button data-doc="imprint">Impressum</button></div><div class="mtrwLegalChecks"><label class="mtrwLegalCheck"><input id="legalAge" type="checkbox"><span>Ich bestätige, dass ich mindestens 18 Jahre alt bin.</span></label><label class="mtrwLegalCheck"><input id="legalTerms" type="checkbox"><span>Ich akzeptiere die <b>Nutzungsbedingungen</b> und die darin enthaltenen Spiel- und Sanktionsregeln.</span></label><label class="mtrwLegalCheck"><input id="legalCommunity" type="checkbox"><span>Ich akzeptiere die <b>Community- und Spielregeln</b>.</span></label><label class="mtrwLegalCheck"><input id="legalPrivacy" type="checkbox"><span>Ich habe die <b>Datenschutzerklärung</b> gelesen und zur Kenntnis genommen.</span></label><label class="mtrwLegalCheck"><input id="legalGps" type="checkbox"><span>Ich willige ausdrücklich ein, dass MAFIVERA meinen Gerätestandort für die beschriebenen GPS-Spielmechaniken verarbeitet. Mir ist bekannt, dass ich diese Einwilligung mit Wirkung für die Zukunft widerrufen kann.</span></label></div><button class="mtrwLegalSubmit" id="legalAccept" disabled>Rechtliche Zustimmung abgeben und Spiel starten</button><div class="mtrwLegalError" id="legalError"></div></div>`;document.body.appendChild(g);const ids=['legalAge','legalTerms','legalCommunity','legalPrivacy','legalGps'],btn=g.querySelector('#legalAccept');const check=()=>{btn.disabled=!ids.every(id=>g.querySelector('#'+id).checked)};ids.forEach(id=>g.querySelector('#'+id).addEventListener('change',check));g.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>doc(b.textContent,legal[b.dataset.doc]));btn.onclick=async()=>{btn.disabled=true;g.querySelector('#legalError').textContent='Speichere Zustimmung…';try{const r=await window.db.rpc('mtrw_record_legal_acceptance',{p_legal_version:VERSION,p_terms:true,p_privacy_ack:true,p_community_rules:true,p_gps_consent:true,p_user_agent:navigator.userAgent});if(r.error)throw r.error;g.remove();resolve(true)}catch(e){g.querySelector('#legalError').textContent=e.message||'Zustimmung konnte nicht gespeichert werden.';btn.disabled=false}}})}
async function hasAcceptance(){try{const r=await window.db.rpc('mtrw_has_current_legal_acceptance');return !r.error&&r.data===true}catch(e){return false}}
window.__mtrwLegalReady=async function(){if(!window.db)return false;if(await hasAcceptance())return true;if(waiting)return waiting;waiting=gate().finally(()=>{waiting=null});return waiting};
window.__mtrwLegalDocs=legal;
// Für die Registrierung: Die Zustimmung wird vor dem Absenden verlangt.
document.addEventListener('DOMContentLoaded',()=>{const f=document.getElementById('authForm');if(!f)return;f.addEventListener('submit',e=>{const u=document.getElementById('usernameField');if(!u||u.classList.contains('hidden'))return;if(!window.__mtrwPreLegalAccepted){e.preventDefault();e.stopImmediatePropagation();window.__mtrwPreLegalAccepted=true;gate().then(()=>{f.requestSubmit()}).catch(()=>{window.__mtrwPreLegalAccepted=false})}},true)});
})();