/* MAFIVERA – central version/update checker */
(()=>{'use strict';
if(window.__mtrwUpdateLoaded)return;window.__mtrwUpdateLoaded=true;
const CURRENT='6.1.1';
const VERSION_URL='./version.json';
let checking=false;
function css(){if(document.getElementById('mtrwUpdateStyle'))return;const s=document.createElement('style');s.id='mtrwUpdateStyle';s.textContent='.mtrw-update-overlay{position:fixed;inset:0;z-index:300000;display:none;align-items:center;justify-content:center;background:#000b;backdrop-filter:blur(7px);padding:20px}.mtrw-update-overlay.show{display:flex}.mtrw-update-card{width:min(92vw,390px);padding:26px 22px;text-align:center;color:#fff;border:1px solid #d6a63a;border-radius:22px;background:linear-gradient(180deg,#202630,#0c1016);box-shadow:0 25px 80px #000e}.mtrw-update-icon{font-size:54px;margin-bottom:8px}.mtrw-update-card h2{margin:0 0 8px;font-size:23px}.mtrw-update-card p{margin:8px 0;color:#bfc7d1;line-height:1.45}.mtrw-update-version{color:#ffd66b;font-weight:900;margin:12px 0}.mtrw-update-btn{width:100%;margin-top:12px;padding:14px 18px;border:1px solid #e2b64e;border-radius:13px;background:linear-gradient(180deg,#e1b341,#9f7118);color:#111;font:900 16px system-ui;cursor:pointer}.mtrw-update-btn:disabled{opacity:.65;cursor:wait}.mtrw-update-status{min-height:20px;margin-top:10px;font-size:12px;color:#aeb7c3}';document.head.appendChild(s)}
function overlay(){let o=document.getElementById('mtrwUpdateOverlay');if(o)return o;o=document.createElement('div');o.id='mtrwUpdateOverlay';o.className='mtrw-update-overlay';o.innerHTML='<div class="mtrw-update-card"><div class="mtrw-update-icon">🔄</div><h2>Neue Version verfügbar</h2><p class="mtrw-update-message">Eine neue Version von MAFIVERA ist verfügbar.</p><div class="mtrw-update-version"></div><button class="mtrw-update-btn" type="button">UPDATE</button><div class="mtrw-update-status"></div></div>';document.body.appendChild(o);return o}
function cmp(a,b){const pa=String(a).replace(/^v/i,'').split('.').map(x=>parseInt(x,10)||0),pb=String(b).replace(/^v/i,'').split('.').map(x=>parseInt(x,10)||0);for(let i=0;i<3;i++){if((pa[i]||0)!==(pb[i]||0))return(pa[i]||0)-(pb[i]||0)}return 0}
async function check(){if(checking)return;checking=true;try{const r=await fetch(VERSION_URL+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('version_check_failed');const v=await r.json();if(v.version&&cmp(CURRENT,v.version)<0)show(v)}catch(e){}finally{checking=false}}
function show(v){css();const o=overlay();o.querySelector('.mtrw-update-message').textContent=v.message||'Eine neue Version von MAFIVERA ist verfügbar.';o.querySelector('.mtrw-update-version').textContent='Version '+v.version;o.classList.add('show');const b=o.querySelector('.mtrw-update-btn'),st=o.querySelector('.mtrw-update-status');b.disabled=false;b.onclick=async()=>{b.disabled=true;st.textContent='Update wird geladen …';try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.update().catch(()=>{})))}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(k=>String(k).startsWith('mtrw-')).map(k=>caches.delete(k)))}}catch(e){}st.textContent='MAFIVERA wird aktualisiert …';setTimeout(()=>location.replace(location.pathname+'?mtrw_update='+Date.now()+location.hash),350)}}
window.mtrwCheckForUpdate=check;window.mtrwCurrentVersion=CURRENT;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(check,2500));else setTimeout(check,2500);
setInterval(check,10*60*1000);
})();