/* MAFIVERA — offline-first world cache + reconnect sync */
(()=>{'use strict';
if(window.MAFIVERA_OFFLINE_WORLD)return;window.MAFIVERA_OFFLINE_WORLD=true;
const CACHE='mafivera:v1:world-cache',QUEUE='mafivera:v1:offline-queue';
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch(e){return d}};
const put=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const toast=t=>{const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._offlineT);e._offlineT=setTimeout(()=>e.classList.remove('show'),2800)};
const status=()=>{document.documentElement.dataset.network=navigator.onLine?'online':'offline';window.dispatchEvent(new CustomEvent('mafivera:network',{detail:{online:navigator.onLine}}))};
window.MAFIVERA_OFFLINE_CACHE={save(rows){if(Array.isArray(rows))put(CACHE,{savedAt:Date.now(),rows})},load(){return get(CACHE,{savedAt:0,rows:[]})}};
const queue=item=>{const q=get(QUEUE,[]);q.push({...item,queuedAt:Date.now()});put(QUEUE,q);return q.length};
window.MAFIVERA_OFFLINE_QUEUE={add:queue,get:()=>get(QUEUE,[]),clear:()=>put(QUEUE,[])};
const cacheWorld=async()=>{if(!navigator.onLine||!window.db)return;try{const r=await window.db.from('world_territories').select('zone_key,owner_id,center_lat,center_lng,defense_points,garrison,building_type,building_defense,support_bonus,claimed_at,updated_at');if(!r.error)window.MAFIVERA_OFFLINE_CACHE.save(r.data||[])}catch(e){}};
const sync=async()=>{if(!navigator.onLine||!window.db)return;const q=get(QUEUE,[]),keep=[];for(const x of q){try{if(x.type==='defense'){const r=await window.db.rpc('update_world_defense',x.args);if(r.error)throw r.error}else if(x.type==='territory'){const r=await window.db.rpc('sync_world_territory',x.args);if(r.error)throw r.error}else keep.push(x)}catch(e){keep.push(x)}}put(QUEUE,keep);await cacheWorld();if(q.length&&!keep.length)toast('☁️ Offline-Änderungen synchronisiert.');else if(keep.length)toast(`☁️ ${keep.length} Änderung(en) warten auf Verbindung.`);window.dispatchEvent(new Event('mafivera:worldRefresh'))};
const offlineLayer=()=>{const map=window.mtrwMap;if(!map||!window.L)return;const s=(()=>{try{const k=Object.keys(localStorage).find(x=>x.startsWith('mafivera:v1:save:'));return k?JSON.parse(localStorage.getItem(k)||'{}'):{} }catch(e){return{}}})();const o=s.worldOrigin;if(!o)return;let layer=window.__mtrwOfflineWorldLayer;if(!layer)layer=L.layerGroup().addTo(map),window.__mtrwOfflineWorldLayer=layer;layer.clearLayers();const cached=get(CACHE,{rows:[]}).rows||[],center=window.mtrwLiveGps||s.gps||o,GL=.0018,GW=.0025,pr=Math.floor((center.lat-o.lat)/GL),pc=Math.floor((center.lng-o.lng)/GW);cached.forEach(r=>{const rr=Math.floor((r.center_lat-o.lat)/GL),cc=Math.floor((r.center_lng-o.lng)/GW);if(Math.max(Math.abs(rr-pr),Math.abs(cc-pc))>10)return;const mine=r.owner_id===window.__mtrwCurrentUserId,color=mine?'#3b82f6':'#ef4444',rect=L.rectangle([[r.center_lat-GL/2,r.center_lng-GW/2],[r.center_lat+GL/2,r.center_lng+GW/2]],{color,weight:3,fillColor:color,fillOpacity:.30,interactive:false});rect.__offlineZoneKey=r.zone_key;layer.addLayer(rect);if(r.building_type){const names=window.MAFIVERA_ALL_BUILDINGS||window.MAFIVERA_BUILDINGS||{};const d=names[r.building_type]||{name:r.building_type,icon:'🏗️'};layer.addLayer(L.marker([r.center_lat,r.center_lng],{interactive:false,zIndexOffset:700,icon:L.divIcon({className:'building-marker synced-building-marker',html:`<div class="mtrw-building-pin"><span>${d.icon}</span><b>${d.name}</b></div>`,iconSize:[96,52],iconAnchor:[48,26]})}))}})};
const refresh=()=>{if(navigator.onLine){offlineLayer();setTimeout(()=>{const l=window.__mtrwOfflineWorldLayer;if(l)l.clearLayers()},1200)}else offlineLayer()};
const wait=()=>{if(!window.db||!window.mtrwMap)return setTimeout(wait,500);window.db.auth.getSession().then(x=>window.__mtrwCurrentUserId=x.data?.session?.user?.id||null);cacheWorld();refresh();window.addEventListener('offline',()=>{refresh()});window.addEventListener('online',()=>{sync();setTimeout(refresh,900)});window.addEventListener('mafivera:worldRefresh',refresh);window.addEventListener('mafivera:territoryChanged',refresh);window.mtrwMap.on('moveend zoomend',refresh);setInterval(()=>{if(navigator.onLine)cacheWorld()},30000);setInterval(()=>{if(navigator.onLine)sync()},10000)};wait();
window.addEventListener('offline',()=>{status();toast('📴 Offline-Modus: letzter Weltstand bleibt sichtbar.')});window.addEventListener('online',()=>{status();toast('🌐 Wieder online · synchronisiere Welt…')});status();
})();
