/* MTRW v0.7 - Real-world OSM claimable areas. */
(async()=>{
  if(!window.db||!window.map)return;
  const map=window.map,oldGrid=window.gridLayer;if(oldGrid)oldGrid.clearLayers();
  const placeLayer=L.layerGroup().addTo(map);let places=[],selectedPlace=null,lastLoad=0,loading=false;
  const state=()=>window.getMtrwState?window.getMtrwState():{};
  const OVERPASS='https://overpass-api.de/api/interpreter';
  const typeFor=t=>t==='city'||t==='town'?'Stadt':t==='village'||t==='hamlet'?'Siedlung':t==='suburb'||t==='neighbourhood'||t==='quarter'?'Stadtteil':t==='building'?'Grundstück':t==='residential'?'Wohngebiet':t==='industrial'?'Industriegebiet':'Gebiet';
  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function centerOf(e){if(e.lat&&e.lon)return[e.lat,e.lon];if(e.center)return[e.center.lat,e.center.lon];if(e.geometry?.length){let a=e.geometry.reduce((x,p)=>[x[0]+p.lat,x[1]+p.lon],[0,0]);return[a[0]/e.geometry.length,a[1]/e.geometry.length]}return null}
  function eligible(e){const t=e.tags||{};return!!(t.name||t.place||t.building||t.landuse==='residential'||t.landuse==='industrial')}
  function areaKind(e){const t=e.tags||{};return t.place||t.building||t.landuse||'area'}
  async function fetchPlaces(lat,lng){if(loading||Date.now()-lastLoad<5000)return;loading=true;lastLoad=Date.now();const d=.008,s=lat-d,w=lng-d,n=lat+d,e=lng+d,q=`[out:json][timeout:25];(way[building](${s},${w},${n},${e});way[landuse~"^(residential|industrial)$"](${s},${w},${n},${e});way[place~"^(neighbourhood|suburb|quarter|village|hamlet|town|city)$"](${s},${w},${n},${e});relation[place~"^(neighbourhood|suburb|quarter|village|hamlet|town|city)$"](${s},${w},${n},${e});node[place~"^(neighbourhood|suburb|quarter|village|hamlet|town|city)$"](${s},${w},${n},${e}););out center geom;`;try{const r=await fetch(OVERPASS,{method:'POST',body:'data='+encodeURIComponent(q)});if(!r.ok)throw Error();const j=await r.json();places=(j.elements||[]).filter(eligible).map(x=>({id:`${x.type}/${x.id}`,osmType:x.type,osmId:x.id,name:x.tags?.name||typeFor(areaKind(x)),kind:areaKind(x),kindLabel:typeFor(areaKind(x)),center:centerOf(x),geometry:x.geometry||null,tags:x.tags||{}})).filter(x=>x.center);drawPlaces();selectAt(lat,lng)}catch{const st=document.getElementById('status');if(st)st.textContent='Kartendaten konnten gerade nicht geladen werden.'}finally{loading=false}}
  function color(p,owned){return owned?'#d1a72c':p.kind==='building'?'#5b83b5':p.kind==='city'||p.kind==='town'?'#a85b9c':'#777'}
  function drawPlaces(){placeLayer.clearLayers();const owned=new Set((state().territories||[]).map(t=>t.place_id||t.zone_key));for(const p of places){const own=owned.has(p.id);let layer;if(p.geometry?.length>=3)layer=L.polygon(p.geometry.map(x=>[x.lat,x.lon]),{color:color(p,own),weight:own?3:1,fillColor:color(p,own),fillOpacity:own?.28:.08});else layer=L.circleMarker(p.center,{radius:p.kind==='city'||p.kind==='town'?10:6,color:color(p,own),fillColor:color(p,own),fillOpacity:.55,weight:2});layer.on('click',()=>selectPlace(p));layer.bindTooltip(esc(p.name),{sticky:true});layer.addTo(placeLayer)}}
  function pointInPoly(pt,poly){let x=pt[1],y=pt[0],inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let xi=poly[i][1],yi=poly[i][0],xj=poly[j][1],yj=poly[j][0],inter=((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi);if(inter)inside=!inside}return inside}
  function selectAt(lat,lng){let best=null;for(const p of places)if(p.geometry?.length>=3&&pointInPoly([lat,lng],p.geometry))if(!best||p.geometry.length>best.geometry.length)best=p;if(best)selectPlace(best);else{const near=places.filter(p=>p.center).sort((a,b)=>map.distance([lat,lng],a.center)-map.distance([lat,lng],b.center))[0];if(near&&map.distance([lat,lng],near.center)<120)selectPlace(near)}}
  function selectPlace(p){selectedPlace=p;window.current=p.id;const st=state(),owned=(st.territories||[]).find(t=>(t.place_id||t.zone_key)===p.id),title=document.getElementById('zoneTitle'),info=document.getElementById('zoneInfo'),claim=document.getElementById('claim');if(title)title.textContent=`${p.kindLabel}: ${p.name}`;if(info)info.textContent=owned?(owned.owner_id===st.user?.id?'Dieses Gebiet gehört deiner Mafia-Familie.':'Dieses Gebiet wird von einer rivalisierenden Mafia kontrolliert.'):`${p.kindLabel}. Du befindest dich im Bereich und kannst ihn übernehmen.`;if(claim)claim.disabled=!!owned||!st.user}
  window.claimRealPlace=async()=>{const st=state();if(!selectedPlace||!st.user)return;const pos=st.marker?.getLatLng();if(!pos){document.getElementById('status').textContent='GPS-Position fehlt.';return}const s=document.getElementById('status');s.textContent='Gebiet wird serverseitig geprüft…';const{data,error}=await window.db.rpc('claim_place',{p_place_id:selectedPlace.id,p_osm_type:selectedPlace.osmType,p_osm_id:selectedPlace.osmId,p_name:selectedPlace.name,p_kind:selectedPlace.kind,p_lat:pos.lat,p_lng:pos.lng,p_geometry:selectedPlace.geometry});if(error){s.textContent=error.message.includes('place_already_owned')?'Dieses Gebiet wurde bereits übernommen.':error.message.includes('not_inside_place')?'Du befindest dich nicht innerhalb dieses Gebiets.':error.message;return}st.profile.money=data.money;st.profile.reputation=data.reputation;if(window.loadTerritories)await window.loadTerritories();drawPlaces();selectPlace(selectedPlace);s.textContent=`${selectedPlace.kindLabel} übernommen. +$${data.reward_money} · +${data.reward_reputation} Reputation`};
  document.getElementById('claim').onclick=()=>window.claimRealPlace();window.updateZoneReal=(lat,lng)=>{fetchPlaces(lat,lng);selectAt(lat,lng)};
  if(window.marker)fetchPlaces(window.marker.getLatLng().lat,window.marker.getLatLng().lng);document.getElementById('status').textContent='Echte Kartenobjekte werden geladen…';
})();
// Integration trigger: v0.7 real-world areas
