/* MAFIVERA V1 — Produktionsmengen */
(()=>{
  'use strict';
  if(window.mtrwProductionInstalled)return;
  window.mtrwProductionInstalled=true;
  const BATCH_MS=30000, INPUT_PER_UNIT=5, MAX_BATCH=100;
  let saveKey='',data=null,observer=null,refreshTimer=null;
  const fmt=n=>Number(n||0).toLocaleString('de-DE');
  const read=()=>{try{return JSON.parse(localStorage.getItem(saveKey)||'{}')}catch(e){return {}}};
  const write=s=>{try{localStorage.setItem(saveKey,JSON.stringify(s))}catch(e){}};
  const toast=t=>{const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._productionToast);e._productionToast=setTimeout(()=>e.classList.remove('show'),2800)};
  const normalize=s=>{s.material=Math.max(0,Math.floor(Number(s.material||0)));s.product=Math.max(0,Math.floor(Number(s.product||0)));if(s.production?.running){s.production.quantity=Math.max(1,Math.floor(Number(s.production.quantity||s.production.output||1)));s.production.input=s.production.quantity*INPUT_PER_UNIT;s.production.output=s.production.quantity;s.production.durationMs=s.production.quantity*BATCH_MS;s.production.startedAt=Number(s.production.startedAt||Date.now())}return s};
  const settle=()=>{data=normalize(read());const p=data.production;if(!p?.running)return false;const elapsed=Date.now()-p.startedAt;if(elapsed<p.durationMs)return false;data.material=Math.max(0,data.material-Number(p.input||0));data.product+=Number(p.output||0);data.production=null;write(data);window.mtrwPlayerEvent?.('Mehrfachproduktion abgeschlossen',{menge:Number(p.output||0),material:Number(p.input||0)});return true};
  const startBatch=qty=>{data=normalize(read());settle();data=normalize(read());if(data.production?.running){toast('Eine Produktion läuft bereits.');return}const available=Math.floor(Number(data.material||0)/INPUT_PER_UNIT),max=Math.min(MAX_BATCH,available);qty=Math.max(1,Math.min(Math.floor(Number(qty)||1),max));if(max<1){toast('Mindestens 5 Material benötigt.');return}if(qty<1){toast('Ungültige Produktionsmenge.');return}data.production={running:true,startedAt:Date.now(),durationMs:qty*BATCH_MS,input:qty*INPUT_PER_UNIT,output:qty,quantity:qty,unitsCompleted:0};write(data);window.mtrwPlayerEvent?.('Produktion gestartet',{menge:qty,material:qty*INPUT_PER_UNIT,dauerSekunden:qty*30});toast(`⚗ ${qty} Drogen in Produktion · ${qty*30} Sekunden`);renderBusiness()};
  const renderBusiness=()=>{const title=document.getElementById('drawerTitle'),body=document.getElementById('drawerBody');if(!title||!body||title.textContent!=='Geschäft')return;data=normalize(read());const p=data.production?.running?data.production:null;const material=Math.floor(Number(data.material||0)),max=Math.min(MAX_BATCH,Math.floor(material/INPUT_PER_UNIT));const old=body.querySelector('[data-a="produce"]');if(!old&&!body.querySelector('.batch-production'))return;const card=body.querySelector('.production-card');if(!card)return;let batch=body.querySelector('.batch-production');if(!batch){batch=document.createElement('div');batch.className='batch-production';card.insertAdjacentElement('afterend',batch)}if(p){const elapsed=Math.max(0,Date.now()-p.startedAt),pct=Math.min(100,elapsed/p.durationMs*100),left=Math.max(0,p.durationMs-elapsed);batch.innerHTML=`<div class="batch-head"><b>⚗ Mehrfachproduktion läuft</b><strong>${fmt(p.output)} Drogen</strong></div><div class="production-progress"><i style="width:${pct}%"></i></div><small>${fmt(p.input)} Material verarbeitet · fertig in ${Math.ceil(left/1000)}s</small>`;if(old)old.remove()}else{batch.innerHTML=`<div class="batch-head"><b>⚗ Produktionsmenge</b><span>5 Material = 1 Droge</span></div><div class="batch-controls"><button type="button" data-minus>−</button><input data-qty type="number" min="1" max="${Math.max(1,max)}" value="${Math.max(1,Math.min(1,Math.max(1,max)))}" inputmode="numeric"><button type="button" data-plus>+</button></div><div class="batch-info"><span>Verfügbar: <b>${fmt(material)} Material</b></span><span>Maximal: <b>${fmt(max)} Drogen</b></span></div><button type="button" class="panel-action batch-start" data-batch-start ${max<1?'disabled':''}>⚗ ${max>1?'Produktion starten':'Droge produzieren'}${max>1?' · Menge auswählen':''}</button>`;const input=batch.querySelector('[data-qty]'),minus=batch.querySelector('[data-minus]'),plus=batch.querySelector('[data-plus]'),start=batch.querySelector('[data-batch-start]');const clamp=()=>{const m=Math.max(1,max);let v=Math.floor(Number(input.value)||1);v=Math.max(1,Math.min(m,v));input.value=v;return v};minus.onclick=()=>{input.value=Math.max(1,(Number(input.value)||1)-1)};plus.onclick=()=>{input.value=Math.min(Math.max(1,max),(Number(input.value)||1)+1)};input.onchange=clamp;start.onclick=()=>startBatch(clamp())} }
  const hideOld=()=>{const body=document.getElementById('drawerBody');if(!body)return;const b=body.querySelector('[data-a="produce"]');if(b)b.remove()};
  const install=async()=>{if(!window.db){setTimeout(install,100);return}const session=(await window.db.auth.getSession()).data.session;if(!session){setTimeout(install,500);return}saveKey='mafivera:v1:save:'+session.user.id;data=normalize(read());const root=document.getElementById('gameRoot');if(root&&!observer){observer=new MutationObserver(()=>{renderBusiness()});observer.observe(root,{subtree:true,childList:true});}hideOld();renderBusiness();if(!refreshTimer)refreshTimer=setInterval(()=>{if(settle()||document.getElementById('drawerTitle')?.textContent==='Geschäft')renderBusiness()},1000)};
  install();
})();
