-- MAFIVERA: complete database audit trail
create table if not exists public.mtrw_audit_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null default gen_random_uuid() unique,
  occurred_at timestamptz not null default now(),
  operation text not null check (operation in ('INSERT','UPDATE','DELETE')),
  schema_name text not null default 'public',
  table_name text not null,
  actor_user_id uuid null,
  subject_user_id uuid null,
  row_key text null,
  old_data jsonb null,
  new_data jsonb null,
  metadata jsonb not null default '{}'::jsonb,
  discord_sent boolean not null default false,
  discord_sent_at timestamptz null,
  discord_error text null
);
create index if not exists mtrw_audit_events_time_idx on public.mtrw_audit_events (occurred_at desc);
create index if not exists mtrw_audit_events_table_idx on public.mtrw_audit_events (table_name, occurred_at desc);
create index if not exists mtrw_audit_events_subject_idx on public.mtrw_audit_events (subject_user_id, occurred_at desc);
create index if not exists mtrw_audit_events_unsent_idx on public.mtrw_audit_events (discord_sent, occurred_at) where discord_sent = false;
alter table public.mtrw_audit_events enable row level security;
revoke all on public.mtrw_audit_events from anon, authenticated;

create or replace function public.mtrw_audit_redact(value jsonb)
returns jsonb language plpgsql immutable set search_path = public as $$
declare result jsonb; item jsonb; key text;
begin
  if value is null then return null; end if;
  if jsonb_typeof(value) = 'object' then
    result := '{}'::jsonb;
    for key, item in select key, value from jsonb_each(value) loop
      if lower(key) ~ '(password|token|secret|access_token|refresh_token|webhook|private_key|service_role|bot_token)' then
        result := result || jsonb_build_object(key, '[REDACTED]');
      else
        result := result || jsonb_build_object(key, public.mtrw_audit_redact(item));
      end if;
    end loop;
    return result;
  elsif jsonb_typeof(value) = 'array' then
    return (select coalesce(jsonb_agg(public.mtrw_audit_redact(x)), '[]'::jsonb) from jsonb_array_elements(value) as e(x));
  end if;
  return value;
end;
$$;

create or replace function public.mtrw_try_uuid(value text)
returns uuid language plpgsql immutable set search_path = public as $$
begin
  if value is null then return null; end if;
  if value ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then return value::uuid; end if;
  return null;
end;
$$;

create or replace function public.mtrw_audit_row_change()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  old_json jsonb;
  new_json jsonb;
  subject_text text;
  row_key_text text;
  actor uuid;
begin
  old_json := case when TG_OP in ('UPDATE','DELETE') then public.mtrw_audit_redact(to_jsonb(OLD)) else null end;
  new_json := case when TG_OP in ('INSERT','UPDATE') then public.mtrw_audit_redact(to_jsonb(NEW)) else null end;
  actor := auth.uid();
  subject_text := coalesce(new_json->>'user_id', old_json->>'user_id', new_json->>'owner_id', old_json->>'owner_id',
    new_json->>'target_user_id', old_json->>'target_user_id', new_json->>'created_by', old_json->>'created_by',
    new_json->>'admin_id', old_json->>'admin_id');
  row_key_text := coalesce(new_json->>'id', old_json->>'id', new_json->>'user_id', old_json->>'user_id',
    new_json->>'zone_key', old_json->>'zone_key', new_json->>'tile_key', old_json->>'tile_key',
    new_json->>'version', old_json->>'version');
  insert into public.mtrw_audit_events(operation,schema_name,table_name,actor_user_id,subject_user_id,row_key,old_data,new_data,metadata)
  values (TG_OP,TG_TABLE_SCHEMA,TG_TABLE_NAME,actor,public.mtrw_try_uuid(subject_text),row_key_text,old_json,new_json,
    jsonb_build_object('transaction_user_id',actor,'database_role',current_user,'source','postgres_trigger'));
  return case when TG_OP = 'DELETE' then OLD else NEW end;
end;
$$;

do $$
declare t record;
begin
  for t in select c.relname as table_name
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    where n.nspname='public' and c.relkind='r' and c.relname not in ('mtrw_audit_events')
  loop
    execute format('drop trigger if exists mtrw_audit_row_change on public.%I',t.table_name);
    execute format('create trigger mtrw_audit_row_change after insert or update or delete on public.%I for each row execute function public.mtrw_audit_row_change()',t.table_name);
  end loop;
end;
$$;
